### ISSUE TITLE
Missing padding causing visual bug and maybe wrog alignment

### ISSUE THREAD

**Issue by WilHolt** [OriginProtocol/origin-dollar#1003]
Hi, I've noticed that is missing some padding in a specific case between maybe 765px to 799px 
and the alignment of the last item looks wrong too, maybe I'm without context, and I'm wrong
![image](https://user-images.githubusercontent.com/25349344/169502188-66127758-e3e5-4967-aa6d-b416f1d16b72.png)

**Comment by sparrowDom** [comment]
Thanks fixed via: https://github.com/OriginProtocol/origin-dollar/commit/e178cefa3734acc0503b3f3d93344135a563dfc5
shall be live in ~30 mins
