### ISSUE TITLE
Reduce default price tolerance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1004]
Let's change the default value here from 0.5% to 0.1% since that's what Curve uses and it's quite unlikely that the user will experience much slippage on stablecoins, particularly if they're minting or redeeming.

<img width="922" alt="Screen Shot 2022-05-23 at 10 26 01 AM" src="https://user-images.githubusercontent.com/273937/169874750-dfabb01b-096c-4f52-b6a2-26b11bd7588f.png">

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/1005 thanks @rolandpo
