### ISSUE TITLE
Allow form interaction without wallet connection

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1007]
Currently, the swap and wrap forms require a wallet to be connected. Otherwise, they aren't rendered and the user can't kick the tires without granting permission to the DApp.

<img width="618" alt="Screen Shot 2022-05-29 at 10 23 11 PM" src="https://user-images.githubusercontent.com/273937/170922730-02ffdc6b-17be-4ddf-ac40-5d22209d11fb.png">

Let's lose this and just go ahead and render the form whether the wallet is connected or not. When the wallet is not connected, the button should say "Connect wallet". When the wallet is connected, the form should behave as it does today. The important part is that the user be able to interact with the form inputs either way.

<img width="617" alt="Screen Shot 2022-05-29 at 10 23 27 PM" src="https://user-images.githubusercontent.com/273937/170923025-88c92f3e-c194-4d7f-89d0-43f38ea9685b.png">

This change will make our DApp more consistent with the experiences that users have on Uniswap and other DApps.

<img width="508" alt="Screen Shot 2022-05-29 at 10 31 12 PM" src="https://user-images.githubusercontent.com/273937/170923220-80eb9bc3-be31-410a-8430-de7906b95ae4.png">

**Comment by rolandpo** [comment]
Would the contract table be displayed if no wallet is connected? Gas estimates wouldn't be able to take allowances into consideration + there would be a very small chance that different routes are shown depending on whether a wallet is connected or not

**Comment by micahalcorn** [comment]
> Would the contract table be displayed if no wallet is connected? Gas estimates wouldn't be able to take allowances into consideration + there would be a very small chance that different routes are shown depending on whether a wallet is connected or not

Yeah, ideally everything would behave the same and the calculations would just assume that there are no existing allowances. If necessary, we could hide the calculations but it would be nice for everything to work without having a wallet connected even if the results are slightly different.

**Comment by rolandpo** [comment]
done in #1009
