### ISSUE TITLE
Adding liquidity to Metapool strategy

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#1010]
[This script](https://github.com/OriginProtocol/origin-dollar/pull/1002/files#diff-c66b7eccb97ac182ee863bf6eff8b1373803079d9f829bc642decb5a9097c788) using brownie forked environment performs various approaches to adding/removing liquidity to meta strategy. Detailed results of various approaches and initial states of the Metapool are captured in [this spreadsheet](https://docs.google.com/spreadsheets/d/1DYSyYwHqxRzSJh9dYkY5kcgP_K5gku6N2mQVhoH33vY/edit#gid=0). Take a closer look to get a good feeling of pros/cons of various approaches. 

**Key takeaways:**
- The more OUSD we mint along with the counterpart of 3Crv when supplying liquidity to the pool the higher the rewards APY:
  - if Convex APY is 7% and we deposit $1 worth of 3crv and mint $1 worth of OUSD we supply $2 worth of LP. Practically doubling the rewards APY to ~14%. Metapool balance stays unchanged. 
  - if we mint $2 worth of OUSD for $1 worth of 3crv we supply $3 worth of LP. Increasing effective rewards APY to 20-21%. That is accounting for slippage loss when removing liquidity which turns out to be minimal 
- there is less slippage cost if we remove liquidity in a balanced manner. Meaning we trade the LP for whatever balance ratio of 3CRV-OUSD the metapool gives us. And subsequently trade OUSD for 3CRV on the pool and vice versa when needed
- If metapool has more 3CRV on balance than OUSD then we can mint whatever amount of OUSD is missing and get the *free* boost of the rewards APY
- If metapool is balanced heavier towards OUSD and we add liquidity in such a manner that the pool end up being balanced (minting less OUSD for 3Crv counterpart) the rewards APY will be less than double of Convex APY
- [assumption] If nothing special is happening to the markets the curve metapool will more or less be balanced

**What liquidity supply strategy should we use:**
- do we want to add liquidity in an unstable manner where Metapool ends up being unbalanced? This would result in an arbitrage opportunity where someone would swap any of the 3 stables for a cheaper OUSD and then redeem the OUSD using our Vault. Which would in turn decrease the TVL in an accelerated pace -> redeeming $1 worth of OUSD will decrease the metapool liquidity at least by $2 or more.
- or do we supply liquidity in such a manner that the pool ends up being balanced. Possibly suffering slight hit to rewards APY especially when pool is heavier in OUSD
- or do we blindly add the 50/50 share of OUSD/3CRV liquidity. Though it seems like a waste to not bank on the free extra APY that would be harvestable in cases where pool tilts more heavily towards 3crv (and we could mint more OUSD)

**Comment by sparrowDom** [comment]
Metapool liquidity research cc
@DanielVF @micahalcorn @franckc @joshfraser 

Would be glad to hear your thoughts

**Comment by micahalcorn** [comment]
Great work @sparrowDom 👍 Does your model take into account the Curve/Convex yield falling as we put more liquidity into the pool? I assume that happens if the CRV/CVX rewards allocated to the pool are fixed and we're adding to the deposits.

For what it's worth, the projected APY is now down to 4% although it changes regularly.

My instinct is to keep it simple and go with the 50/50 strategy when adding to the pool or just maintaining the current balance, whatever it happens to be when adding or removing. Though I don't have a great handle on the math, so I'm open to doing something fancier. I would just prefer to get the strategy deployed and working before we get too fancy trying to optimize the return.

**Comment by sparrowDom** [comment]
That is a great point @micahalcorn thanks, have updated the spreadsheet to take declining APY into account when more liquidity is provided to Convex pool. It is clear that diminishing returns come into play and we should consider how much capital to deploy to Convex Metapool. 

Also have added another test run a bit below with 10 mio CRV deployed next to other tests that deploy 1 mio to showcase how that affects the APY.

**Comment by franckc** [comment]
@sparrowDom Do we need to keep this issue open? is there anything actionable?

**Comment by sparrowDom** [comment]
nothing actionable closing
