### ISSUE TITLE
Round the corners

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1014]
The container for the wrap form should have rounded corners whether the wallet is connected or not. This may not matter after https://github.com/OriginProtocol/origin-dollar/issues/1007 is resolved.

Rounded 👍

<img width="1440" alt="Screen Shot 2022-06-05 at 10 18 43 AM" src="https://user-images.githubusercontent.com/273937/172065033-468ab01b-d394-4eb6-8b3b-827e590b1b8c.png">

Sharp 👎

<img width="1440" alt="Screen Shot 2022-06-05 at 10 18 49 AM" src="https://user-images.githubusercontent.com/273937/172065042-66e3c1af-e0ce-4987-bd5b-53a6f0ab7508.png">

**Comment by rolandpo** [comment]
yes, I do believe #1009 solves this

**Comment by rolandpo** [comment]
done on history page in #1027
