### ISSUE TITLE
Annoying zero state when connecting a wallet

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1016]
When the wallet gets connected, the input field should be empty rather than `0`. This may become irrelevant once #1007 is resolved.

https://www.loom.com/share/54191256783d4639a57b1967c3fc3d49

**Comment by rolandpo** [comment]
yep, this annoyed me too :) already pending fix for this in PR #1011

**Comment by rolandpo** [comment]
done in #1011
