### ISSUE TITLE
Avoid rounding down on OUSD value for wOUSD

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1017]
After wrapping 123.00 OUSD, my current value appeared to be 122.99 at the top. I don't remember this happening with a larger number when I wrapped with a different account, but I may just not have noticed if it was not a round number. Of course, this doesn't matter much once the next rebase happens, but it's not a great experience.

Related to https://github.com/OriginProtocol/origin-dollar/issues/1015 🙃

<img width="1440" alt="Screen Shot 2022-06-05 at 12 11 18 PM" src="https://user-images.githubusercontent.com/273937/172067838-74e33cc5-2abc-404d-9370-ce1c647bdb1b.png">

**Comment by rolandpo** [comment]
done in #1018 but I don't think we're pushing that through

**Comment by rolandpo** [comment]
reconsidered
