### ISSUE TITLE
Curve Compound Pool Strategy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#102]
Create a strategy that deposits tokens to [the Curve Compound pool](https://www.curve.fi/compound) and automatically liquidates earned CRV tokens.

**Comment by franckc** [comment]
Done.

**Comment by micahalcorn** [comment]
@franckc this was a different pool on Curve (not 3pool). We can leave this closed though, as I doubt that we will end up doing it.
