### ISSUE TITLE
Prevent new OGN staking

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1035]
Let's remove these elements and all of the related functionality so that new lock-ups can no longer be initiated from the DApp. Later, we'll disable them at the contract level. It's important, however, that users who have an existing stake can still access it and claim their OGN at maturity.

<img width="977" alt="Screen Shot 2022-07-08 at 1 13 54 PM" src="https://user-images.githubusercontent.com/273937/178064068-7898975e-4d90-4fc2-95dd-39b106323227.png">

**Comment by rolandpo** [comment]
done in #1039
