### ISSUE TITLE
Vertically align nav links on mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1037]
These links have been pushed to the bottom for some reason. This same issue was fixed in https://github.com/OriginProtocol/ousd-governance/pull/192, so it may be as simple as just bringing over the same code.

<img width="412" alt="Screen Shot 2022-07-11 at 1 37 07 AM" src="https://user-images.githubusercontent.com/273937/178223500-dad5ae2d-e1f5-4f5f-95b0-8c53a70c0ac5.png">

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/1042
