### ISSUE TITLE
Ledger account derivation mismatch

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1040]
I have a Ledger Nano X that I'm testing with. The accounts that I'm generating don't match up with any of the options that are shown by our DApp. The first account is the same but the rest are not. It looks like this might be related to https://github.com/OriginProtocol/origin-dollar/issues/21#issuecomment-694997222.

**Ledger Live**
Ethereum 1: 0x**c...** `"freshAddressPath": "44'/60'/0'/0/0"`
Ethereum 2: 0x**9...** `"freshAddressPath": "44'/60'/1'/0/0"`

**ousd.com**
<img width="476" alt="Screen Shot 2022-07-12 at 10 42 04 PM" src="https://user-images.githubusercontent.com/273937/178659361-08eba052-9c7f-4bbe-863d-d457fc3dbdd8.png">

**Comment by micahalcorn** [comment]
As another data point, I connected the Ledger to MetaMask and they offer the same accounts as Ledger Live (also not matching our DApp).

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/1041
