### ISSUE TITLE
Explain unsupported

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1048]
Let's make "Unsupported" clickable either by linkifying it or adding an info icon. Clicking should open a tooltip explaining why the given contract route is not available. It's not very intuitive why "Origin Vault" is always unsupported with DAI, USDC, and USDT as the output. Similarly, everything else is unsupported when the output is Mix.

<img width="595" alt="Screen Shot 2022-07-19 at 8 55 50 PM" src="https://user-images.githubusercontent.com/273937/179894556-c05840a0-bc60-4b4c-a71b-6229c97532d3.png">

**Comment by rolandpo** [comment]
done in #1050
