### ISSUE TITLE
Add Sentry to staging environment

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1051]
Unless I'm mistaken, we're not currently reporting errors to Sentry from staging. Or it's possible that we are but not distinguishing the environment from production.

https://sentry.io/organizations/origin-protocol/issues/?project=5423988

There is at least one issue I'm aware of in staging that isn't reproducible in production, but it would be nice to track it down and fix it because it is distracting when trying to identify other issues with new deployments.

**Comment by franckc** [comment]
When going to Sentry and looking at the dashboard for the OUSD dapp (see https://sentry.io/organizations/origin-protocol/issues/?project=5423988), I don't see a staging environment in the dropdown. I only see production.
So the DApp on staging is probably not populating that argument properly when calling the Sentry API.

<img width="1160" alt="Screen Shot 2022-09-12 at 9 24 23 PM" src="https://user-images.githubusercontent.com/945910/189808482-d2ce34a0-711c-47c4-a6a6-5553c1964026.png">

**Comment by ivanzhelyazkov** [comment]
Added reporting to Sentry on staging environment in PR: #1089
