### ISSUE TITLE
ousd.com redesign MVP: homepage + blog posts page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1055]
Once https://github.com/OriginProtocol/origin-dollar/issues/1054 is done, let's ship at least a minimal version of our new landing pages. I imagine that we'll be ambitious with some more complex improvements (namely, charts/graphs), but we need to quickly move on from what we have now. We should aim to have something up at the end of Sprint 32 that we can continue to improve.

**Comment by franckc** [comment]
@rolandpo Can I volunteer you to work on this? Thanks :)

**Comment by rolandpo** [comment]
sure thing!

**Comment by micahalcorn** [comment]
We'll start with just the homepage: https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=53%3A480

**Comment by franckc** [comment]
The scope of the MVP is homepage + blog posts page.

**Comment by micahalcorn** [comment]
Considering this done 🚪 I will create additional issues for performance-related launch blockers.
