### ISSUE TITLE
Create DeFi Llama Adapter for OGV

### ISSUE THREAD

**Issue by GuzmanMassAdoption** [OriginProtocol/origin-dollar#1062]
In order for Origin Dollar Governance to be tracked on DeFi Llama an adapter will need to be created. 

Below I have provided the steps mentioned in [DeFi Llama's docs](https://docs.llama.fi/list-your-project/submit-a-project).:
If you'd like to list a DeFi project on DefiLlama:
1. Fork the [Adapters repo](https://github.com/DefiLlama/DefiLlama-Adapters) (button towards the top right of the repo page).
2. Add a new folder with the same name as the project to projects/.
3. Write an [SDK adapter](https://github.com/list-your-project/how-to-write-an-sdk-adapter) (or a [fetch adapter](https://github.com/list-your-project/how-to-write-a-fetch-adapter) if you cant use the SDK for this project) in the new folder.
4. Make a Pull Request with the changes on your fork, to the main DefiLlama Adapters repo, with a brief explanation of what you changed.
5. Wait for someone to either comment on or merge your Pull Request. There is no need to ask for someone to check your PR as there a monitored regularly.
6. Once your PR has been merged, please give 24 hours for the front-end team to load your listing onto the UI.

**Comment by rolandpo** [comment]
pending DeFi Llama adapter PR: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3509

**Comment by GuzmanMassAdoption** [comment]
We can close this issue. OGV Staking was included on the OUSD page here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/3518
