### ISSUE TITLE
Maintain swap form state during navigation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1065]
This is a minor edge case, but it confused me for a second when I was using the DApp this morning. The swap form almost maintains its state between route changes, but it's slightly off.

https://www.loom.com/share/80b47082ea104d4d9b8cb37e7eb931f7

**Comment by OrlundoHubbard** [comment]
@micahalcorn I would like to work on this. Is it still open?

**Comment by micahalcorn** [comment]
> @micahalcorn I would like to work on this. Is it still open?

Yes, thanks! I've added you to the organization so that you can push a branch instead of using a fork. Let us know what questions you have as you start to work on it.

**Comment by OrlundoHubbard** [comment]
Awesome! @micahalcorn thank you. Going to read through everything and let you know if I have questions.
