### ISSUE TITLE
Build FAQ page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1077]
Expanding from https://github.com/OriginProtocol/origin-dollar/issues/1055, we'll want to add an FAQ page that will be accessible from the new nav.

‣ [Design in Figma](https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=298%3A750)

**Comment by chandu-jadhav** [comment]
Hey , can I work on this issue?

**Comment by ighmaZ** [comment]
i wanna contribute!

**Comment by micahalcorn** [comment]
@chandu-jadhav @ighmaZ ping me in the #ousd-engineering Discord channel if you're interested in picking up an issue.

**Comment by ighmaZ** [comment]
hi @micahalcorn , how do i start?
