### ISSUE TITLE
Build OGV burn page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1079]
Leading up to the OGV burn on October 10th, we'll want to promote a landing page that shows a countdown, how many tokens have gone unclaimed and will be burned, as well as with some other stats and content.

‣ Design in Figma (coming soon)

**Comment by tomhirst** [comment]
I made a quick page on the governance dApp for this to tide us over: https://governance.ousd.com/burn

@rolandpo There might be some useful math for you here: https://github.com/OriginProtocol/ousd-governance/blob/0b4313155c289633ecc4894de4bdb455e0bc5b9b/client/pages/burn.tsx#L57
