### ISSUE TITLE
Rinkeby -> Goerli migration

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#1080]
With The Merge happening in just a few days from now, we should migrate from Rinkeby to Goerli.
Alchemy mentioned they'll stop supporting Rinkeby by October 5th.

We should look for references and use of Rinkeby in our 3 repos and replace with Goerli:
 - [x] OUSD: https://github.com/OriginProtocol/origin-dollar/
 - [x] OUSD governance: https://github.com/OriginProtocol/ousd-governance
 - [x] OUSD analytics: https://github.com/OriginProtocol/ousd-analytics

Non exhaustive list of things to look for:
 - Chain ID 4
 - string "rinkeby" or "Rinkeby"

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/ousd-governance/issues/286

**Comment by tomhirst** [comment]
@ivanzhelyazkov Loose process I had planned for OUSD governance:

1. Deploy contracts to Goerli
1. Set up a new Heroku environment for Goerli (with database)
1. Set it to auto-deploy from the `staging` branch
1. Update the environment vars as appropriate (`https://eth-goerli.alchemyapi.io/v2/...` etc.)

**Comment by ivanzhelyazkov** [comment]
OUSD governance contracts PR for the migration:
https://github.com/OriginProtocol/ousd-governance/pull/333
OUSD repo don't use a testnet environment - Master and Staging are connected to the mainnet deployment (there are deprecated Rinkeby references though)
OUSD analytics repo doesn't have any Rinkeby references

**Comment by ivanzhelyazkov** [comment]
For OUSD-governance deployed new governance contracts on Goerli, connected the UI to the new contracts and replaced all Rinkeby references with Goerli, as well as tested the entire workflow from submitting a proposal to voting.
For Origin-dollar removed all Rinkeby references and tested that staging works correctly.
