### ISSUE TITLE
Code Review of OGV ERC20 Governance Token

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#1087]
Contract:
https://github.com/OriginProtocol/ousd-governance/blob/master/contracts/GovernanceToken.sol
https://etherscan.io/address/0x9c354503c38481a7a7a51629142963f98ecc12d0

Tests:
https://github.com/OriginProtocol/ousd-governance/blob/master/tests/test_token.py

Deploy Script:
https://github.com/OriginProtocol/ousd-governance/blob/master/scripts/deploy_token.py

**Comment by DanielVF** [comment]
Note that these dependancies are openzeppelin-contracts-upgradeable so there may be important differences with the standard OZ contracts.

**Comment by DanielVF** [comment]
### Dependencies
- [x] Have read all OZ smart contract dependencies.
- [x] No rentrancy. 

### Access control

The contract combines two different access control methodologies. It use both the single address owner style, and the role based style. Currently no admins for the role base style are set, so minter access control for now is only through the owner-style method.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/837/190254340-ca7cba89-5668-4023-a1e1-c9aa191353cc.png">

Note that if we ever need to remove a minting address, we'll need to add a default admin before being able to call remove role. (Also minters can remove themselves from minting, via the roles system, even though we don't have an explicit method for that in the top-level contract.)

The current setup should be fine, but neither side auth system gives a full picture of permissions, and this could cause problems down the line if future developers are not aware of it. I don't think we should change it, but perhaps we should not it in contract comments.

**Comment by sparrowDom** [comment]
Interestingly owner ( 0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899 ) has the default admin role:
<img width="1340" alt="Screenshot 2022-09-16 at 00 22 59" src="https://user-images.githubusercontent.com/579910/190519220-10f7b4f7-8081-4cc6-8aa5-0bfebe749557.png">

**Comment by sparrowDom** [comment]
All the OpenZeppelin dependencies: 
- [ERC20BurnableUpgradeable.sol  ](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/token/ERC20/extensions/ERC20BurnableUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [OwnableUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/access/OwnableUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [AccessControlUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/access/AccessControlUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [UUPSUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/proxy/utils/UUPSUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [Initializable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/proxy/utils/Initializable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [ERC20Upgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/token/ERC20/ERC20Upgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [ContextUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/utils/ContextUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [StringsUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/utils/StringsUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [ERC165Upgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/utils/introspection/ERC165Upgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [AddressUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/utils/AddressUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [ERC1967UpgradeUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense
- [StorageSlotUpgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.6.0/contracts/utils/StorageSlotUpgradeable.sol)
  - [x] code doing what we expect for our use case
  - [x] all ACL / init states make sense

All the transactions that modified state of the contract other than Approve & Transfer transactions using [Dune Query](https://dune.com/queries/1276264): 
- [0x9295cac246169f06a3d4ec33fdbd87fced7a9e19ea61177cae75034e45ae66f4](https://etherscan.io/tx/0x9295cac246169f06a3d4ec33fdbd87fced7a9e19ea61177cae75034e45ae66f4)
  - Logs:
    - **Upgraded** to implementation address: 0x6cE89Ff1E8a910007BAc236C27B88f8a95B0bFaD
    - **OwnershipTransferred** **from**: 0x0000000000000000000000000000000000000000 **to** [0x71f78361537a6f7b6818e7a760c8bc0146d93f50](https://etherscan.io/address/0x71f78361537a6f7b6818e7a760c8bc0146d93f50) -> Origin Dollar Deployer
    - **Transfer** -> Minting 1b OGV to Origin Dollar Deployer
- [0x6f1073a4e58d3e541c590cc80e6e9371d510a348f872bdc193031fa76c674668](https://etherscan.io/tx/0x6f1073a4e58d3e541c590cc80e6e9371d510a348f872bdc193031fa76c674668)
  - Logs:
    -  **OwnershipTransferred from** [0x71f78361537a6f7b6818e7a760c8bc0146d93f50](https://etherscan.io/address/0x71f78361537a6f7b6818e7a760c8bc0146d93f50) -> Origin Dollar Deployer **to** 0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899 -> 5/8 Multisig
- [0xc172f6285b063de7ff248d50c3afe5ab0f358ac7a532e9cc4ae757b452edc56e](https://etherscan.io/tx/0xc172f6285b063de7ff248d50c3afe5ab0f358ac7a532e9cc4ae757b452edc56e)
  - Logs:
    - **Upgraded** to implementation address: [0xed6e3808fce0c4a52dea8636933f666c6dea4d1d](https://etherscan.io/address/0xed6e3808fce0c4a52dea8636933f666c6dea4d1d)
    - **RoleGranted** DEFAULT_ADMIN_ROLE to 0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899 -> 5/8 Multisig
    - **ExecutionSuccess** 🔴 [event contains](https://etherscan.io/tx/0xc172f6285b063de7ff248d50c3afe5ab0f358ac7a532e9cc4ae757b452edc56e#eventlog) TX hash I am unable to locate on etherscan 0x0C68FC717CEDA379C25BF24C8A5791A773DD5AD95991416943B3147C74C5B805
- [0x83d83e8015108d7f72d6ff80a637abec96572af3be1a5d174dfb12feb9ad85a5](https://etherscan.io/tx/0x83d83e8015108d7f72d6ff80a637abec96572af3be1a5d174dfb12feb9ad85a5)
  - Logs:
    - **GovernorshipTransferred** from [0x69e078ebc4631e1947f0c38ef0357de7ed064644](https://etherscan.io/address/0x69e078ebc4631e1947f0c38ef0357de7ed064644) -> Origin Protocol Deployer **to** [0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899](https://etherscan.io/address/0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899) -> 5/8 Multisig
    - **GovernorshipTransferred**  (emitted twice) from [0x69e078ebc4631e1947f0c38ef0357de7ed064644](https://etherscan.io/address/0x69e078ebc4631e1947f0c38ef0357de7ed064644) -> Origin Protocol Deployer **to** [0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899](https://etherscan.io/address/0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899) -> 5/8 Multisig
    - **RoleGranted** MINTER_ROLE to [0x7d82e86cf1496f9485a8ea04012afeb3c7489397](https://etherscan.io/address/0x7d82e86cf1496f9485a8ea04012afeb3c7489397) -> Reward Source Proxy
    - **ExecutionSuccess** 🔴 Again can not locate tx hash 0x 616F45986321AFB7DAA415C1BF74B349853F27526A74F5FB45C3981AA1214477

🟢 OpenZeppelin Access Control roles are OK
🟢 5/8 Multisig is the owner and also has the DEFAULT_ADMIN_ROLE
🟢 the logic in OpenZeppelin contract doesn't perform unexpected things
🟢 no state changes to contract that would be suspicious
🟠 couple of **ExecutionSuccess** events above have transaction hash info I can not resolve
🟠 have not checked that deployed code corresponds to expected source files

**Comment by DanielVF** [comment]
Thanks for that catch, Domen, on the default admin permissions. I checked that this permissions weren't granted before the handover, but hadn't checked the event logs. 

We'll need to be sure to change these permissions to when we switch over ownership of this contract in the future away from the multisig.

**Comment by DanielVF** [comment]
I have verified all dependency sources on both the proxy and the implementation.

I don't think you need do this also @sparrowDom.
