### ISSUE TITLE
Launch Buyback to Mainnet

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#1093]
TODO
 - [x] One PR Deployed, awaiting deploy review (Domen + Shah)
 - [x] One PR is waiting a deploy script and deploy (Domen + Shah)
 - [x] Update monitoring (Domen + Shah)

**Comment by shahthepro** [comment]
[This PR](https://github.com/OriginProtocol/ousd-analytics/pull/226) should take care of the monitoring
