### ISSUE TITLE
Guaranteed Amounts vs Approximation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#111]
Our buying/minting form includes a disclaimer about the resulting OUSD being an approximate amount. Arguably, our selling/redeeming form should also include this.

<img width="562" alt="Screen Shot 2020-08-28 at 11 02 36 AM" src="https://user-images.githubusercontent.com/273937/91601251-28249c00-e91e-11ea-9c72-c1c29d12c8d4.png">

This is an approximation due to possible movements in the exchange rate(s) for the stablecoin(s) involved in the transaction between the time that the form is rendered and the time that the transaction is constructed in the contract. If https://github.com/oplabs/origin-dollar/issues/90 were to account for depth of liquidity, then there could also be slippage. With the introduction of https://github.com/oplabs/origin-dollar/issues/110, there would be actual slippage.

My hypothesis is that, as we move toward a more mainstream userbase, the approximation of prices and lack of clarity might be a deterrent that causes people to abandon the transaction. Less sophisticated users might actually prefer a worse price if they don't have to think about price fluctuations. Uniswap addresses the slippage problem by promising a minimum output below and estimated output. We should consider doing something similar.

Alternatively, I'm wondering if it's possible for us to give the user the specific amount that they ask for, account for slippage in the rate, and then collect any bonus/excess resulting OUSD (or unconverted stablecoin) as revenue for either the pool itself or for governance token. This would create a small revenue opportunity and also give users a cleaner transaction that is easier to mentally process. I suppose this could be considered "OUSD as a market maker".

@matthewliu points out that this might involve significant amounts of money for users transacting with large amounts or people for whom a few dollars is very meaningful. Users who understand what's happening might be frustrated that they're losing money on their transactions. It would probably also depend on the APY that they're likely to enjoy and the gas costs associated with their transactions.

**Comment by micahalcorn** [comment]
With the advent of https://github.com/OriginProtocol/origin-dollar/pull/390 and https://github.com/OriginProtocol/origin-dollar/pull/410, our contracts now have the ability to abandon mints and redeems if the output is less than expected. We'll implement a frontend config feature for the user to set a threshold for oracle price movement much like slippage parameters on AMMs. My alternate solution proposed above might make sense with more mainstream users who are less familiar with AMMs, but those aren't likely our target users with this DApp. We probably want them to just buy OUSD on centralized exchanges or with fiat onramps when the time comes.

**Comment by micahalcorn** [comment]
According to @sparrowDom, the DApp currently passes an amount that will cause the transaction to fail if the output would be 3% below $1 rather than 3% below the expected output. We'll design a way for the user to configure the threshold to a specific percentage and then update the calculation to be based on output instead of peg when we implement the user-facing improvements.

**Comment by micahalcorn** [comment]
Here are the designs for allowing the user to see and change the threshold:

- [mint](https://zpl.io/29X3W6B)
- [redeem](https://zpl.io/2jAKzjA)

**Comment by sparrowDom** [comment]
solved via: https://github.com/OriginProtocol/origin-dollar/pull/544
