### ISSUE TITLE
Transition to new governance

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#1125]
We want to **safely** transition to OUSD contracts being owned by the new community governance system.

Objectives:

- [ ] All contracts are moved off old governance systems to the new governance system
- [ ] All active OUSD contracts are moved to the new governance system
- [ ] All new governance contracts are owned by the new governance system
- [x] Contract registry docs are up to date.
- [x] Examined inactive contracts for anything we need to pay attention to in the future.

In this case **safety** means:

1. Community can pass and execute governance actions
2. Bad guys can't do these things.
3. All contracts end up with the correct ownership.

### Background

<img width="533" alt="image" src="https://user-images.githubusercontent.com/837/193635092-97cbd047-aa85-4b88-828d-19f74e5afc78.png">

In our new governance system, we have a circular loop of ownership, since OGV controls veOGV, which controls voting, which controls the timelock, which controls OGV. Once we switch governance over, each of these contracts needs to keep working correctly, or we loose the ability to pass further proposals. (well, OGV could die, and previous staked governance powers would stay working). No pressure.

Previously I had been thinking we would do the governance transition in two phases, first moving control of all contracts over to the governance system, then later moving control of the governance system over to the governance system. However after more thinking about it, I don't think this gains us much. It does not mitigate a bug or misconfiguration giving uncontrolled access. And in order for governance to transition over, we'll need to use the new system to accept governance, talking to the very contracts that we need to control. In this case, we might as well just do it in one pair of transactions.

### 1. Survey contracts

We want to be sure that we move all contracts over to this new system. This will be OUSD's third governance contract, and we have some unused contracts still owned by old contracts. It would be good to all old contracts over, so that in the future we can fully depreciate the old governance contracts and don't have to have the future need of spending time digging on how to access the old governance contracts. 

1. We should get a clean list of currently active contracts from an on chain tour (and verify that the docs are updated with these addresses.)
2. We should dig up a list of past contracts/proxies, then check governorship on them. Particularly we should locate the old OUSD vault proxy, since it may have user approvals on it.

### 2. Transfer ownership from old governance system

We'll need to generate a transaction on the current governance system and on the past governance system transferring ownership/governership on all contracts. This will have a two day timelock on it.

We'll also need to make a governance action on the old governor for the contracts on it.

### 3. Accept ownership from new system.

The new governance system will need to accept ownership on all these contracts. This will have the voting period and the timelock period, so we can start the process at the same time as starting governance actions on previous contracts.

**Comment by franckc** [comment]
Thanks for writing this up! High level plan LGTM.

For 1.2 (survey of old contracts), we could check the commit history for the registry page on docs.ousd.com, or also look at the on-chain transactions initiated by the multisig against the governor as part of governance proposal queueing/execution. Or we could also look at our launch plan xsheet since we typically record the deployed contract address in there.

Now, maybe for extra safety and validation we could split things into 2 batches:
 - batch 1 (executed first): transfer ownership of old contracts
 - batch 2 (executed second): transfer ownership of currently active contracts

**Comment by franckc** [comment]
CC @sparrowDom @shahthepro @micahalcorn

**Comment by sparrowDom** [comment]
LGTM

Would be also cool to test run the two batches on forked network. And write tests that after the transfer of ownership contracts remain functional and upgradeable.  

Also thinking it would probably be really convenient to have `ousd-governance` and `origin-dollar` repos merged into the same one.

**Comment by DanielVF** [comment]
Will do the two transitions, old then new @franckc .

**Comment by DanielVF** [comment]
Code to scrape active contracts and owners:

```python
from world import *


VAULT_ADMIN_SLOT = 0xa2bd3d3cf188a41358c8b401076eb59066b09dec5775650c0de4c55187d17bd9


CONTRACTS = []
CONTRACTS_CACHE = {}

def tryread_address(address, data):
	output = None
	try:
		output = web3.eth.call({'to':address, 'data':data})[12:].hex()
	except:
		pass
	if output and output != "0x":
		return output


def crawl(address, name=None):
	address = address.lower()
	if address in CONTRACTS_CACHE:
		return CONTRACTS_CACHE[address]
	contract = Contract.from_explorer(address)
	if not name:
		name = repr(contract).split(" ")[0][1:]
	contract.__NAME = name
	print("Crawl %s %s" % (name, address))

	# record governor

	contract.__GOVERNOR = "                                          "
	for x in ['0x8da5cb5b', '0x0c340a24']:
		gov = tryread_address(contract.address, x)
		if gov:
			contract.__GOVERNOR = gov
			break

	# Crawl IMPL
	impl = tryread_address(contract.address, '0x5c60da1b')
	if impl:
		crawl(impl)
	
	CONTRACTS_CACHE[address] = contract
	CONTRACTS.append(contract)
	return contract

def crawl_strategy(address):
	contract = crawl(address)
	harvester = crawl(contract.harvesterAddress())
	crawl(harvester.rewardProceedsAddress())

def crawl_vault(address):
	vault = crawl(address)
	admin_impl = web3.eth.getStorageAt(vault.address, VAULT_ADMIN_SLOT )[12:].hex()
	vault_admin = crawl(admin_impl)
	crawl(vault.priceProvider())
	buyback = crawl(vault.trusteeAddress(), "Buyback")

	for x in vault.getAllStrategies():
		crawl_strategy(x)



crawl(ousd.address, "OUSDProxy")
crawl_vault(ousd.vaultAddress())
crawl("0xD2af830E8CBdFed6CC11Bab697bB25496ed6FA62","wOUSDProxy")
crawl("0x9c354503c38481a7a7a51629142963f98ecc12d0", "OGVProxy")
crawl("0x0c4576ca1c365868e162554af8e385dc3e7c66d9", "veOGVProxy")
crawl("0x7d82e86cf1496f9485a8ea04012afeb3c7489397") # Rewards
crawl("0xcecaD69d7D4Ed6D52eFcFA028aF8732F27e08F70") # Flipper



for contract in CONTRACTS:
	print("%s\t%s\t%s" %(contract.__GOVERNOR, contract.address, contract.__NAME))


```

**Comment by DanielVF** [comment]
Active:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/837/194144797-001693aa-d5ce-49f7-825f-5cba237c64af.png">

**Comment by DanielVF** [comment]
Notable inactive contracts:

- Old vault proxy 0x277e80f3E14E7fB3fc40A9d6184088e0241034bD. Still has approvals on it from users.
- Old buyback 0x77314EB392b2be47C014cde0706908b3307Ad6a9. Still has a bit of OGV, OGN, and a little OUSD on it
- Old compensation claims contract 0x9C94df9d594BA1eb94430C006c269C314B1A8281. Still has 22.8K OUSD on it.

**Comment by DanielVF** [comment]
Contracts to migrate to new system:


#### 🟦 DVF Deployer (0x69e078ebc4631e1947f0c38ef0357de7ed064644) Status: Ready to accept

Address | Name
-|-
0x48Cf14DeA2f5dD31c57218877195913412D3278A | VaultCore

#### 🟨 Old Governor (0x830622bdd79cc677ee6594e20bbda5b26568b781) Status: In timelock

Address | Name
-|-
0x9C94df9d594BA1eb94430C006c269C314B1A8281 | CompensationClaims
0xD5433168Ed0B1F7714819646606DB509D9d8EC1f | CompoundStrategyProxy
0x9f2b18751376cF6a3432eb158Ba5F9b1AbD2F7ce | InitializeGovernedUpgradeabilityProxy
0x3c5fe0a3922777343CBD67D3732FCdc9f2Fa6f2F | ThreePoolStrategyProxy

#### 🟥 Old Governor (0x8a5ff78bfe0de04f5dc1b57d2e1095be697be76e)

Address | Name
-|-
0x52BEBd3d7f37EC4284853Fd5861Ae71253A7F428 | MinuteTimelock

#### 🟥 Old Governor (0x8e7bdfecd1164c46ad51b58e49a611f954d23377)

Address | Name
-|-
0x017aD99900b9581Cd40C815990890EE9F0858246 | ChainlinkOracle
0x843530DC8005e13dEA30CEa2394FF60635f38cc4 | MixOracle

#### 🟥 Old Timelock (0x52bebd3d7f37ec4284853fd5861ae71253a7f428)

Address | Name
-|-
0x12115A32a19e4994C2BA4A5437C22CEf5ABb59C3 | CompoundStrategyProxy
0x47211B1D1F6Da45aaEE06f877266E072Cf8BaA74 | CompoundStrategyProxy
0x051CaEFA90aDf261B8E8200920C83778b7B176B6 | InitializeGovernedUpgradeabilityProxy
0x277e80f3E14E7fB3fc40A9d6184088e0241034bD | InitializeGovernedUpgradeabilityProxy
0x4d4f5e7a1FE57F5cEB38BfcE8653EFFa5e584458 | MixOracle
0xe40e09cD6725E542001FcB900d9dfeA447B529C0 | ThreePoolStrategyProxy

#### 🟥 Current Governor (0x72426ba137dec62657306b12b1e869d43fec6ec7)

Address | Name
-|-
0x6C5cdfB47150EFc52072cB93Eea1e0F123529748 | Buyback
0x7294CD3C3eb4097b03E1A61EB2AD280D3dD265e6 | Buyback
0x77314EB392b2be47C014cde0706908b3307Ad6a9 | Buyback
0xEA2Ef2e2E5A749D4A66b41Db9aD85a38Aa264cb3 | ConvexStrategyProxy
0x21Fb5812D70B3396880D30e90D9e5C1202266c89 | HarvesterProxy
0x80C898ae5e56f888365E235CeB8CEa3EB726CB58 | HarvesterProxy
0x9c459eeb3FA179a40329b81C1635525e9A0Ef094 | InitializeGovernedUpgradeabilityProxy
0x5e3646A1Db86993f73E6b74A57D8640B69F7e259 | InitializeGovernedUpgradeabilityProxy
0x501804B374EF06fa9C427476147ac09F1551B9A0 | InitializeGovernedUpgradeabilityProxy
0x2A8e1E676Ec238d8A992307B495b45B3fEAa5e86 | OUSDProxy
0xE75D77B1865Ae93c7eaa3040B038D7aA7BC02F70 | VaultProxy
0xD2af830E8CBdFed6CC11Bab697bB25496ed6FA62 | WrappedOUSDProxy

#### 🟥 Current Multisig (0xbe2ab3d3d8f6a32b96414ebbd865dbd276d3d899)

Address | Name
-|-
0x9c354503C38481a7A7a51629142963F98eCC12D0 | ERC1967Proxy
0x72426BA137DEC62657306b12B1E869d43FeC6eC7 | Governor
0x830622BDd79CC677eE6594E20bBda5B26568b781 | Governor
0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9 | OgvStakingProxy
0xE82191eF8996852a802aaE509993770480F9CA2C | RewardsSource
0x7d82E86CF1496f9485a8ea04012afeb3C7489397 | RewardsSourceProxy

#### 🟥 Old Multisig (0xe011fa2a6df98c69383457d87a056ed0103aa352)


Address | Name
-|-
0x8DE3Ac42F800a1186b6D70CB91e0D6876cC36759 | ChainlinkOracle
0x8e7bDFeCd1164C46ad51b58e49A611F954D23377 | Governor
0xa8f14F558aC70F5f52C37cD96d802ef9210023C5 | OpenUniswapOracle
0x2693C0eCcb5734EBd3910E9c23a8039401a73c87 | Timelock

**Comment by DanielVF** [comment]
OGV Governance contracts to be owned:

-|Address|Name|Facts
-|-|-|-
🟥 |0x9c354503C38481a7A7a51629142963F98eCC12D0 | OGVProxy  | (proxy, no impl owner) [transferOwnership]
🟥 |0x0C4576Ca1c365868E162554AF8e385dc3e7C66D9 | veOGVProxy  | (proxy, no impl owner) [transferGovernance]
🟥 |0x7d82E86CF1496f9485a8ea04012afeb3C7489397 | RewardsSourceProxy  | (proxy) [transferGovernance]
🟥 |0xE82191eF8996852a802aaE509993770480F9CA2C | RewardsSource  | (impl) [transferGovernance]

OGV contracts that are unownable/don't need ownership:

-|Address|Name|Facts
-|-|-|-
▪️ |0x35918cDE7233F2dD33fA41ae3Cb6aE0e42E0e69F|Timelock| controlled by governor
▪️ |0x3cdd07c16614059e66344a7b579dab4f9516c0b6|Governance|controlled by voting
▪️ |0x7dfafe7d547fc9083719d633b9c5f6f542c42c77|OGV Imp| zero'd owner impl
▪️ |0xd313c06fa0e5d7286f28fa688e09248cb644295e|veOGV Imp | no gov code in impl

**Comment by DanielVF** [comment]
The OGV `transferOwnership` is going to be instant, with no `acceptOwnership` afterwords.

**Comment by DanielVF** [comment]
Tentative switchover code.

Testing both multisig and governance.

```python
# --------------------------------
# Jan 20, 2022 - Move ownership of new governance to new governance
# 

from world import *
from allocations import *
from ape_safe import ApeSafe

veogv_proxy = Contract.from_abi('veogv_proxy', veogv, rewards_source.abi)
rewards_source_impl = Contract.from_abi('rewards_source_impl', '0xE82191eF8996852a802aaE509993770480F9CA2C', rewards_source.abi)

with TemporaryFork():
    # Create old governance internal transactions
    print(ogv.owner())
    print(veogv_proxy.governor())
    print(rewards_source.governor())
    print(rewards_source_impl.governor())
    txs = [
        ogv.transferOwnership(TIMELOCK, {'from': GOV_MULTISIG}),
        veogv_proxy.transferGovernance(TIMELOCK, {'from': GOV_MULTISIG}),
        rewards_source.transferGovernance(TIMELOCK, {'from': GOV_MULTISIG}),
        rewards_source_impl.transferGovernance(TIMELOCK, {'from': GOV_MULTISIG}),
    ]
    print(ogv.owner())
    print(veogv_proxy.governor())
    print(rewards_source.governor())
    print(rewards_source_impl.governor())

    # # Test Claim Ownership
    accept_txs = []
    with TemporaryFork():
        for x in [veogv_proxy, rewards_source, rewards_source_impl]:
            accept_txs.append(x.claimGovernance({'from': TIMELOCK}))

    governor_five.propose(
        [x.receiver for x in accept_txs],
        [0 for x in accept_txs],
        ['claimGovernance()' for x in accept_txs],
        [x.input[10:] for x in accept_txs],
        "Claim governance on old contracts\n\nMoves a selection of old contracts from old goverance to the new.",
        {'from': GOV_MULTISIG }
    )

    print("Raw proposal:")
    print(history[-1].receiver)
    print(history[-1].input)
    print(history[-1].events)
    proposal_id = history[-1].events['ProposalCreated'][0]['proposalId']
    print(proposal_id)

    print("...Simulating vote")
    chain.mine()
    governor_five.castVote(proposal_id, 1, {'from': GOV_MULTISIG})

    print("...Simulating voting time, going to take time")
    chain.mine(governor_five.votingPeriod() + 1)

    print("...Simulating queue")
    governor_five.queue(proposal_id, {'from': GOV_MULTISIG})
    chain.mine(timedelta=2*24*60*60+2)

    print("...Simulating execution")
    governor_five.execute(proposal_id, {'from': GOV_MULTISIG})

    print(ogv.owner())
    print(veogv_proxy.governor())
    print(rewards_source.governor())
    print(rewards_source_impl.governor())

safe = ApeSafe(GOV_MULTISIG)
safe_tx = safe.multisend_from_receipts(txs)
safe.sign_with_frame(safe_tx)
r = safe.post_transaction(safe_tx)
```

**Comment by DanielVF** [comment]
We've completed the transfer of the OGV Governance contracts

**Comment by franckc** [comment]
We've transferred the ownership of the OUSD contracts. Done! Woohoo :)
