### ISSUE TITLE
Strategies testing framework

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#1133]
High level idea:

- We've been writing duplicate test cases for every strategy. Need refactor
- We should test every single strategy individually
- Fork testing
- Front-running tests would be very valuable
- Differentiate default vs non-default strategy
- For ex Morpho should be a drop-in replacement for Comp in terms of testing

**Comment by franckc** [comment]
Stretch goal for SP37

**Comment by DanielVF** [comment]
Fundamentally in place with the fork tests.
