### ISSUE TITLE
Restrict Input Values

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#114]
On our buying and selling forms, the input fields should not allow the user to type in letters and random characters. We should use a key event (press, down, up) and prevent the invalid characters from appearing in the field. The same is true for repeated use of the decimal character, for example. There may be an existing React component that we can use for this.

**Comment by cipherzzz** [comment]
you can assign this to me

**Comment by cipherzzz** [comment]
Can you give me a list of restricted input? a bit more specific - @micahalcorn

**Comment by micahalcorn** [comment]
> Can you give me a list of restricted input? a bit more specific - @micahalcorn

I think the only permitted characters should be as follows:

```
1
2
3
4
5
6
7
8
9
0
.
```

Ideally, use of the period character (`.`) would be restricted to a maximum of one instance per input field.

A bonus restriction would be a maximum number precision based on the relevant currency's `decimals` value (`6` for USDC/T and `18` for DAI/OUSD).
