### ISSUE TITLE
Replace HTML meta images

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1168]
This image appears when the site is linked on Twitter, Facebook, Discord, etc. It should be replaced with something following the style of the new site.

<img width="517" alt="Screen Shot 2022-11-07 at 9 19 03 AM" src="https://user-images.githubusercontent.com/273937/200373900-9a1fe897-3aad-4f79-b760-aa2df46a697d.png">

**Comment by matt-bullock** [comment]
Attached jpg and png formats

![OUSD Meta Tag Image](https://user-images.githubusercontent.com/39496225/200682846-321aecfc-01a3-4c75-8999-8b149a83173f.jpg)
![OUSD Meta Tag Image](https://user-images.githubusercontent.com/39496225/200682852-9a3f9924-6ee3-4ccd-ba89-0324daf2d4ad.png)
