### ISSUE TITLE
Waffle fixtures don't revert properly

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#117]
I had to commend out these tests https://github.com/oplabs/origin-dollar/blob/fee4ba2557589cb87a777de207769b02827d83f1/contracts/test/vault.js#L384-L402

Waffle doesn't seem to be reverting these [fixtures](https://ethereum-waffle.readthedocs.io/en/latest/fixtures.html) as the state is hanging around. It might be something to do with the proxy setup and the vault implementation being replaced by the mock vault.

**Comment by DanielVF** [comment]
Happening in this PR.

https://github.com/OriginProtocol/origin-dollar/pull/499
