### ISSUE TITLE
TUSD-3Crv strategy deployment

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1179]
Pending governance approval, create a proposal to deploy the TUSD-3Crv implementation of the generalized Convex strategy.

**Comment by sparrowDom** [comment]
The PR for it is here: https://github.com/OriginProtocol/origin-dollar/pull/1190 and ready to be deployed. We have some considerations [in this doc](https://docs.google.com/document/d/1vfzD3M-3CzAwU46XeZOoWiV3XI2lLMnjoCM42UOqseA/edit)  that we want to get clarity on before continuing

**Comment by micahalcorn** [comment]
Closing this since the work was done although we decided not to move forward at this time 😔
