### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1187]
An error is thrown when someone visits an invalid route. Let's handle this properly with a 404 and consider whether or not to use the same design across all sites.

https://staging.ousd.com/wrong

See https://github.com/OriginProtocol/website-frontend/issues/11 😐

**Comment by matt-bullock** [comment]
Design is here: https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2354%3A23875&t=SoRBE4EYvmBZ82C6-1

The same template can be used on Origin and Origin Story sites with the appropriate colour changes @micahalcorn
