### ISSUE TITLE
Ousd Governance Brave + Metamask wallet connect

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#1192]
@joshfraser had an issue connecting to [OUSD governance Dapp](https://governance.ousd.com/) with. the combination of Mac + Brave + Metamask. Resulting in this error: 
![Screenshot_2022-11-20_at_4 35 13_PM](https://user-images.githubusercontent.com/579910/203436160-3389fe42-d04c-4f2a-bab8-b7a17c5e93e1.png)

@sparrowDom couldn't reproduce it on Mac + Brave (1.45.127) + Metamask (10.22.1) environment.

**Comment by sparrowDom** [comment]
@joshfraser can you add Brave + Metamask versions you are using please ☝️

**Comment by joshfraser** [comment]
It seems to have been a transient issue that has since gone away. I think we can close this for now.
