### ISSUE TITLE
Strategy monitoring: engineering design doc

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1193]
As discussed in this week's community call 📄

**Comment by franckc** [comment]
@sparrowDom @shahthepro How are we doing on this doc? Would be great to share and finalize it since having the monitoring in place will be blocking for deploying any convex generalized strategy.

**Comment by sparrowDom** [comment]
just started doing this, will share when I have smth

**Comment by sparrowDom** [comment]
The design document is here: https://docs.google.com/document/d/17WXnkAKFEk2QNASmljCT8_P_Bib8svxGdjm-GFxLCuU/edit#heading=h.6n1ka1lh01ho
