### ISSUE TITLE
Heroku Migration

### ISSUE THREAD

**Issue by shahthepro** [OriginProtocol/origin-dollar#1214]
We should migrate all the DApp and sites from GCP to Heroku, since that'd make it easier for us to maintain/deploy and help reduce some infra costs as well

**Comment by franckc** [comment]
- [ ] dapp.ousd.com
  - [ ] analytics.ousd.com

**Comment by shahthepro** [comment]
Closing this since the migration is done. I'll create another issue for deprecating GAE
