### ISSUE TITLE
Slippage parameters

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#124]
Define maximum tolerances for slippage for actions like liquidating COMP tokens or entering yCRV.

**Comment by franckc** [comment]
@sparrowDom This was implemented as part of the harvester and is configurable, right?
https://github.com/OriginProtocol/origin-dollar/blob/0d30731f7167da0f410db469baaaf74897408cf6/contracts/contracts/harvest/Harvester.sol#L389

Closing. Please re-open if I'm missing something...

**Comment by sparrowDom** [comment]
Yup it was, thanks for cleanup!
