### ISSUE TITLE
OETH - Oracle Router

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#1275]
This can be a separate contract from our current contract.

We'll need oracles for our core assets. We don't need prices in here for reward tokens, since we'll use the old price oracle for the token harvesting.

We'll set the price of wETH to 1.

I'm hoping that we can get an fraxETH oracle from chainlink before launch.

Support:

- stETH
- Coinbase Wrapped Staked ETH
- Rocket Pool
- Frax Ether 1:1 until we have an oracle
- WETH 1:1

**Comment by DanielVF** [comment]
@sparrowDom

I'm thinking we should move the oracle range checks out of the oracle router and into the vault. Primarily this is because the range checks as they are won't work for something like rETH that is constantly increasing in value. By moving this to the vaultCore, we check the oracle prices AFTER the conversion to units. The vault has the information needed, but the oracle does not.

Secondly, this gets rid of the super gas inefficient calls out to getSymbol on everything the oracle touches.

**Comment by sparrowDom** [comment]
yup agreed good point

**Comment by sparrowDom** [comment]
Deployed here: 0x60fF8354e9C0E78e032B7daeA8da2c3265287dBd
