### ISSUE TITLE
OETH - ETH Zapper

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#1276]
Tiny standalone contract.

Has a payable deposit method that takes ETH in, converts to WETH, deposits WETH to mint OETH, and returns OETH to user.

Allows the user to pass a minimum OETH amount, that is passed to the OUTH mint function.

# Phases

- [x] Design
- [x] Code
- [x] Code Review
- [x] Deploy
- [x] Deploy Review
- [x] Live

**Comment by rafaelugolini** [comment]
@DanielVF is this done?
