### ISSUE TITLE
Support MetaMask Mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#129]
Since [it appears that MetaMask is moving forward with their DApp browser](https://www.bloomberg.com/news/articles/2020-09-02/metamask-s-blockchain-mobile-app-opens-doors-for-next-level-web), let's make sure that our DApp works with it. Hopefully, the environment is similar to the desktop browser extension.

**Comment by sparrowDom** [comment]
Done via: https://github.com/OriginProtocol/origin-dollar/pull/297
