### ISSUE TITLE
OETH risk monitoring

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1305]
Here are the metrics that we should track to monitor OETH health:

- [x] [ETH/frxETH Curve pool](https://curve.fi/#/ethereum/pools/frxeth/deposit) balances
- [x] [rETH/ETH Curve pool](https://curve.fi/#/ethereum/pools/factory-crypto-210/deposit) balances
- [x] [ETH/stETH Curve pool](https://curve.fi/#/ethereum/pools/steth/deposit) balances
- [x] [WETH/stETH Concentrated Curve pool](https://curve.fi/#/ethereum/pools/factory-v2-117/deposit) balances
- [x] Total supply
- [x] Vault holdings (balance in vault, even if the balance is generating yield)
- [x] Strategy holdings
- [x] APR and APY
- [x] OETH/ETH Curve pool balances
- [x] OETH/ETH Curve pool percentages

**Comment by rafaelugolini** [comment]
@micahalcorn can we agree that this task is complete once we add tracking on?

- [ ] frxETH
- [ ] rETH
- [ ] stETH
