### ISSUE TITLE
OETH dapp

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1328]
Implement a newly-styled dapp for OETH and apply the same changes to OUSD (shared code). The OETH version should _not_ be deployed to app.oeth.com but should be accessible at an obscure Heroku URL for testing.

---
**Prioritization**

- Mint and redeem with the following:
  - WETH, stETH, rETH, frxETH
- Mint with the following:
  - ETH, sfrxETH
- Wrap and unwrap (WOETH)
- Swap with Curve
- Balance
- Pending yield
- APY
- Account history
- Lifetime earnings
- Swap with Uniswap

**Comment by rafaelugolini** [comment]
@matt-bullock do you have a link to the design files?

**Comment by matt-bullock** [comment]
Designs are here https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/OETH-App?node-id=54%3A11231&t=JvT5zrliuG1B44Ui-1

**Comment by micahalcorn** [comment]
Closing this in favor of separate issues 🚪
