### ISSUE TITLE
Review LSD contracts

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1329]
Similar to the prior [LUSD analysis](https://docs.google.com/document/d/1sc9NFfn-ACetRZOPfE6DdRi78hf6zokPkzIU1ZQ2jz8/edit), review the smart contracts for each LSD that OETH will support as minting collateral and confirm that there aren't any red flags.

- [x] rETH
- [x] frxETH

Moved stETH to https://github.com/OriginProtocol/origin-dollar/issues/1345

**Comment by rafaelugolini** [comment]
Links for the work
rETH: https://docs.google.com/document/d/1HIcJ0ecpeM45caowBHVLOfM7U0zBrcg3w4589QHgvGM/edit
frxETH: https://docs.google.com/document/d/1voXJs2PlLiSUGhOB4sF8i62l1d1AvN7gmJ8diQyXZy4/edit
