### ISSUE TITLE
Integrate OETH with DefiLlama

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1347]

**Comment by shahthepro** [comment]
This is done and has been live since the last weekend

**Comment by shahthepro** [comment]
Reopening this since DefiLlama seem to have changed the category from "Liquid Staking" to "Yield", this has removed OETH from their LSD page. Here's the commit that [made the change](https://github.com/DefiLlama/defillama-server/commit/e5e49185afc46273cf7744c78814c850f4eb36ac)

**Comment by micahalcorn** [comment]
Closing because this is out of our hands at the moment 🦙
