### ISSUE TITLE
Audit contract ownership

### ISSUE THREAD

**Issue by rafaelugolini** [OriginProtocol/origin-dollar#1355]
We need to audit all the contract's ownership for the right mult-sig

- [x] Vault core / admin
- [x] Oracle router
- [x] Zapper
- [x] 4626 strategy
- [x] Wrapped OETH
- [x] Keeper
- [x] Curve AMO
- [x] Harvester
- [x] Dripper

**Comment by DanielVF** [comment]
All currently deployed contracts are correctly owned. We'll need to check the new AMO deploy in the future.

**Comment by micahalcorn** [comment]
> All currently deployed contracts are correctly owned. We'll need to check the new AMO deploy in the future.

I made some boxes and checked some of them.

**Comment by DanielVF** [comment]
All good
