### ISSUE TITLE
Add relevant tooltips for unsupported contracts

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1378]
This text in this tooltip should be contextual based on which situaation it is explaining.

<img width="766" alt="Screenshot 2023-05-01 at 12 49 57 PM" src="https://user-images.githubusercontent.com/273937/235519476-a5ed09d4-8110-4d14-a3b8-7bc04008a9ce.png">

**Suggestion**
> The zapper contract is only used to convert ETH and sfrxETH into WETH or frxETH before sending them to the vault.

<hr>

<img width="805" alt="Screenshot 2023-05-01 at 12 50 18 PM" src="https://user-images.githubusercontent.com/273937/235519482-5b59f451-5476-4d44-98bf-408d4e3dfb42.png">

**Suggestion**
> The vault contract requires ETH and sfrxETH to be converted to WETH or frxETH prior to minting.

**Comment by smitch88** [comment]
Context is given inline in latest staging deploy
