### ISSUE TITLE
Reskinned OETH dapp

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1386]
Apply the [new dapp styling](https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/OETH-App?node-id=54%3A11231&t=JvT5zrliuG1B44Ui-1) but [relocate the transaction activity](https://github.com/OriginProtocol/origin-dollar/issues/1377) last.

**Comment by smitch88** [comment]
Closing this overarching issue as its tracked in various other issues.
