### ISSUE TITLE
Error on Curve swap route

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1392]
If I choose anything other than ETH, I see an error on the Curve option. This makes sense because our pool does not involve most of these other tokens. Instead of "Error" though, we should show "Unsupported" with a tooltip explaining why. Also, I was under the impression that WETH was supported by the pool but our dapp indicatres otherwise.

<img width="582" alt="Screenshot 2023-05-02 at 9 37 41 PM" src="https://user-images.githubusercontent.com/273937/235833723-fb2ea2d5-3a9a-4f4e-b204-60a0a285f27b.png">

**Comment by micahalcorn** [comment]
Unsupported helper text:

> The OETH Curve pool only supports swapping with ETH.

**Comment by smitch88** [comment]
Fixed and in staging
