### ISSUE TITLE
Graceful handling of disabled minting

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1397]
For security reasons, we disable minting for a given collateral type that is trading below peg. Currently, this results in a vague "Error", misleading button label, and red stack trace in the console. Let's improve this user experience so that it's clear a security feature is doing its job of protecting OETH holders rather than something going wrong.

<img width="959" alt="Screenshot 2023-05-03 at 2 50 41 PM" src="https://user-images.githubusercontent.com/273937/236061553-7a50ae69-951e-4f1e-a909-a2cab30441f7.png">

**Comment by matt-bullock** [comment]
https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=377%3A17124&t=vTS94yL8VB0h2LjF-1

<img width="740" alt="image" src="https://user-images.githubusercontent.com/39496225/236273696-37fc07a5-533f-47c9-bc41-50d34cfcc30e.png">

**Comment by smitch88** [comment]
Linked to [1402](https://github.com/OriginProtocol/origin-dollar/issues/1402)
