### ISSUE TITLE
Enable only one button at a time

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1400]
I've ended up in a state where the dapp thinks I still need to approve an allowance but it also offers me a swap button. Onle one button should be enabled, presumably the approve in my case.

<img width="962" alt="Screenshot 2023-05-03 at 4 12 20 PM" src="https://user-images.githubusercontent.com/273937/236071228-6a279743-8ee1-480c-b155-d8960fafde49.png">

**Comment by smitch88** [comment]
Should be fixed in staging
