### ISSUE TITLE
Improve the wrap experience

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1403]
When landing on /wrap, the input field (on top) should default to OETH. Currently, it defaults to wOETH, which is 0 for basically every first-time visitor. Also, the styling is still inheriting parts of the original OUSD dapp and both sides of the form show the wOETH balance instead of one of them being OETH.

<img width="902" alt="Screenshot 2023-05-03 at 8 40 31 PM" src="https://user-images.githubusercontent.com/273937/236108036-a1c0cdd8-4d0b-444b-83d8-ac162544d121.png">

**Comment by rafaelugolini** [comment]
@HrikB check with @smitch88 before working on this, apparently, he worked on this already.

**Comment by smitch88** [comment]
Should be deployed already as well

**Comment by rafaelugolini** [comment]
@micahalcorn can you confirm?

**Comment by micahalcorn** [comment]
Much improved, thx 👍
