### ISSUE TITLE
Incorrect numbers showing for yield amounts in history

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1404]
Yield amounts way higher than they should be:

![image](https://user-images.githubusercontent.com/39496225/236236414-95c52390-7790-428c-b14c-16bae5d0d18e.png)

**Comment by HrikB** [comment]
Found the cause of the issue:
![image](https://github.com/OriginProtocol/origin-dollar/assets/23041116/12e90116-e5ec-4c8f-add2-2da6bda60e93)
