### ISSUE TITLE
Detect Safe wallet contracts outside of connected apps

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1405]
Safe contracts are detected when a user connects via a connected app in their frontend. But if she uses WalletConnect and their mobile app, no banner is displayed indicating that opting-in is necessary to receive yield.

https://www.loom.com/share/293b59d5f321478f8db5cccd5964a5d0

<img width="830" alt="Screenshot 2023-05-04 at 1 55 26 PM" src="https://user-images.githubusercontent.com/273937/236327078-f27958dc-3c37-4ac2-a907-cbdfa030be68.png">

**Comment by toniocodo** [comment]
this feature has been migrated to new `origin-defi` repo where the Safe wallet is properly detected
