### ISSUE TITLE
Scientific notation in token balances

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1408]
Let's not do this. Note that it also happens in the big form output, not just the dropdown/modal.

<img width="591" alt="Screenshot 2023-05-04 at 2 18 51 PM" src="https://user-images.githubusercontent.com/273937/236332436-a92898f6-b96e-4f56-b223-37794efb5ff4.png">

**Comment by smitch88** [comment]
Fix is deployed into staging
