### ISSUE TITLE
USD balances empty

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1409]
Throughout the OETH dapp, we show $0 on balances. These should be wired up with the ETH/USD exchange rate or we can remove them and handle it later. Currently, users focus on this and don't see the unit amounts.

**Comment by smitch88** [comment]
There is an error from calling into chainlink,

```
 Error happened fetching eth usd chainlink data: TypeError: Cannot read properties of undefined (reading 'latestRoundData')
 ```
 
 This is also why it looks like the gas estimate isnt in dollars, its bringing back eth price as a not real num
