### ISSUE TITLE
Slightly incorrect balance

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1411]
This user received 0.0001 OETH according to Etherscan but the balance is showing 0.000099 in our dapp.

https://etherscan.io/token/0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3?a=0xf8e695089a24e98af2abc3b96788fa01ef9dc852

![IMG_3502](https://user-images.githubusercontent.com/273937/236494385-0cdcd8ad-8e55-4d00-b3c7-1b2d2041e5cb.PNG)

**Comment by franckc** [comment]
This is a known rounding issue in the contract.
Identified by @DanielVF a couple of weeks ago

<img width="640" alt="oeth_rounding" src="https://user-images.githubusercontent.com/945910/236522528-e7e2d25e-2c28-488a-98d8-95fab6fbef7b.png">

**Comment by micahalcorn** [comment]
Closing in favor of https://github.com/OriginProtocol/origin-dollar/issues/1418 🚪
