### ISSUE TITLE
Add pending states to the activity menu button

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1412]
Pending state:

Can you use a pending animation similar to the design (the arrows spin) there is probably something you can grab from somewhere rather than making it yourself

https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=216%3A9958&t=AkjZktXnbgaTqRqs-1

<img width="248" alt="image" src="https://user-images.githubusercontent.com/39496225/236497720-749d7ff8-b58f-4dec-9d9a-8de773d147fa.png">

Confirmed state:

This should appear for around 5 seconds (whatever feels good) before disappearing. Feel free to use a tick animation that draws itself in.

https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=216%3A11503&t=AkjZktXnbgaTqRqs-1
<img width="179" alt="image" src="https://user-images.githubusercontent.com/39496225/236498163-653a4e57-5311-4bf8-9979-c4de7753667d.png">

Failed:

This should appear for the same amount of time as confirmed/success state.

https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=54%3A11326&t=AkjZktXnbgaTqRqs-1

<img width="175" alt="image" src="https://user-images.githubusercontent.com/39496225/236498424-c1e013df-665d-4d58-b901-904d6578d377.png">

**Comment by smitch88** [comment]
This should actually be working this way. The transaction activity icon should spin when a new transaction is taking place. The one thing that needs to be done is reverting it back after X seconds have passed

**Comment by smitch88** [comment]
Fixed and deploying to staging
