### ISSUE TITLE
make mobile responsive 

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1420]
Mobile designs are here https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=216%3A14998&t=AkjZktXnbgaTqRqs-1

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/39496225/236510197-870f29ef-038a-467a-bc37-521b9a9afa2b.png">

**Comment by smitch88** [comment]
I think the last remaining items here would be the dropdowns and modals
