### ISSUE TITLE
history page styling 

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1421]
https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=54%3A11422&t=AkjZktXnbgaTqRqs-1

<img width="1928" alt="image" src="https://user-images.githubusercontent.com/39496225/236510619-46cccd54-a746-419e-8455-35e289a7391a.png">

**Comment by matt-bullock** [comment]
- [ ] Disable export button when not connected (grey out text - see design https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?type=design&node-id=54%3A11448&t=LZLkRdPYpuQNjtjV-1)
- [ ] Remove hover states from filter buttons as it's confusing the way they keep flashing on and off. You can try only removing the hover from the active state to see if that helps.
- [ ] APY column is missing
- [ ] Reduce padding on right side
- [ ] Add more spacing between OETH balance and etherscan arrow - see design.
- [ ] Can you add a larger hit spot around the etherscan link arrow button

**Comment by micahalcorn** [comment]
No APY for now, sry ⏩
