### ISSUE TITLE
Nav styling

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1422]
Desktop:

 https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=385%3A20165&t=AkjZktXnbgaTqRqs-1

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/39496225/236511150-49a29e14-fb56-43bf-99f7-37502af5c7e6.png">

Mobile:

https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=216%3A14998&t=AkjZktXnbgaTqRqs-1

<img width="940" alt="image" src="https://user-images.githubusercontent.com/39496225/236511076-6604e417-19bf-4f4e-8487-d43bec03677a.png">

**Comment by micahalcorn** [comment]
Including this screenshot where there are two IPFS buttons wrapping :v:

<img width="722" alt="Screenshot 2023-05-06 at 2 42 01 PM" src="https://user-images.githubusercontent.com/273937/236647696-3d663ef2-fd2d-4cef-aeff-0f24360e76ec.png">
