### ISSUE TITLE
Swap route styling

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1423]
https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?node-id=54%3A11254&t=AkjZktXnbgaTqRqs-1

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/39496225/236511700-b151d278-cdfe-4ecb-8df8-6450a58cf505.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/39496225/236511885-aad7d29b-caa6-4272-aa1e-8e25bfd5c34e.png">

**Comment by smitch88** [comment]
Should be good and deployed into staging.
