### ISSUE TITLE
Redundant and missing history transactions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1427]
@franckc swapped ETH for OETH on Curve and [the transaction](https://etherscan.io/tx/0x4b1fe775f01ab5189ec82146af940fd3ed113cc19b72ff920a37812950be0639) is missing. Meanwhile, the same [redeem transaction](https://etherscan.io/tx/0xdf1d7b7d1548930d78afe82ba17dca1f9afb0bba4bc599ab2e839ac069ddad45) is showing up repeatedly (as a swap).

<img width="926" alt="Screenshot 2023-05-05 at 2 32 12 PM" src="https://user-images.githubusercontent.com/273937/236572915-10d443c4-cc81-4f2f-bb4b-9edd18eeb1df.png">

**Comment by matt-bullock** [comment]
@micahalcorn are you able to test this?

**Comment by micahalcorn** [comment]
> @micahalcorn are you able to test this?

Yep, I've got this one covered, thanks.
