### ISSUE TITLE
Support multi-step swaps with Curve

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1429]
When a user has ETH and wants OETH, there are two options: minting with the zapper or swapping through the Curve ETH/OETH pool. However, if she has stETH or another LSD and wants OETH, minting is currently the only option. Due to the frequency of stETH (and others) being off-peg, there's a high likelihood that users won't be able to acquire OETH from our dapp. Let's add support for additional Curve swaps beyond just ETH/OETH.

In order of priority...
- [ ] stETH
- [ ] WETH
- [ ] rETH
- [ ] frxETH

**Comment by rafaelugolini** [comment]
@smitch88 isn't this merged?

**Comment by smitch88** [comment]
Yup, closing
