### ISSUE TITLE
Wire up lifetime earnings and pending yield

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1439]
It seems that the lifetime earnings and pending yield numbers are either not working or incorrect. Here's an example of an account that has earned 0.041834 and should have a non-zero pending yield but is showing otherwise.

https://etherscan.io/token/0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3?a=0x57b0dd7967955c92b6e34a038b47fee63e1efd1a

<img width="681" alt="Screenshot 2023-05-09 at 8 16 02 AM" src="https://github.com/OriginProtocol/origin-dollar/assets/273937/74509ab5-f965-481c-a513-9620bfd757ad">

**Comment by shahthepro** [comment]
This was a bug on the backend API. Have fixed it now
