### ISSUE TITLE
 Analyse if 1% to the harvester is enough to cover current gas costs when harvesting

### ISSUE THREAD

**Issue by naddison36** [OriginProtocol/origin-dollar#1448]
The last harvest was in tx [0x8c94dbcda1111f7fa11818f2ae5c8681f5459066af03d1523d9dc573dbd98a4a](https://etherscan.io/tx/0x8c94dbcda1111f7fa11818f2ae5c8681f5459066af03d1523d9dc573dbd98a4a) on 14 April 2023
It cost 0.015 ETH ($26.79) with a gas price of 25 Gwei.
The harvested included swapping 126 CVX for 745 USDT and 6,006 CRV and 6,311 USDT.

![ousd-harvest-value](https://github.com/OriginProtocol/origin-dollar/assets/6491112/94dbbbca-15ca-4534-a649-00a004d3f3d9)

Simulating `harvestAndSwap` with the Convex USD Strategy 0x89Eb88fEdc50FC77ae8a18aAD1cA0ac27f777a90, the tx failed with `UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT`
The simulation harvests 254 CVX and 13,392 CRV which is worth 1,122 USD and 10,713 USD respectively

The failure is when swapping 13,392.295953250305476319 CRV for a min of 10,365.935533 USDT. That's a min exchange rate of 0.774 CRV/USDT. The current market rate is 0.79555 CRV/USDT.

There is not enough liquidity on the SushiSwap for the CRV > ETH > USDT path. For 13,392 CRV, it is only returning 9,717 USDT which is a rate of 0.725652 CRV/USDT. This is well under the 0.774 min and is nearly 9% below market rates

The best execution at the moment on 1Inch is using PMM3 returning 10,631 USDT at a rate of 0.792849 CRV/USDT.

**Comment by naddison36** [comment]
Analysis of different sized swaps on different DEXs

CRV | 1Inch | Uniswap V2 |   | Uniswap V3 |   | SushiSwap |  
-- | -- | -- | -- | -- | -- | -- | --
1,000 | 800.00 | 788 | -1.50% | 801 | 0.13% | 789 | -1.38%
2,000 | 1,602.00 | 1,564 | -2.37% | 1,601 | -0.06% | 1,573 | -1.81%
5,000 | 4,005.00 | 3,828 | -4.42% | 4,001 | -0.10% | 3,890 | -2.87%
10,000 | 8,006.00 | 7,393 | -7.66% | 7,993 | -0.16% | 7,636 | -4.62%
20,000 | 16,000.00 | 13,834 | -13.54% | 15,951 | -0.31% | 14,727 | -7.96%
100,000 | 79,938.00 | 45,665 | -42.87% | 77,362 | -3.22% | 57,267 | -28.36%

The Uniswap V3 path
CRV/WETH 0.3% pool
WETH/USDT 0.05% pool

**Comment by naddison36** [comment]
The dripper steams harvested rewards over a 7 day period.
The allowed slippage for CRV is 3%

**Comment by naddison36** [comment]
There is currently 26,476 CRV that can be harvested by the OUSD Harvester for the AMO strategy.
From fork testing, we have to set the OUSD Harvester liquidation limit to 4000 for CRV. There is not enough SushiSwap liquidity to handle 5000 CRV.

4000 CRV is currently worth 3,199 USDT when swapped by SushiSwap which is just under 3% slippage.

**Comment by naddison36** [comment]
The medium term solution is to change the OUSD Harvester to use Uniswap V3 as there is a lot more liquidity to handle larger CRV swaps.

Longer term a DEX aggregator could be used to get best execution as Uniswap does not always have the best prices.

**Comment by DanielVF** [comment]
So 3199 @ 1% fee gives $32 worth of fees to pay for gas. That will work at 26 GWEI gas. I'm thinking we should maybe bump the percentage up to 1.5% then.

**Comment by naddison36** [comment]
The 3,199 was just from liquidating the CRV. But the CVX is usually less than 20% of the CRV amount

Here's what the harvester has been returning to the caller recently
| Date           | USDT    |
| -------------- | ------- |
| 14/2/2023 1:17 | 19.30   |
| 12/2/2023 18:41| 20.36   |
| 11/2/2023 10:03| 20.19   |
| 10/2/2023 0:47 | 28.68   |
| 8/2/2023 2:19  | 35.95   |
| 5/2/2023 22:24 | 25.20   |
| 30/1/2023 3:11 | 20.12   |
| 27/1/2023 7:07 | 19.19   |
| 26/1/2023 4:46 | 19.93   |
| 25/1/2023 2:56 | 19.09   |

This has been costing around 600,000 gas. 
| Gwei | Ether  | USD     |
| ---- | ------ | ------- |
| 20   | 0.0120 | $21.60  |
| 40   | 0.0240 | $43.20  |
| 50   | 0.0300 | $54.00  |
| 60   | 0.0360 | $64.80  |
| 80   | 0.0480 | $86.40  |
| 100  | 0.0600 | $108.00 |
| 150  | 0.0900 | $162.00 |
| 200  | 0.1200 | $216.00 |

So we need to double the percentage to 2% for the caller to recover costs when gas prices are 40 Gwei.

**Comment by naddison36** [comment]
the config changes and fork tests are in PR https://github.com/OriginProtocol/origin-dollar/pull/1492

**Comment by naddison36** [comment]
The analysis has been done so closing. The config change can be tracked in https://github.com/OriginProtocol/origin-dollar/pull/1492
