### ISSUE TITLE
Replace EKG with activity animation

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1452]
When a transaction is submitted, the dapp auto-scrolls to the top of the page where the nav is visible. There is an icon in the top right that the user should be focused on, but there is nothing drawing the eyes to it. @DanielVF has commented that the current icon resembles a health monitor rather than blockchain activity. Let's put a spinner there or something.

**Comment by matt-bullock** [comment]
The nav should be sticky so it remains stuck to the top of the browser and always visible.

The pending animation should be the spinner icon rotating.

I'll come up with something better for the activity icon. Something to do with transactions rather than activity.

**Comment by smitch88** [comment]
I can make this sticky but was having a bit of trouble with how the layout is structured currently

**Comment by smitch88** [comment]
@matt-bullock Was there a new icon we wanted to use? In staging the header should be sticky and the pending should rotate now.
