### ISSUE TITLE
Empty state for swap routes

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1461]
Can we show the O amount and some dashes for this state. There's no need to show the alert message here if the users hasn't entered anything

https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?type=design&node-id=54%3A11232&t=8ieYLdJXWfcj5da9-1

<img width="753" alt="image" src="https://github.com/OriginProtocol/origin-dollar/assets/39496225/1f73d5b0-eb7a-4f0d-9032-376e60140c76">

**Comment by smitch88** [comment]
Deployed via https://github.com/OriginProtocol/origin-dollar/pull/1489
