### ISSUE TITLE
Add explainer section to wrap page

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/origin-dollar#1472]
https://www.figma.com/file/5JBhCbve90PJPO8c0kd0G3/Swap-App?type=design&node-id=223%3A12248&t=M7JSrE4uxSkYqbhc-1

<img width="774" alt="image" src="https://github.com/OriginProtocol/origin-dollar/assets/39496225/02f4dcd4-5da3-49ab-981c-0ea920a679b8">

Learn more link: https://docs.oeth.com/core-concepts/wrapped-ousd

**Comment by smitch88** [comment]
Deployed into prod
