### ISSUE TITLE
Skeleton DApp Experience

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#148]
The DApp seems to take some time to find the user's balances. I'm not sure if this is because it hasn't connected to the account yet or if there is a delay between accessing the account and determining the balances. If we can find some way to distinguish empty balances from balances that have not yet loaded, we should first render a [skeleton](https://www.lukew.com/ff/entry.asp?1797) DApp with placeholder elements to indicate that the data is being loaded. Currently, we get a flickering between the empty state and the non-empty state when the data is loading.

**Comment by sparrowDom** [comment]
Closing since this issue is a duplicate (more a subset) of this issue: https://github.com/OriginProtocol/origin-dollar/issues/25
