### ISSUE TITLE
Enable collateral conversions

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1518]
In order to maximize yield and minimize risk, the OETH strategists (and the community at large) need to be able to adjust the makeup of the vault collateral periodically. For example, during one of last year's USDT scares, we voted to swap all of our USDT for DAI temporarily. Another example from OUSD is when voters elect to increase our Morpho Aave USDT position beyond the amount that we're currently holding. OUSD has long since been able to swap collateral because it includes a Curve 3pool strategy. The strategists are able to conver DAI to USDC, for example, by depositing DAI into the Curve 3pool strategy and then withdrawing USDC from the same pool. Sometimes there are costs or slippage associated with this but we at least have the capability and can do a cost-benefit analysis before taking the action.

OETH doesn't have the same capabilities. There is no existing strategy in place to be able to use as a swapping mechanism. This is important for OETH because of the diversity of collateral types and the increased likelihood of volatility. While OUSD has a default, yield-generating strategy for each of its supported collateral types (DAI, USDC, USDT), it's never stuck holding stagnant USD. OETH, however, is currently stuck holding [w]ETH that is not earning yield. We don't have any basic single-sided strategies to earn yield with ETH. We also may need to diverify LSD holdings if everyone mints with stETH and we want greater decentralization or higher yield from rETH and frxETH.

Ultimately, there are two near-term objectives:

1. Make it possible for the collateral to be converted from one supported asset type to another
2. Limit this capabilty to the strategists rather than exposing it to decentralized actors or being automated (for now)

Implementation tasks
- [x] #1539
- [x] #1540

**Comment by naddison36** [comment]
I'll do the analysis and solution design in Notion https://www.notion.so/Analysis-of-OETH-Collateral-Swapper-1d9d8b2d2b104968ad81c734d161fe58

**Comment by naddison36** [comment]
The solution design decisions have been reviewed and agreed with the DeFi team.
https://www.notion.so/813478cd16c84f3bb869a5e6ff0a2eda

Work not progresses to implementation.

**Comment by naddison36** [comment]
This is now being deployed with PR https://github.com/OriginProtocol/origin-dollar/pull/1655
