### ISSUE TITLE
Decimal format deploy

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#1534]
As part of OpenZeppelin audit we have changed Vault asset decimal type -> [PR](https://github.com/OriginProtocol/origin-dollar/pull/1516/files). When we upgrade the VaultStorage we need to create a governance action for OUSD & OETH that will call `cacheDecimals` on all the Vault's supported assets -> in order to not break the storage slot change

**Comment by naddison36** [comment]
This issue will be fixed for the OETH Vault as part of the OETH collateral swaps change. PR https://github.com/OriginProtocol/origin-dollar/pull/1559

**Comment by naddison36** [comment]
This has been done with deploy 066 https://github.com/OriginProtocol/origin-dollar/pull/1655
