### ISSUE TITLE
off-chain component that interacts with the 1Inch API and the Vault

### ISSUE THREAD

**Issue by naddison36** [OriginProtocol/origin-dollar#1540]
# Scope

This task is to implement the off-chain collateral asset swap functionality for the OETH Vault.

The on-chain contract component are being implemented in https://github.com/OriginProtocol/origin-dollar/issues/1539

## Out of scope

Implementing collateral swaps on the OUSD Vault can be done separately at a later point.

## Requirements

The relevant assumptions from the [design decisions](https://www.notion.so/Analysis-of-OETH-Collateral-Swapper-1d9d8b2d2b104968ad81c734d161fe58) are:

- The strategist mutlisig will execute the collateral swaps.
- 1Inch Pathfinder V5 will be used as the swap provider.
- There will be two layers of MEV protection
  - The strategist will pass in a min amount to be returned from the swap.
  - The vault will check that the return amount is not outside the Oracle deviation limits of the from and to asset exchange rates.
- The strategist will decide if partial fills are allowed or not for each swap. There will be no on-chain enforcement of this.

## Process

This is the happy path for the off-chain command line interface (cli) component.

- A signer of the strategist multisig inputs the required swap details including the from asset, from asset amount, to asset and slippage amount as a percentage. eg 0.1 is 0.1% which is 10 basis points.
- An optional parameter will if partial fills will be allowed or not. This is a parameter of the 1Inch swap API call. The default will be partial fills will not be allowed
- The off-chain component will get the Oracle exchange rates from the chain.
- The off-chain component will warn if the exchange rates are stale??
- The off-chain component uses the Oracle exchange rates and the entered slippage to calculate a minimum to asset amount.
- The off-chain component calls the 1Inch Pathfinder API /v5.0/1/swap
- The off-chain component outputs the details of the swap including final to asset amount and swap routes
- The off-chain component gets the `tx.data` from the response
- The off-chain component builds a tx that calls the `collateralSwap` function is called on the Vault with the from asset, from asset amount, to asset and 1Inch router data.
- The off-chain component outputs the `collateralSwap` tx details so they can be copied into the strategist multisig's tx builder.

## Testing Strategy

The collateral swap will be fork tested using the production 1Inch API and a local mainnet fork.

## Resources

- [1Inch V5 Pathfinder introduction](https://docs.1inch.io/docs/aggregation-protocol/introduction)
- [1Inch V5 Pathfinder Swapper docs](https://docs.1inch.io/docs/aggregation-protocol/api/swagger)
- [1Inch V5 Pathfinder contract code](https://vscode.blockscan.com/ethereum/0x1111111254EEB25477B68fb85Ed929f73A960582)
- [1Inch V5 Pathfinder swap parameters](https://docs.1inch.io/docs/aggregation-protocol/api/swap-params)
- [DefiLlama Swap Aggregator](https://swap.defillama.com/?chain=ethereum)

**Comment by naddison36** [comment]
The off-chain component should be written in Python using Brownie. See the following design decision for more details
https://www.notion.so/What-will-the-off-chain-component-that-calls-the-1Inch-API-and-then-the-swap-function-on-the-vault-b-e171201a1c114344a0e22cfb6574a7d0

**Comment by sparrowDom** [comment]
@naddison36 thank you for this wonderful project spec!

**Comment by naddison36** [comment]
@sparrowDom I've changed the `swapCollateral` interface slightly. Instead of passing the full `tx.data` to the `data` param of the swap, I've changed it to only include the executer contract address and data. That way we aren't duplicating the `fromAsset`, `toAsset`, `fromAssetAmount` and `minToAssetAmount` param data.

So the `tx.data` from the 1Inch swap API needs to be decoded and then re-encoded. Here's JS util that does this https://github.com/OriginProtocol/origin-dollar/blob/e2fa7edbcd12aa79bde8434c3d0f7851b493126e/contracts/utils/1Inch.js#L8

Here's where the decoding is done in the Swapper contract https://github.com/OriginProtocol/origin-dollar/blob/e2fa7edbcd12aa79bde8434c3d0f7851b493126e/contracts/contracts/swapper/Swapper1InchV5.sol#L51

**Comment by naddison36** [comment]
apologies @sparrowDom, but there's another change to the spec!

The encoding of the data field passed to the `swapCollateral` function will depend on the function selector returned from the 1Inch swap API.

The `data`
 * The first 4 bytes is the function selector to call on 1Inch's router. That is, the first 4 bytes of the tx.data in the API response.
 * If calling the 1Inch `swap` function, the next 20 bytes is the executer's address and then the executer data.
 * If calling the 1Inch `unoswap` or `uniswapV3SwapTo` functions, an array of Uniswap pools are encoded.

Here's the JS implementation of this
https://github.com/OriginProtocol/origin-dollar/blob/e1189fc6c0c0f6366282b35d5878b234b1c6e32c/contracts/utils/1Inch.js#L20

The relevant code in the `Swapper1InchV5` contract is https://github.com/OriginProtocol/origin-dollar/blob/e1189fc6c0c0f6366282b35d5878b234b1c6e32c/contracts/contracts/swapper/Swapper1InchV5.sol#L35
