### ISSUE TITLE
Wrong calculation of sfrxETH price

### ISSUE THREAD

**Issue by rafaelugolini** [OriginProtocol/origin-dollar#1545]
sfrxETH shows the same price in USD from frxETH

![Image](https://github.com/OriginProtocol/origin-dollar/assets/2651141/8a20f8de-b1f3-461b-af44-57e494710c4d)
![Image](https://github.com/OriginProtocol/origin-dollar/assets/2651141/866ebb85-ae9c-4189-a852-68edc94c3edf)

**Comment by smitch88** [comment]
@rafaelugolini Just for clarity, the bug here is the USD price conversion of sfrxETH. I would imagine this is an issue across all the LSTs, right now this is just taking eth price and multiplying which would be incorrect.

**Comment by smitch88** [comment]
@micahalcorn Take a look. Basically the USD value is going to be inaccurate for any LST

**Comment by micahalcorn** [comment]
Here's another report that may be the same issue:

![IMG_5845](https://github.com/OriginProtocol/origin-dollar/assets/273937/c228fb3c-1e34-4619-89db-ae5fc635fa93)
