### ISSUE TITLE
Repair Curve pool Grafana chart(s)

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#1554]
<img width="696" alt="Screenshot 2023-05-28 at 1 33 50 PM" src="https://github.com/OriginProtocol/origin-dollar/assets/273937/23e4c5d8-cf5b-4b48-b600-d493b1eb1c53">

**Comment by HrikB** [comment]
OETH and rETH were reversed. I changed the labels in grafana and added a comment in the prometheus repo. This way we don't lose the data we already have.
