### ISSUE TITLE
Add WETH asset support to the FRAX ETH strategy

### ISSUE THREAD

**Issue by naddison36** [OriginProtocol/origin-dollar#1555]
Modify the FRAX Strategy so it can support the WETH asset. This will withdraw ETH from the WETH, deposits the ETH into frxETH and stakes the frxETH for sfrxETH.

![oethValueFlows-sfrxETH-for-weth](https://github.com/OriginProtocol/origin-dollar/assets/6491112/bf85b1ac-092b-4991-8bbb-a9916c7bc4d3)

The frxETH contract
https://etherscan.io/address/0x3ff8654d633d4ea0fae24c52aec73b4a20d0d0e5#code

**Comment by DanielVF** [comment]
I think this should replace our current strategy, and handle both WETH and FraxETH as supported assets. This will be more gas efficient, and will be less code and UI floating around. The checkBalance will return the correct frax amount for frax, and 0 for WETH.

**Comment by naddison36** [comment]
The design decisions are being logged in Notion https://www.notion.so/Support-WETH-in-FraxETH-Strategy-ee565494ff454f6baed094f19cbcc59b?pvs=4#af0debc1bb5b4ac88d748d331733d2ca

**Comment by naddison36** [comment]
This has been completed
