### ISSUE TITLE
Conditional Connector Image

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#157]
[We currently show a MetaMask icon](https://github.com/oplabs/origin-dollar/blob/7464d1e5cc92e8581e5c47f312b07f47aac5dbfb/dapp/src/components/_AccountStatusContent.js#L50-L54) anytime a wallet prompt is pending. We don't need a separate image for every vendor, but we shouldn't show the MetaMask fox when the connector is Ledger, WalletConnect, etc. We'll come up with a generic, non-MetaMask version to swap in.

**Comment by sparrowDom** [comment]
This has been done already

**Comment by micahalcorn** [comment]
![B95A9103-5CCD-49CB-B3BF-8404FAADC261](https://user-images.githubusercontent.com/273937/94831703-e32ed200-03c1-11eb-87d1-c0d36442f93f.png)

**Comment by sparrowDom** [comment]
@micahalcorn aha I see, we are currently differentiating (and showing different connector images) for Metamask, Ledger, MyEtherWallet and WalletConnect. 

For others we default to Metamask image. Which [of these](https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/utils/web3.js#L87-L118) you think are important enough to show as their own connector image?

Also keep in mind that engineering overhead here is minimal, not sure now much extra time it will take Aure to prepare the icons.

**Comment by sparrowDom** [comment]
Also we might have a separate `default` wallet icon, when users connect with none of the recognised ones.

**Comment by micahalcorn** [comment]
This issue is just calling for a generic image for all of the others. We need to get one from @auregimon.

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin-dollar/pull/289
