### ISSUE TITLE
Cannot partially liquidate a strategy

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#158]
In the event that Compound gets near running out liquidity, we may want to pull our funds out. Our current only way to mass pull funds from a strategy is to remove and liquidate the entire strategy as a single transaction. If Compound had 99% of our funds available, we would be unable to pull our funds back since the single huge liquidate would revert.

It would seem useful to be able to reallocate smaller percentages.

**Comment by tomlinton** [comment]
Achieved by #363
