### ISSUE TITLE
Remove `reallocate` from vault admin

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#1619]
We aren't using `reallocate()` in the vault_admin, so we should get rid of it. `depositTo()` and `withdrawFrom()` have taken it's place and do a better job.

Unused duplicate code kills. Burn it with fire.

The contract change should be simple. Work will just be around changing the tests. (We could perhaps make `reallocate` javascript test helper that does withdraws and deposits, and allows for easy conversion of old tests.)

**Comment by naddison36** [comment]
Now is the time to do this as I'm about to redeploy the OETH Vault contracts.

FYI, `028_dai_default_aave` uses `reallocate`. I'll leave it as the fork tests won't run this old deploy script anyway. And if we do fork from an old block number, `reallocate` will be available.

**Comment by naddison36** [comment]
This has been done with deploy 066 https://github.com/OriginProtocol/origin-dollar/pull/1655
