### ISSUE TITLE
WalletConnect v1.0 shutdown is happening in 2 weeks!!

### ISSUE THREAD

**Issue by sumpg41** [OriginProtocol/origin-dollar#1632]
It appears we are using WalletConnect v1.0 - **WalletConnect v1.0 shutdown is happening at 2pm UTC on June 28** - It is essential that we migrate to WalletConnect v2.0 as soon as possible to prevent any disruption when the shutdown finally comes into effect.

Migration paths from v1 to v2 can be found here: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/overview

**Comment by micahalcorn** [comment]
> @micahalcorn should this be changed to a P0? There are less than 9 days till WC v1 shutdown

I wouldn't call it a **0** but we'll get it done, thanks.
