### ISSUE TITLE
Implement Timelock

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#165]
The contracts that we initially deploy will not have the timelock enabled. Within a week of deployment, we should update the contracts to have a 48-hour timelock so that stakeholders have plenty of time to see any changes that are being made.

**Comment by franckc** [comment]
Timelock implemented and currently set to 1min. Once we feel comfortable all contracts are mature and stable we'll increase the timelock to 2 days. Closing this for now.
