### ISSUE TITLE
Pending Yield for Safe wallet using Rabby - Opt-in Button is not showing

### ISSUE THREAD

**Issue by DegenSensei** [OriginProtocol/origin-dollar#1748]
Smart contract users (generally Gnosis Safe users) are experiencing issues when they are trying to opt into yield on our app. 

We would need to audit our app and find out what is causing this issue.

**Comment by DegenSensei** [comment]
Update:

Considering the wallet that flagged this had a history of prior trouble. I created a new Gnosis Safe Wallet and went through the minting process. Essentially, when you mint OETH from a Gnosis Safe Wallet without opting into yield that's when you get the error in the pending yield.

As soon as you Opt-in to yield, this corrects itself immediately. 

The opt-in button is also available when you use Rabby as I specifically tested for that as well.

The main issue here is what causes the number discrepancy when you haven't opted into yield.

**Comment by rafaelugolini** [comment]
Not relevant anymore
