### ISSUE TITLE
Make PR to Ethereum.org

### ISSUE THREAD

**Issue by sumpg41** [OriginProtocol/origin-dollar#1756]
Unfortunately OETH was removed from the ethereum.org staking page, due to the fact that OETH is not an LST. There was also some push back on having OETH/OUSD added to their dapps page, since they don't add individual tokens. Adding Origin Protocol as a whole to the dapps page seems to be our last resort if we want to be featured on this website.

I've created an issue, but there has been no feedback or response to it: https://github.com/ethereum/ethereum-org-website/issues/10743 

I was told that if we made a PR to add the actual item, we'll get a prompt response.

**Comment by jonathansnow** [comment]
Submitted PR: https://github.com/ethereum/ethereum-org-website/pull/10953
