### ISSUE TITLE
Connect with Ledger

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#21]
Confirm that the DApp connects with [Ledger](https://www.ledger.com/) hardware wallets.

**Comment by sparrowDom** [comment]
@mikeshultz  not sure if this reply is still relevant, if you find any more places where we could add error handling for Ledger inside the dapp we can handle that similarly as it is in this PR: https://github.com/OriginProtocol/origin-dollar/pull/246 .

Login widget has got a simple catch statement that triggers an error displayed in the widget. 
The BuySellWidget passes on an onError function to any component that might want to throw a Ledger type error and those errors are all handled inside the BuySellWidget component.

**Comment by sparrowDom** [comment]
If there are no other things to address in the Ledger UX improvement PR: https://github.com/OriginProtocol/origin-dollar/pull/246 I think we can close this issue for now.  The behaviour on Ledger is currently not ideal, but I think we got it to a good enough usable state. 

Any objections? cc:// @mikeshultz @micahalcorn
