### ISSUE TITLE
Coin icon doesn't load for failing/canceled transaction

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#223]
I triggered this state by entering -2 for my amount and then canceling the transaction.

![Screen Shot 2020-09-21 at 2 00 13 PM](https://user-images.githubusercontent.com/982234/93821078-e8965a80-fc12-11ea-8031-4d5ca574efcf.png)

**Comment by micahalcorn** [comment]
This is no longer happening in my experience.
