### ISSUE TITLE
DApp does not surface an error when a redeem fails

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#226]
After my redeem transaction failed, the DApp did not show me any error and the widget on the top right actually showed me the transaction as completed, even though MetaMask and etherscan show it as reverted.

<img width="965" alt="failed_redeem" src="https://user-images.githubusercontent.com/945910/93828480-4c735000-fc20-11ea-9dc2-e18d851b2a98.png">

**Comment by sparrowDom** [comment]
This was already fixed via: https://github.com/OriginProtocol/origin-dollar/pull/268/files
