### ISSUE TITLE
Vault contract deploy fails due to max size

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#232]
We've reached the max size on the Vault contract.

A deploy to Rinkeby/Mainnet results in the following error:
```Error: max code size exceeded```

I was able to do a deploy by commenting out the initialize function, but moving forward it would be good to have a better solution. Some potential ideas: https://soliditydeveloper.com/max-contract-size

**Comment by micahalcorn** [comment]
Resolved by https://github.com/OriginProtocol/origin-dollar/pull/255 ✅
