### ISSUE TITLE
Stuck Input Field

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#233]
In Coinbase Wallet (can't reproduce elsewhere), I've somehow gotten into a state where I can't completely delete the value in my DAI field. I can edit it, say from 4 to 34 by moving the cursor to the beginning of the number. But if I try deleting it, the last remaining digit will not go away. If I disable the DAI row, the estimated purchase becomes `NaN`. If I enable a different row, everything is fine until I enable DAI again. I've killed the app and started over but the problem doesn't go away.

![IMG_1874](https://user-images.githubusercontent.com/273937/93908978-20091380-fcb4-11ea-8420-58022a60f536.PNG)

**Comment by sparrowDom** [comment]
There have been some changes in the past week as to how inputs are handled. I can no longer reproduce this on CoinBase wallet on an iPhone.
