### ISSUE TITLE
Remaining Balance Gone Wild

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#235]
In Coinbase Wallet, if I click "All" to redeem my growing OUSD balance, the "Remaining Balance" field goes out of control flickering between `NaN` and an inexplicable, non-zero number less than my balance. If I click "All" again to return to the normal redeem, the "Remaining Balance" value aggressively climbs for a few seconds and then changes back to a low number that climbs more slowly. If I manually type the amount from the beginning, it works fine.

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin-dollar/pull/309
