### ISSUE TITLE
Error: could not detect network

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-dollar#236]
I get this before connecting a wallet:

    Error: could not detect network

Probably shouldn't be trying, or at least being quiet about it until it's actually an error state.

**Comment by sparrowDom** [comment]
@mikeshultz are you still experiencing this error? I can not reproduce it

**Comment by mikeshultz** [comment]
I kind of wish I added repro steps now because I don't remember where this came from.  Guess it's no longer occurring, closing.

**Comment by sparrowDom** [comment]
cool, thanks for testing it out @mikeshultz 🙏  Feel free to reopen in case you see it happening again.
