### ISSUE TITLE
CompoundStrategy over-estimates APR

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#237]
It seems we are over-weighting DAI in the Compound strategy APR calculation. Could be because DAI is 10 digits vs USDT/USDC 6 digits?

Here is the output of the scripts/deploy/checkDeploy.js script:
```Vault APR and balances
================
vault APR:        0.028952855086796242
totalValue (USD): 1548.077536561894754485
  DAI	: 208.855339043806697187
  USDC	: 1205.655818
  USDT	: 133.71889

Compound strategy
================
Balance and APR: 0.032170329217293643
  DAI	: balance=184.06455041536856367	APR=0.032170329217455
  USDC	: balance=1092.987793	                         APR=0.0068360801544425
  USDT	: balance=116.401639	                         APR=0.0149022669654625
```

**Comment by matthewliu** [comment]
Think we're mostly agreed on the very short-term to just have a centralized calculation, but I just want to say I'm comfortable with APY being calculated that way for at least the first few months. It'll be faster and more accurate than if we do it on-chain, and I don't think 98% of users will care that APYs are calculated in a decentralized way (as long as they are accurate).

Being able to buy/sell OUSD in a completely decentralized way is important. The rest is less so.

There may be downsides in composability in the mid-term if other smart contracts are conditionally deploying capital to us, but this probably won't be an issue for some time.

**Comment by tomlinton** [comment]
Centralized 👍
