### ISSUE TITLE
Localized Docs Link

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#239]
We currently link to the English version of the docs regardless of the locale selected on the DApp. We should be more intelligent about this so that non-English speakers don't need to find the language select twice.

**Comment by ZaHuPro** [comment]
@micahalcorn 
I found some mismatch in the languages that exist in docs and DApp.
The Italian language exists in DApp but not in docs and two more languages exist in docs that do not exist in the DApp.
I would like to know how to handle this one in the DApp

**Comment by micahalcorn** [comment]
Ah, thanks for pointing that out @ZaHuPro. I suppose we could write a GitBook plugin to redirect missing languages to English, but that's probably not worth doing. We should just manually point them to the English version of the docs if we don't have support there. That probably means we need mapping of languages that are supported on each side. For those that are available in the docs but not in the DApp, we'll just let people find those languages in the docs. We don't need to worry about linking from the docs to the correctly-localized version of the DApp (the inverse of what this issue calls for). Does that help?

**Comment by ZaHuPro** [comment]
@micahalcorn Yeah this is helpful, Thanks
