### ISSUE TITLE
Mint failure due to out of gas error

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#242]
Aure had a failed transaction due to running out of gas:
https://etherscan.io/tx/0xedf69e37aaf1c6950e82a3e9bb77f538d065c63e67906ffaee58c967382536c3

This was for minting 4 DAI, so in between the rebase threshold ($3) and allocate threshold ($5).

Here is the trace: 
https://majorhammers.com/tx/debug/0xedf69e37aaf1c6950e82a3e9bb77f538d065c63e67906ffaee58c967382536c3

Looks like it failed in the final stage here, when calling OUSD.mint
https://github.com/oplabs/origin-dollar/blob/master/contracts/contracts/vault/Vault.sol#L285

Aure tried again the exact same transaction and it succeeded:
https://etherscan.io/tx/0x102146e698107cc2d06f6e92e24961717b78b3260c435b011517d8d7c13b1ade

**Comment by DanielVF** [comment]
Another failure here:

(183,281 gas sent)

https://etherscan.io/tx/0x8526d810d9432959bd801a41738a60d294ba9468d3b38dfc19a632d178f98b44

![image](https://user-images.githubusercontent.com/837/94266754-91410480-ff08-11ea-9100-8ff4cfc11633.png)

That's not even enough to get past the oracles.

**Comment by sparrowDom** [comment]
Hopefuly @DanielVF 's change increasing the simple mint to 200k gas will prevent failed transactions like the one above
