### ISSUE TITLE
Disconnected Wallet State

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#25]
~~Build an index page for the DApp that involves some marketing/onboarding and a primary CTA for connecting a wallet. [Here](https://zpl.io/VKMynLP) is a placeholder, but the design is in progress.~~

We're no longer going to have an intermediate screen between the marketing home page and the wallet-connected DApp. We still need to decide what users will see in two cases:

1) Immediately after disconnecting a wallet

Our current plan is to redirect to /. But it seems a little odd to me for the way back into the /dapp to be to click "Get OUSD". Maybe if I have a cookie in my browser, we should change this button copy to "Connect"?

2) When landing on /dapp but the wallet has not yet connected

It can take several seconds for us to be able to access the Ethereum account after the page first loads. We'll probably want to display a skeleton version of the DApp while the account is loading.

**Comment by sparrowDom** [comment]
@micahalcorn thinking of something like this for a skeleton app:
<img width="988" alt="Screenshot 2020-10-13 at 23 36 31" src="https://user-images.githubusercontent.com/579910/95919225-7e09b200-0dad-11eb-8a7f-235a30eb5b3a.png">

Borrowed the body of the skeleton from when user has no stablecoins: 
<img width="962" alt="Screenshot 2020-10-13 at 23 35 52" src="https://user-images.githubusercontent.com/579910/95919268-911c8200-0dad-11eb-948a-bbbe395ec36e.png">

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin-dollar/pull/314

**Comment by micahalcorn** [comment]
Thanks, @auregimon approves ✅
