### ISSUE TITLE
Dapp sending far to little gas for RedeemAll 

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#256]
These two redeemAll transactions were sent with far too little gas.

https://etherscan.io/tx/0xd5829674e0096c18de2ded31b9403f24cda774d6ea332b897ea8feeec9414bde (33,000 gas)
https://etherscan.io/tx/0x7dd12b03326e04fe1cd8f5e266f5b0f57ef65dda2d04336418a2f7e7521f6f76 (97,836 gas)

**Comment by sparrowDom** [comment]
I am not sure how this could happen any other way then user setting a different limit manually inside Metamask or other web3 wallet. We hardcode it here: https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/components/buySell/SellWidget.js#L127-L129

Have also tested on prod and it gets set correctly to 3.3m
<img width="1045" alt="Screenshot 2020-09-25 at 15 51 16" src="https://user-images.githubusercontent.com/579910/94280430-b310aa80-ff4d-11ea-9a80-9087d9749e50.png">

Will close for now, unless there are some suspicions we could be causing this error with the Dapp code.
