### ISSUE TITLE
DApp does not surface out of gas transaction failure

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#262]
I minted a tx (https://etherscan.io/tx/0x4c8127efdc38fbb19d0a16fb0ca796f703d34c97139f27f5317dfbec9c33036d) that reverted due to out of gas failure but the DApp UI showed it as successful. The DApp should surface this error, an in general any error that causes the tx to get reverted.

<img width="1056" alt="Screen Shot 2020-09-27 at 3 18 51 PM" src="https://user-images.githubusercontent.com/945910/94377470-c7cc7a00-00d6-11eb-97a3-d09f0197fd2b.png">

**Comment by franckc** [comment]
CC @micahalcorn for prioritization

**Comment by sparrowDom** [comment]
Fixed in this PR: https://github.com/OriginProtocol/origin-dollar/pull/268
