### ISSUE TITLE
Add Token Help

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#270]
After a user mints OUSD for the first time, she may need to manually add the token address to her wallet. This is currently the case with MetaMask while we wait for them to merge [our PR](https://github.com/MetaMask/eth-contract-metadata/pull/572). However, it's not necessary for most of the mobile wallets. So we should be intelligent about when to encourage the user to add the token.

I recommend that we show a modal similar to [this one](https://zpl.io/V105K5k) only under the following circumstances:
- the current provider is MetaMask
- immediately after the balance changes from 0 to non-zero
- the user has not previously seen the modal

We only want to show it after a first-time mint, but it's not necessary to show it to a first-time minter who came to the DApp with OUSD already in her wallet. And, ideally, the modal would only appear _after_ all of the other animations are done so that she can see the success transition. Only after a balance is shown in the DApp is it relevant to see the balance in the wallet.

As for the content of the modal, we can show a copyable token address and/or implement a button using [EIP-747](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-747.md). I'm told by one of the authors of the EIP that it hasn't see much adoption across various wallets. But the main one we care about is MetaMask, and we know they support it. We should probably still show a small version of the address even if we include the button. I recommend timeboxing the EIP implementation and skipping altogether unless it can be done quickly.

**Comment by sparrowDom** [comment]
PR for this issue: https://github.com/OriginProtocol/origin-dollar/pull/276
