### ISSUE TITLE
Expandable Transaction Card

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#271]
After a user mints OUSD, we currently show a card that says "DAI converted to OUSD", for example. We also link to Etherscan for the user to see more information. But it's not possible for the user to see, at a glance, what transaction the card represents. This is particularly problematic if she is submitting multiple transactions in a short period of time.

Let's make the cards expandable with a new icon next to the Etherscan icon. Here are a couple of mockups:
- https://zpl.io/bzmx5E7
- https://zpl.io/29LnpxY

Another consideration is that the entire card is currently clickable. We should limit the clickable area to the Etherscan icon, the new expansion icon, and the close icon. Clicking the card itself should not have any effect.

This feature makes a lot of sense for mints and redeems (successful and failed), but I'm not sure how helpful it would be for token approvals. We can leave the new icon off of those for now.

**Comment by sparrowDom** [comment]
Pull request for this issue: https://github.com/OriginProtocol/origin-dollar/pull/285

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/285
