### ISSUE TITLE
Fail with error 'SafeERC20: low-level call failed'

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#281]
https://etherscan.io/tx/0xc0216471231a9a8c41a8f217f97a725e948a9c6161c46510815fc917bf1ffdce

<img width="730" alt="Screen Shot 2020-10-01 at 4 24 23 PM" src="https://user-images.githubusercontent.com/273937/94872869-9a4b3d80-0402-11eb-9f3e-08423f5b3485.png">

**Comment by tomlinton** [comment]
They had 0.348971 USDT and it was an attempted mint for 389.348971 USDT. Noting it looks like they just took the value from the max input and jammed 389 in front of it. I don't see a way to do that with the UI and still submit the transaction so I'd be inclined to chalk this up to a manual contract interaction and close it.
