### ISSUE TITLE
Selling Form Blocked

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#284]
While a `redeem` or `redeemAll` transaction is waiting to be mined, we're blocking the selling form. This is inconsistent with the buying form. I think [our desire here is to clear the form and workspace anytime a transaction is submitted](https://github.com/OriginProtocol/origin-dollar/issues/36) so that the user can proceed with more work. The sell side might be a little more confusing than the buy side though. If the user calls `redeemAll`, for example, the form will reset with an animated "remaining balance". But we probably want them to be consistent.

<img width="627" alt="Screen Shot 2020-10-01 at 5 23 39 PM" src="https://user-images.githubusercontent.com/273937/94888463-0db67480-042e-11eb-8034-ec8dab0bc7c4.png">

**Comment by rolandpo** [comment]
Outdated
