### ISSUE TITLE
Failing DApp Redirect

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#288]
In [this video](https://youtu.be/G2AzmDM8dP8?t=523), a user connected MetaMask and then was not redirected to /dapp even after subsequently clicking "Get OUSD" multiple times. He reported that an ad blocker was the culprit and that it worked fine once he disabled it. We should try to see what we're doing that conflicts with ad blockers and see if we can resolve this.

**Comment by joshfraser** [comment]
Do we know which ad blocker he was using so we can try and recreate the issue?

**Comment by micahalcorn** [comment]
No longer relevant 🤞
