### ISSUE TITLE
Slimjet browser

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#290]
OUSD Dapp doesn't login successfully in the [Slimjet browser](https://www.slimjet.com/) as can be seen from [this Youtube video](https://www.youtube.com/watch?v=G2AzmDM8dP8).

**Comment by sparrowDom** [comment]
cc @micahalcorn for prioritisation. I've set it to P4 for now, since it seems quite an obscure browser to me.

**Comment by micahalcorn** [comment]
Probably similar to https://github.com/OriginProtocol/origin-dollar/issues/264 😐

**Comment by rolandpo** [comment]
Outdated
