### ISSUE TITLE
Tools for verifying contracts on etherscan

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#307]
We need better tooling for generating the solidity contract code that can be then used to verify our contracts on etherscan.

Libraries to consider:
 - https://github.com/BlockCatIO/solidity-flattener
 - https://www.npmjs.com/package/truffle-flattener (note: @crazybuster mentioned this does not deal well with new-line includes)

**Comment by joshfraser** [comment]
There's also https://www.npmjs.com/package/truffle-plugin-verify

You can read more about it here: https://kalis.me/verify-truffle-smart-contracts-etherscan/

**Comment by DanielVF** [comment]
Buidler supports flattening everything.

https://github.com/nomiclabs/buidler/blob/0183504555c2aed2e3ea7e63b6ddeb656ce7d4f7/packages/buidler-core/src/builtin-tasks/flatten.ts

It might not be too hard to modify their code only flatten things upstream of a target contract in their dependency graph.

**Comment by tomlinton** [comment]
Truffle-flattener should work, my PR got merged into truffle to fix that multiline include https://github.com/trufflesuite/truffle/pull/3324 and it got into a release. Maybe they haven't updated the version that truffle-flattener uses.

**Comment by tomlinton** [comment]
Also the buidler flatten won't work due to multiline imports, I have a PR out for that https://github.com/nomiclabs/buidler/pull/757 but it hasn't been merged.
