### ISSUE TITLE
Dependency Contract Monitoring

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#310]
Establish a monitoring service that will alert us anytime a change is deployed to one of the external contracts that we depend on. Examples would be Compound's timelock contract and the Open Price Feed. The frequency of these updates might be quite high, so we may want to find a way to filter them to reduce the noise. We can probably start with just emailing a shared address and then eventually tie into GitHub or somewhere that we can track the review of each change.

**Comment by joshfraser** [comment]
I created a shared Etherscan account for us to use in the meantime and added the Compound timelock to their [alerting tool](https://etherscan.io/myaddress). I'll circulate the credentials via email.

**Comment by mikeshultz** [comment]
>  change is deployed 

What does this mean, exactly?

**Comment by mikeshultz** [comment]
I think I understand what you mean by this now.  We're looking for alerts for contract upgrades and key parameter updates for contracts our strategies interact with.   

Other than proxy upgrades, any examples you can provide that I can implement now?  I'll look into Compound's timelock today or tomorrow.

**Comment by joshfraser** [comment]
Yeah, we want to be notified of any parameter changes or new contracts that go through the timelocks of any of our supported strategies. Compound has a really nice dashboard that shows exactly what code will be executed with any proposal ([example](https://compound.finance/governance/proposals/32?target_network=mainnet)).

Having the alert be smart enough to say "This is the proposal to Distribute COMP to Affected Users in the DAI Liquidations and here are the code changes..." is nicer than just posting a raw tx hash, but anything is better than what we have now.

**Comment by mikeshultz** [comment]
Going to start exploring adding Compound stuff.  I think that's going to include:

- [Open Price Feed](https://compound.finance/prices)  [[dics](https://compound.finance/docs/prices)]
- [Timelock](https://app.compound.finance/timelock)  [[docs](https://compound.finance/docs/governance#timelock)]

I'm not super familiar with their general architecture yet so if anyone has any specific requests beyond these two that should be included early on, lmk.  Otherwise, we can add things as we go.

**Comment by mikeshultz** [comment]
May want to make improvements in the future but I think the initial Compound is pretty much done.  Will be starting Aave soon.

**Comment by mikeshultz** [comment]
Initial Aave implementation has been completed.  I'm gonna call this one closed.  Let me know if there's any further improvements you'd like to be made on the Compound/Aave side.
