### ISSUE TITLE
Exchange Rate Monitoring

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#311]
Similar to https://github.com/OriginProtocol/origin-dollar/issues/310, we should alert ourselves if any of our oracles report prices outside of expected ranges. This is probably straightforward for the stablecoin exchange rates, but I'm not sure what we would consider to be unexpected for ETH movement. cc @DanielVF

**Comment by mikeshultz** [comment]
Think I'd call this replaced by #417
