### ISSUE TITLE
Misleading Redeem Output

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#328]
I ended up in some odd state where my redeem preview did not add up to anywhere close to the amount that I was selling. I'm unable to reproduce this and I didn't submit the transaction, so I don't know whether it was a DApp issue or if the contract was returning the wrong amount. I suspect that it's a DApp-only concern and might be related to the comma in my number since the output nearly equals 110 instead of my 1,100.

<img width="577" alt="Screen Shot 2020-10-15 at 4 16 29 PM" src="https://user-images.githubusercontent.com/273937/96195735-5e37d280-0f02-11eb-94c7-91be35893574.png">

**Comment by micahalcorn** [comment]
Seen a second time with no comma 😕 I think maybe it had something to do with typing a `9` and then pausing before typing the rest.

![Uploading Screen Shot 2020-10-22 at 11.20.05 AM.png…]()

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin-dollar/pull/344
