### ISSUE TITLE
Collect Pending Rebase

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#364]
Once https://github.com/OriginProtocol/origin-dollar/issues/362 is completed, we would like to offer functionality for users to call `rebase` if they choose to lock in their earnings more frequently. [A "collect" link](https://zpl.io/VDeKJ1g) should be shown next to the pending rebase amount and clicking it should immediately queue up a rebase transaction in the user's wallet.

**Comment by ZaHuPro** [comment]
If the pending rebase amount is zero, should the collect link be hidden? @micahalcorn

**Comment by ZaHuPro** [comment]
@micahalcorn  should rebase transaction be shown in the side panel?

**Comment by micahalcorn** [comment]
Good questions @ZaHuPro yes, let's hide the link when the balance is zero but still have the help icon. I forgot to mention that the help icon should open a tooltip like https://zpl.io/bodRXLX. Go ahead and use lorem ipsum text there and I'll update it.

For the side panel, let's just do a card like this...

<img width="217" alt="Screen Shot 2020-12-06 at 10 03 48 AM" src="https://user-images.githubusercontent.com/273937/101288247-639af600-37aa-11eb-8224-e266d51ef73d.png">

...except use three grey OUSD icons instead of the blue USDC ones and use "OUSD supply increased".

**Comment by sparrowDom** [comment]
Done by @ZaHuPro via: https://github.com/OriginProtocol/origin-dollar/pull/492
