### ISSUE TITLE
MEW Integration not working

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#371]
Saw this occur in the flesh:

- User tries to mint
- MEW asks for confirmation
- User confirms
- DApp instantly displays error saying can't convert DAI to OUSD

**Comment by micahalcorn** [comment]
@tomlinton is this with MEW wallet (the mobile app)? They have several different wallet products.

**Comment by tomlinton** [comment]
Yea it was the mobile app sorry.

**Comment by nigel-binaryio** [comment]
I've experienced this, tried again right now, same error message.
From the MEW android app, v1.2.1 (393)

**Comment by micahalcorn** [comment]
I tried this just now and didn't have any issues minting OUSD using USDC from iOS MEW wallet 1.4.7 (21070701.203).
