### ISSUE TITLE
Cooldown time to rebaseOptIn/rebaseOptOut

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#397]
I think we should have a 24 hour cooldown between opt in/out as a safety feature. Any thoughts?

**Comment by franckc** [comment]
+1 for this idea since I can't think of any legit use case where it would be problematic to have the cool down.

@DanielVF @crazybuster @joshfraser any objection?

**Comment by DanielVF** [comment]
I don't know that it actually provides any protection, since its trivial to work around - just transfer the funds between accounts, one of which is opted in, and one of which is opted out.

**Comment by tomlinton** [comment]
That is true 👍

**Comment by tomlinton** [comment]
Closing this for that reason.
