### ISSUE TITLE
Get rid of mintMultiple and only support mint

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#400]
Note: This idea originated from the OUSD hack postmortem. Filing as a GH issue to have a discussion and make a decision on whether or not we want to implement this.

The main reason would be to simplify the code and reduce the chance of bugs.

CC @joshfraser  @tomlinton @DanielVF @micahalcorn @crazybuster

**Comment by tomlinton** [comment]
I think we've paid the price of the complexity already. Now that is audited and patched it seems worth keeping, as it provided a much better experience for people entering with 3 stables (2 transactions instead of 6 if you count approvals, or 1 instead of 3).

**Comment by micahalcorn** [comment]
In retrospect, I think this feature was unnecessary for the initial launch but it has seen some use in the wild. It would be good to analyze how often it has been used, but we would also need to make some considerable UX changes if we decided to can it.

**Comment by tomlinton** [comment]
Will close for the reason I mentioned, please reopen if you have further input and didn't get a chance to comment.
