### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#417]
In order to increase visibility into the system, we'd like to have a way to monitor various properties and events:
- [x] Unusually large, atypical transactions (mints, redeems, ...)
- [x] OUSD Burns
- [x] OUSD Vault pause/unpause
- [x] Failed transactions
- [x] Large deviations in the Oracle prices
- [x] Supply of OGN rewards being low on the OGN staking contract

In the future we might also want to consider expanding this tool to monitor activity on external contracts we depend on. For example triggering a notification anytime there is a new Compound governance proposal, a new deploy of their contract, a PR merged that touches their core code, tweets from Defi projects warning of a hack, etc...

The monitoring should have the ability to notify our team via posting on Discord and/or emailing.
It should be easy to add new properties to monitor.

The infra to use for running this is still TBD. One option is to make it part of the [ousd analytics stack](https://github.com/OriginProtocol/ousd-analytics).

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin-dollar/issues/311 and https://github.com/OriginProtocol/origin-dollar/issues/310

**Comment by mikeshultz** [comment]
@franckc FYI, I'm updating your list as I go.  

I'm going to implement the easier triggers now (transfers/transactions) and save the ones that require new data collection for later as incremental improvement.

**Comment by franckc** [comment]
@mikeshultz Perfect. The initial list was not exhaustive so thank you for adding anything you think will be useful and for prioritizing the most important alerts first...

**Comment by mikeshultz** [comment]
> Large deviations in the Oracle prices

I guess this means the oracles that `MixOracle` depends on?  `MixOracle` seems to reject anything outside of a drift range preventing the cases I was expecting to use as a trigger.

**Comment by DanielVF** [comment]
@mike Still might be useful to trigger an alert if it went 5% off of a dollar, even if it wasn't as extreme as our stops. 

I guess the hard part is that we are directly monitoring the oracles to the DB at the moment, but even just monitoring our supplysnapshot table would let us pick up medium sized deviations.

**Comment by mikeshultz** [comment]
Added basic Vault stable coin price checks (+/-5%) to the current PR.   ETH is a little less straight forward and I'll add it later.

**Comment by mikeshultz** [comment]
> Supply of OGN rewards being low on the OGN staking contract

Could one of you elaborate on this?  Heard it mentioned a bit on Discord but not really sure what this case might look like.`

**Comment by franckc** [comment]
@mikeshultz We are going to send OGN to the staking contract to cover the rewards. As users add new stake, we want to make sure we keep enough funds to cover their rewards otherwise it will fail when they dry to exit. So perhaps we could monitor that `stakingContract.OgnBalance` is greater than `alerting threshold TBD` + `stagingContract.totalOutstanding` and trigger an alert if not (which would mean we need to add OGN to the contract)?

**Comment by mikeshultz** [comment]
The PR below takes care of the final line item in this issue.  Will probably get merged & deployed today or tommorrow.  Closing this issue now.  Any further requests, please [submit to the ousd-analytics repo](https://github.com/OriginProtocol/ousd-analytics/issues/new/choose).

https://github.com/OriginProtocol/ousd-analytics/pull/11
