### ISSUE TITLE
Review OUSD compensation contract

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#423]
Two engineers should review https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/compensation/CompensationClaims.sol

This is a blocker for launching the compensation program.

**Comment by franckc** [comment]
CC @DanielVF @shahthepro @crazybuster  @tomlinton

**Comment by tomlinton** [comment]
Added some comments to the PR but generally looks good 👍

**Comment by nickgeoca** [comment]
I took a look. Outside of testing it, it looked pretty solid.

One concern I had was about the adjustor being a different address from the governor. If the adjustor somehow became sophisticated and malicious, then it would try to front-run the governor's start of the claims with a different set of claims. Running the adjustor lock before `start` would solve this, then add an `adjustorIsLocked` modifier. What is your threat model for the adjustor?

```solidity
    function start(uint256 _seconds)
         ...
        adjusterIsLocked
```

Have you considered the CompensationClaims pulling the funding from the governor? `transferFrom` tends to be slighly safer than using `transfer`- in the event several mutli-sig approvals agreed on the wrong address and the wrong amount during transfer.

```solidity
    function start(uint256 _seconds)
        ...
        SafeERC20.safeTransferFrom(token, msg.sender, address(this), totalClaims);
```

Overall the solidity code looked solid and I'd be interested in testing.

**Comment by franckc** [comment]
@nickgeoca Thank you for reviewing this contract! Great to have an external pair of eyes scrutinizing it!

Here is the sequence we plan on using:
 1. Governor unlocks the adjuster
 2. Adjuster uploads claims
 3. Governor locks the adjuster
 4. Everyone verifies that the claim amounts and totals are correct
 5. Payout funds are moved to the contract
 6. The claim period starts
 7. Users claim funds
 8. The claim period ends
 9. Governor can collect any remaining funds

In case the adjuster would get compromised, step 4 should detect any malicious data uploaded by the adjuster and step 3 prevents it from making any change before the claiming start.

In terms of funding the compensation contract, we will be funding it from an internal multi-sig wallet that minted OUSD.

Let us know if you have any concerns regarding this plan... :)

**Comment by nickgeoca** [comment]
Yes, that would take care of the concern. Step three and four look great! :+1:

**Comment by micahalcorn** [comment]
I hope this is done. 😬

**Comment by DanielVF** [comment]
It was!
