### ISSUE TITLE
Dapp Ledger account derivation confusion

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/origin-dollar#458]
Had a user today report that the address reported by the dapp was not the expected Ledger account.  It's a bit of an edge case, but one we may want to improve the UX on:

They had a Ledger legacy (chrome app) account with OGN but had 0 ETH.  In this case, we fall back to the new-style derived account because none had any ETH so we're kind of assuming a new unuse dledger.

https://github.com/OriginProtocol/origin-dollar/blob/cf879d58a2db26e0d40e64d93928020430aeadfd/dapp/src/utils/LedgerConnector.js#L94-L128

While it's true, we can't do anything with that account without ETH for gas, we might at least be able to coach the user on what to do in this case.  Might be good to check for OUSD/OGN/Stablecoin balances when enumerating these accounts and not just ETH.  Alternatively, we could check for any and allow account selection if we find multiple.  

CC @sparrowDom

**Comment by sparrowDom** [comment]
Thanks for getting to the source of the bug so fast @mikeshultz 💪 

@micahalcorn what do you think? Out of the solutions that Mike lists the easiest to do are:
 - checking other stable coin balances and changing the logic according to that. Multiple solutions here
   - pick a legacy account as soon as we detect any stable coin / ogn / eth
   - pick an account that has more ETH or stablecoins. 
 - detecting that a legacy - `non picked` account had stable coin balances but no ETH balance and was skipped. And display some warning message in the dapp maybe something like "Ledger account 0x... has some [OGN, USDT, DAI...] but no Eth. Send some ETH to it for the dapp to use it". 

Ideally account selection would be the best solution out of the proposed ones, but that one is a bit more involved.

**Comment by sparrowDom** [comment]
Just leaving some more feedback from Craig here: 

`thanks for your help today. I finally figured things out and was able to stake my coins. Just wanted to confirm that it did not work for me simply by having ETH in my wallet. I actually had to use metamask, connect my hardware nano s wallet to metamask, and then stake on dapp using metamask.`

**Comment by micahalcorn** [comment]
Another user reported that contract data had been disabled.

**Comment by sparrowDom** [comment]
@micahalcorn the user needs to enable contract data on the ledger device in the Ethereum app under settings.

**Comment by joshfraser** [comment]
Bumping this up in priority.

When you choose Ledger, we should show options for choosing the deviation path and wallet address. We should make an intelligent guess based on the coins in their wallet and preselect the wallet with the highest balance while still giving them the freedom to choose.

**Comment by joshfraser** [comment]
Bumping this up to a P1, especially now that a large percentage of our target users are going to be Ledger users.
