### ISSUE TITLE
Enable solidity code coverage

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#460]
It would be good for us to know our solidity code coverage when running our current unit tests.

This will allow us to understand how our current test suite is performing in terms of coverage. It will also point us to areas of our solidity codebase that are not covered well so that we can focus on writing new tests for these..

The hardhat [solidity-coverage](https://hardhat.org/plugins/solidity-coverage.html) plugin seems like a good option for this.

**Comment by Rishabh42** [comment]
Hardhat is a good option especially for tests as it has been observed to reduce the time it takes to run the tests especially when compared to truffle + Ganache. However, in my experience there were some problems associated with running the coverage (in another project of mine). I'll try integrating this with `origin-dollar` and update my findings here

**Comment by franckc** [comment]
Great! Thanks @Rishabh42 for your help on this.

I invited you to the Origin GitHub project so that you can create PRs on a branch without having to fork.

Do feel free to reach out on our Discord engineering channel if you have any question -  we are there to help :)

**Comment by Rishabh42** [comment]
Sure, sounds great. So should I create a new branch for every specific new feature I add/issue I fix and then open a PR from that branch to `master` ?

**Comment by franckc** [comment]
All you need to do is clone the repo, then create a branch (we typically recommend to use you GitHub username as prefix), then when you are ready, push your branch and create a PR against master branch. For example in my case I typically do
  - `git checkout -b franckc/mybranch origin/master`
  - make changes, test, commit
  - when ready to create a PR:
    - run prettier to format the code `yarn run prettier` , then commit `git commit -am prettier`
    - push the new branch`git push origin franckc/mybranch`
    - create PR on github.com

**Comment by franckc** [comment]
@Rishabh42 Are you actively working on this issue? If not, do you mind if I un-assign it from you so that other contributors can take a shot at it?

**Comment by Rishabh42** [comment]
@franckc Yes, you can assign it to someone else. 
As discussed previously, I'll start looking into the issues once I get more bandwidth
Thanks

**Comment by ssfanist** [comment]
https://github.com/OriginProtocol/origin-dollar/pull/918
@franckc please check this PR.
attaching coverage result screenshot as reference.
![coverage](https://user-images.githubusercontent.com/37310971/155694668-2811020f-6802-4f14-97ea-be68861b1f76.png)

**Comment by franckc** [comment]
Thanks for implementing this @ssfanist ! Nice work - we appreciate your contribution :)
