### ISSUE TITLE
Make test fixtures work on the fork

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#462]
The [test fixtures](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/test/_fixture.js) that loads contracts, addresses, define user accounts and funds them currently do not work on the fork.

Here is how to reproduce:
  - On a terminal, start a fork node:
```
export BLOCK_NUMBER=<recent block number>
export PROVIDER_URL=<alchemy or infura URL>
yarn run node:fork
```
  - On a separate terminal, start a console
```
FORK=true npx hardhat console --network localhost
```
  - In the console issue these commands
```
const { defaultFixture } = require("./test/_fixture")
await defaultFixture()
```

It would be really useful to have a simple way to load the equivalent of those test fixtures when running a console on the fork. To make the code more modular, these could be in a separate fork_fixture.js file under the test or utils directory.

**Comment by shahthepro** [comment]
Closing this since it is irrelevant now
