### ISSUE TITLE
Implement smoke tests on the fork

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#463]
Before running a new deploy in production, it would be useful to be able to do the deploy on the fork and then run a small suite of "smoke tests" to make sure all the core functionalities of the OUSD contracts work as expected:
 - mint
 - redeem
 - allocate

**Comment by franckc** [comment]
Note: this is related to #462

**Comment by franckc** [comment]
Idea from @DanielVF : "Perhaps we should also make sure that these smoke tests unlock a current OUSD holder account and exercise it. Just minting new money may hide a change to old slots."

**Comment by mikeshultz** [comment]
I was trying to run unit tests against the fork to generate random events for use in testing analytics.  This apparently crashes the ganache instance.  :confused:
