### ISSUE TITLE
Tool for checking storage slots before a deploy

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#468]
We had an incident where, due to a mistake, storage slots were shifted during the deployment of a new contract. Writes were then issued and caused a data corruption.

To prevent this from happening in the future, we should have a tool we run prior to a deployment to check the storage slots of the current contracts on the master branch vs the ones of the contracts on Mainnet.

**Comment by franckc** [comment]
CC @DanielVF @tomlinton

**Comment by DanielVF** [comment]
Hardhat does some kind of upgrade checking here in this module.

https://hardhat.org/plugins/hardhat-upgrades.html

**Comment by franckc** [comment]
A relevant article: https://blog.coinbase.com/usdc-v2-upgrading-a-multi-billion-dollar-erc-20-token-b57cd9437096 with pointers to USDT storage slots unit tests.

**Comment by mikeshultz** [comment]
If the hardhat stuff is good enough, great.  An alternative might be a simple tool using [the antlr4 parser](https://github.com/federicobond/solidity-parser-antlr) and looking for storage def changes.

**Comment by sparrowDom** [comment]
Solution for this here: https://github.com/OriginProtocol/origin-dollar/pull/536
