### ISSUE TITLE
Readable Historical Yield

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#47]
Our contract should be able to provide the yield at various points in the past. With this, a DApp could display a graph of the yield over the past week, month, year, etc. It might also be helpful to be able to tell users that the "average yield" over the preceding period has been X, which is potentially more informative than the [current yield](https://github.com/oplabs/origin-dollar/issues/13). I'm not sure how well actual earnings will map to time periods since they will accrue as blocks are mined rather than specifically as time passes. But we should be able to approximate it accurately enough.

**Comment by DanielVF** [comment]
We've got events firing for this:

```
event TotalSupplyUpdated(
uint256 totalSupply,
uint256 rebasingCredits,
uint256 rebasingCreditsPerToken
);```

I don't think there's any need for actual price recording on chain beyond the log events.
