### ISSUE TITLE
Frontend Changes for Relaunch

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#471]
Here's what we just discussed for ousd.com:

- [x] Change the top banner to say something like "OUSD has relaunched with independent audits and a renewed focus on security."
- [x] Change the top banner color from blue to black (with white text).
- [x] Show the top banner on all screens (including /stake).
- [x] Add https://zpl.io/bzKrQLA to all dapp screens (/mint and /stake).
- [x] Hide the APY banner on all mobile screens.
- [x] Remove the big red alert from /mint.

**Comment by sparrowDom** [comment]
Pull request for this: https://github.com/OriginProtocol/origin-dollar/pull/476

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/476
