### ISSUE TITLE
Flickering Transaction Icons

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#480]
These icons flicker on the first hover because the `:hover` image has to be loaded. We should preload them or use a sprite strategy to avoid this.

<img width="72" alt="Screen Shot 2021-01-05 at 5 18 13 PM" src="https://user-images.githubusercontent.com/273937/103717455-63914000-4f7a-11eb-976c-b735bc7c0001.png">

**Comment by flashguru-git** [comment]
@micahalcorn 
A simple fix, would you please invite me so that I can create PR?

**Comment by micahalcorn** [comment]
Thanks, you should have an invitation @flashguru-git. 😊

**Comment by calvintoes** [comment]
https://github.com/OriginProtocol/origin-dollar/pull/837

**Comment by micahalcorn** [comment]
I love seeing this fix. 😁
