### ISSUE TITLE
Confusing TotalSupplyUpdated event emitted during a mint

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#484]
During an OUSD mint the following happens
 - rebase() is called, which emits a TotalSupplyUpdated event
 - mint() is called, which internally updates the total supply but does **not** emit a TotalSupplyUpdated event, Just a Mint event.

This causes a bit of confusion when looking at events since one would assume that the TotalSupplyUpdated includes the amount from the mint but it does not.

A possible improvement would be to:
 - rename the TotalSupplyUpdated event emitted in the rebase to ChangeSupply 
 - move TotalSupplyUpdated to mint/burn

If we decide to make this change we'll need to make sure to update the analytics back-end accordingly.

**Comment by franckc** [comment]
CC @tomlinton and @mikeshultz for any additional input since we briefly discussed this on discord.

**Comment by mikeshultz** [comment]
I'm not sure this warrants contract changes.  I'm leaning towards leaving it up to better interpretation by the event consumers(in our case, ousd-analytics).  To me, `TotalSupplyUpdated` means the supply was explicitly updated, not just altered by mint/burn so it seems wrong to add it to that.

Here's the sister issue on ousd-analytics: https://github.com/OriginProtocol/ousd-analytics/issues/24

**Comment by franckc** [comment]
Does not look like it's worth fixing. Closing.
