### ISSUE TITLE
Aave V2 Migration

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#496]
It's getting time to migrate to AAVE v2. Interest rates are higher, liquidity is bigger and gas cost is supposed to be cheaper.

The API has changed in AAVE v2, so we will need to deploy a new strategy contract.

## API changes

_Our current [AAVE strategy code](https://github.com/OriginProtocol/origin-dollar/blob/6e2b1738fe876aa8e7e6d38c23417383ed33b3ad/contracts/contracts/strategies/AaveStrategy.sol). New v2 AAVE [lending pool code](https://github.com/aave/protocol-v2/blob/ice/mainnet-deployment-03-12-2020/contracts/protocol/lendingpool/LendingPool.sol)._

Deposit method has changed from 

```
deposit(address _reserve, uint256 _amount, uint16 _referralCode)
```

to: 

```
deposit(
    address asset,
    uint256 amount,
    address onBehalfOf,
    uint16 referralCode
  )
```

Withdraw method has changed be **on the pool contract** instead of on the aToken:

I think the method signature remains the same, but we should check that we match the new:

```
withdraw(
    address asset,
    uint256 amount,
    address to
  )
```

Balance checking remains the same, just using the new atoken.

We'll need to add the ability to set the `platformAddress` storage slot in the AaveStrategy. Unless I'm missing something obvious, I don't see a setter. Alternately, we could just hardcode it in the new contract.

## Governance Proposal

We'll need a governance proposal to:

1. Pull funds out from strategy - `VaultAdmin.withdrawAllFromStrategy(0x9f2b18751376cF6a3432eb158Ba5F9b1AbD2F7ce)`
2. Upgrade strategy
3. Set atoken AAVEStrategy.setPTokenAddress(0x6b175474e89094c44da98b954eedeac495271d0f, 0x028171bca77440897b824ca71d1c56cac55b68a3 )
4. Set platform
AAVEStrategy.setPlatformToken(0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9)
5. Reallocate Funds - VaultCore.allocate()

## Token cheatsheet

|V|Name|Address|
|-|-----|--|
|v1|aDAI|0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d|
|**v2**|aDAI| 0x028171bca77440897b824ca71d1c56cac55b68a3 |
|v1|LendingPool|0x398ec7346dcd622edc5ae82352f02be94c62d119|
|**v2**|LendingPool|0xd97fE382b923F75Ab8951915eCF07CBf12c102D4|
|v1|LendingPoolProvider| 0x24a42fd28c976a61df5d00d0599c34c4f90748c8 |
|**v2**|LendingPoolProvider|0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9|

## To Do

- [x] Update contract
- [x] Update mocks
- [ ] Write deploy script
- [ ] Test on fork
- [ ] Deploy contract
- [ ] Test on fork
- [ ] Governance Actions

**Comment by DanielVF** [comment]
# AAVE v1 to Compound, intermediate migration

We'll need a governance action to set the cToken for DAI for the Compound Strategy, followed by three strategist actions.

Here's my internal test script for checking the procedure.


### 0. Setup additional contracts for this sim
```
from world import *
from addresses import *
AAVE_STRAT = "0x9f2b18751376cF6a3432eb158Ba5F9b1AbD2F7ce"
COMP_STRAT = "0xD5433168Ed0B1F7714819646606DB509D9d8EC1f"
CDAI = "0x5d3a536e4d6dbd6114cc1ead35777bab948e3643"
GOV = "0x8e7bDFeCd1164C46ad51b58e49A611F954D23377"
aave_strat = Contract.from_explorer(AAVE_STRAT)
comp_strat = Contract.from_explorer(COMP_STRAT)
```

### 1. Governance action
```
comp_strat.setPTokenAddress(DAI, CDAI, {'from':GOV})  # Gas used: 48624
```


### 2. Strategist actions
```
vault_admin.setAssetDefaultStrategy(DAI, COMP_STRAT ,{'from':STRATEGIST}) # Gas 40,557
vault_admin.withdrawAllFromStrategy(AAVE_STRAT, {'from':STRATEGIST}) # Gas used: 596,289
vault_core.allocate({'from':STRATEGIST}) # Gas used: 1,519,170
```

### 3. Testing that it worked
```
# Vault totals correct
>>> int(vault_core.checkBalance(DAI) / 1e18)
1,743,564
>>> int(vault_core.checkBalance(USDC) / 1e6)
5,125,727
>>> int(vault_core.checkBalance(USDT) / 1e6)
11,315,454
```

```
# No DAI in AAVE
>>> int(aave_strat.checkBalance(DAI) / 1e18)
0
# DAI moved to compound
>>> int(comp_strat.checkBalance(DAI) / 1e18)
1,564,762
```

```
# Mints and Redeems stil work
dai.approve(vault_core, 1e18 * 1e18, {'from': COLDWALLET}) # Gas: 29,106
vault_core.mint(DAI, 1e6 * 1e18, 0, {'from': COLDWALLET}) #Gas: 2,176,467
vault_core.redeem(int(0.95 * 1e6 * 1e18), 0, {'from': COLDWALLET}) # Gas: 2,094,212


>>> int(aave_strat.checkBalance(DAI) / 1e18)
0
# DAI went into and out of Compound Strat
>>> int(comp_strat.checkBalance(DAI) / 1e18)
2420394
```

**Comment by DanielVF** [comment]
@mikeshultz Will we need to update analytics to look for DAI in the compound strat, or does it already do that?

**Comment by mikeshultz** [comment]
Looks like it'll need to get updated.  Added an issue to track.  Should be a simple update.  What's the timeline on this?

https://github.com/OriginProtocol/ousd-analytics/issues/136

**Comment by DanielVF** [comment]
@mikeshultz Next couple days?

**Comment by mikeshultz** [comment]
Will try and work this change in today or tomorrow.

**Comment by DanielVF** [comment]
Much awesome! Thanks!

**Comment by mikeshultz** [comment]
btw, analytics has been updated to track DAI in the Compound strategy.

**Comment by mikeshultz** [comment]
> "0x00", // no rewardTokenAddress

Maybe this is out of scope currently, but aren't there AAVE token rewards for lending?

**Comment by micahalcorn** [comment]
> > "0x00", // no rewardTokenAddress
> 
> Maybe this is out of scope currently, but aren't there AAVE token rewards for lending?

I'm not aware of any unless they added some new incentives. Historically, you could only earn by staking.

**Comment by mikeshultz** [comment]
I'm personally lending a minor wad to AAVE and I'm receiving stkAAVE (their AAVE staking token) for lending.  When using their UI to claim my rewards (AAVE tokens?), it sends `0x3111e7b3` (`claimRewards(address[],uint256,address)`) to [`0xd784927Ff2f95ba542BfC824c8a8a98F3495f6b5`](https://etherscan.io/address/0xd784927Ff2f95ba542BfC824c8a8a98F3495f6b5), which is [StakedTokenIncentivesController](https://github.com/aave/incentives-proposal/blob/master/contracts/incentives/StakedTokenIncentivesController.sol).

Method doc:

> Claims reward for an user, on all the assets of the lending pool, accumulating the pending rewards

This seems to only update internal balances.  There seems to be a followup transaction indicated by the UI, presumably a tx with a transfer but I didn't want to waste money executing the claim.  Also having a hard time finding this stuff in their docs...

**Comment by mikeshultz** [comment]
Looks like they call it [Liquidity Mining](https://docs.aave.com/developers/guides/liquidity-mining).

> Liquidity mining/incentives was implemented in the Main Aave market via AIP-16, enabling incentives for both depositing and borrowing. Incentives are also currently implemented on the Polygon market, using the same implementation details as described on this page.
> 
> [...]
>
> For the main market, stkAAVE is rewarded and automatically accrues interest based on the Staking AAVE parameters once claimed. There is an associated 10 day cool down period to convert stkAAVE to AAVE, with a 2 day redeem period to do so. Ensure that this information is presented to the user and handled correctly.

**Comment by micahalcorn** [comment]
Oh, that's great to know @mikeshultz 👍 I've been out of the loop since I haven't used Aave since late last year. We should claim the rewards for sure.

**Comment by DanielVF** [comment]
Sure enough. I called the contract methods to plan, and AAVE v2 is incentivized.

**Comment by micahalcorn** [comment]
Pretty much [done](https://github.com/OriginProtocol/origin-dollar/pull/601) ✌️
