### ISSUE TITLE
OUSD compensation analytics

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#502]
For OUSD compensation it would be nice to have a dashboard that shows basic analytics data: 
- how many accounts have already claimed OGN / OUSD
- what is the total amount already claimed / remaining for each of OUSD and OGN

**Implementation:**
We were on the fence whether to implement this as a completely client side thing in the dapp or have analytics listener capture the events / decode transactions. Because we will have to decode and store transactions anyway in the analytics the decision has been made to implement the whole thing in the analytics module. 

- Regarding `CompensationClaims` contract the `Claim(address recipient, uint256 amount);` event will be captured and stored
- Regarding `SingleAssetStaking` calls to  `_stake` shall be harvested 

**Related issue:** https://github.com/OriginProtocol/ousd-analytics/issues/43

**Comment by sparrowDom** [comment]
@micahalcorn the analytics dashboard ticket ☝️

**Comment by mikeshultz** [comment]
This intended to utilize the API of [OriginProtocol/ousd-analytics](https://github.com/OriginProtocol/ousd-analytics/)?

**Comment by sparrowDom** [comment]
@mikeshultz I am a bit on the fence about this. In theory we wouldn't need any analytics code since all data can be fetched directly from contracts. The downside is that 730 read calls need to be made on OUSD and OGN compensation contracts to figure out which accounts have already claimed their tokens.

I am leaning toward making those contract calls in via wallet provider (to not hammer Alchemy). And users would probably need to wait a couple of seconds or more for the data to show up. It would be slow but super easy to implement. And after the compensation period ends (which is currently set to 90 days) we won't have a need for that dashboard anyway.

Curious what are your thoughts on this?

**Comment by mikeshultz** [comment]
> The downside is that 730 read calls need to be made on OUSD and OGN compensation contracts to figure out which accounts have already claimed their tokens.

That's a lot of requests for every single visit to the page.

I'll let you make that call for the frontend.  FWIW, there's a very high probability that we're going to be pulling this data into ousd-analytics at some point(the events at least).  Whether or not you use it for the FE may only change the timing of implementation.

**Comment by micahalcorn** [comment]
Mini-spec: https://docs.google.com/document/d/1skp5K2qzNxCjCEBNok867wKsDDe0Na0dWBOniwcEK7Q/edit#

**Comment by sparrowDom** [comment]
Nice to me it looks like the spec has all the data we will be interested
in.

**Comment by micahalcorn** [comment]
Closing this since most of the claims have been made 📘
