### ISSUE TITLE
Prettier enforcement on JS in contracts subdir

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#533]
I think we have this via a Husky hook on the DApp stuff. Would be great to add it to the contracts dir as well as unpretty js keeps slipping through.

**Comment by cipherzzz** [comment]
Hey @tomlinton - can you be more specific on `contracts` subdir? Are you saying that you want the solidity to be formatted? I didn't see any js in the the `contracts` dir.

**Comment by tomlinton** [comment]
There is a lot of js in /contracts 🙂

**Comment by cipherzzz** [comment]
sorry - I was looking in `/contracts/contracts` like a dummy 🤦

**Comment by cipherzzz** [comment]
you can assign this to me
