### ISSUE TITLE
Compensation Claims Test Failing in CICD

### ISSUE THREAD

**Issue by cipherzzz** [OriginProtocol/origin-dollar#569]
Issue:
   The `compensation claims` test is failing in CICD

https://github.com/OriginProtocol/origin-dollar/pull/566/checks?check_run_id=1942593912

```
1) Compensation Claims
       User claims
         "before each" hook for "should show a user their funds, and a total of all funds":
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/origin-dollar/origin-dollar/contracts/test/compensation/compensationClaims.js) 
```

**Comment by franckc** [comment]
This does not fail on local, only on CI. Probably because CI runs slower. Increasing our tests timeout should hopefully fix it.

**Comment by franckc** [comment]
I don't think this is an issue anymore. Closing.
