### ISSUE TITLE
Intelligent Transaction Routing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#576]
There are generally three decentralized ways to exchange a stablecoin for OUSD or vice versa.

1. mint/redeem with our vault contract
2. swap using an AMM
3. swap using our flipper contract

Currently, users are required to visit three different DApps to determine which route is the most cost-effective. We can measure the variables for them and simplify the process. A user should be able to go to a single DApp, give us her desired input or output, and have her transaction routed to the most advantageous contract. By integrating an AMM and our own swap contract into our main DApp, we will introduce several UX complexities. We're starting the design process to figure out what this will look like, but we can go ahead and build the logic behind the scenes now.

@DanielVF has already written [some code](https://github.com/OriginProtocol/ousd-analytics/blob/266a4ebe1644f7944bef15d759711115c5eac7df/eagleproject/core/templates/powermint.html#L47-L74) for cost comparison. This is used to visualize the options at [analytics.ousd.com/powermint](http://analytics.ousd.com/powermint). He has also built [a standalone DApp in ousd-analytics](https://github.com/OriginProtocol/ousd-analytics/tree/master/eagleproject/core/static/core/flipper) that supports swapping with the flipper contract at [analytics.ousd.com/swap](https://analytics.ousd.com/swap).

While we wait for designs to specify how the frontend should be handled, let's add the logic to our DApp and just route the transaction appropriately without indicating to the user which path is being taken. In other words, a user will input 5,000 USDC, click "Mint Now", and the transaction will either call [`buyOusdWithUsdc`](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/flipper/Flipper.sol#L50-L57), [`mint`](https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/vault/VaultCore.sol#L36-L87), or the Uniswap method. Note that we won't likely deploy the DApp in this state because we want to be transparent with users about which contract is being called.

Here are some considerations that come to mind:
- `mintMultiple` and `redeemAll` are not applicable to the swap contracts. If a user wants to exchange more than one type of stablecoin for OUSD or exchange the max amount of OUSD for stablecoins, the transaction should simply be routed to our vault contract.
- ERC-20 allowances are granted per-contract, so we may need to prompt the user for approval before submitting the transaction even if an allowance had been previously approved for a different contract.
- Price tolerance is only applicable to our vault contract, and slippage is only applicable to AMMs. There is no analogous concept for the flipper contract. Let's just hard-code the slippage tolerance parameter at 0.5% if the transaction is being routed to Uniswap. We can also use the standard 20-minute transaction deadline and allow multihops (or just inherit defaults if it's easier).
- When calculating the most cost-effective route, we should take into account gas costs ([fast](https://www.gasnow.org/)), fees (Uniswap and OUSD redeem), and exchange rate or slippage consequences.
- When comparing redeem output to swap output, it's fine to treat all stablecoins the same. In other words, an expected redeem output of 1 DAI + 2 USDC + 3 USDC can be considered more beneficial than an expected swap output of 5.999999 DAI even if the DAI is worth more in USD terms.
- When comparing expected outputs, we should be comparing minimums. We shouldn't compare "estimated" results from the vault and Uniswap since those are unreliable (due to oracle movement and slippage).

**Comment by joshfraser** [comment]
Just thinking out loud here. I wonder if we should build a Uniswap style UI with 1 coin swapping to 1 other coin. It certainly makes the most sense for the second two use-cases listed here. I expect our users would find that UI more intuitive, or at least more familiar. Do we have any data on how many people are currently minting using multiple coins vs. just one? I'm thinking we would keep the current UI as an "Advanced" view but default to a simple Uniswap style UI with the smart routing logic that you described. We could switch into the Advanced mode automatically if we detect it's advantageous (large amounts of more than 1 stablecoin).

**Comment by sparrowDom** [comment]
Done
