### ISSUE TITLE
Increase OUSD credits resolution

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#590]
OUSD currently cannot mint to Uniswap v3.

### Background:

OUSD stores balances as "credits" that back each account. These value of these credit go up as OUSD rebases. When transferring funds from one account to another, the OUSD transfer method subtracts a number of credits from the sender and  adds credits to the receiver account.

Unfortunately the resolution on these credits to token ratio is larger than the 18 decimals resolution of OUSD balances. It's like trying to making dollar exact change using only bills of a $1.13 face value. This means that OUSD must either round up or down or round down when converting to credits and back up. Implementing either up or down will almost always result in either more or less being transferred than was requested. This rounding error affects both the sender account and the receiver account.

Currently, we round down for credit calculations, resulting in the sender receiving less than the amount requested to be transferred.
  
    >>> ousd.balanceOf(TARGET)
    0
    >>> ousd.transfer(TARGET, 10000, {'from': SENDER})
    ....
    >>> ousd.balanceOf(TARGET)
    9999

This is fairly unintuitive, and breaks Uniswap v3's mint checks, which insure that the exact amount requested to transfer in was transferred in.

### Options: 

Off the top of my head, some options for fixing this:

A. Add 1/1e18 credit to the receiver on each transfer for more than a credit. Extremely minimal change to code. This will make the ending receiver balance in OUSD be equal to or greater than. This will increase the actual supply on each transfer (but by insanely, unimaginable amounts). Disadvanage is that if we want to keep the accounting perfect, we also need to write this value change to the the total supply, which costs one write's worth of gas per transfer.

B. We could round up when computing transfers. While this takes makes the receiver's account be correct, the it does mean that the sender's accounting is less, and maybe?might? fail a legit transfer. A sender with 30000 raw OUSD would be unable to make 3x 10000 transfers.
 
C. We could take OUSD offline and increase the resolution of credits. This is by far the most work. If each credits was worth only a fraction of what it is now, then the increased resolution could mean that this would almost always work out to the right answer.

**Comment by joshfraser** [comment]
Thanks for looking into this. Is there a magic amount of liquidity that we could provide that wouldn't have rounding issues? Uniswap v3 is really ideal for trading OUSD but I understand that we're strapped for bandwidth right now.

At first glance, option C seems like the "correct" long-term solution.

In the meantime, A seems like a decent stop-gap solution assuming it doesn't create too much of a mess to clean up later. How bad would it be if we didn't have perfect accounting in the name of keeping transfer costs at a minimum?

The failure case for option B seems bad enough that we should avoid it. 

Curious to hear @tomlinton's thoughts on this.

**Comment by tomlinton** [comment]
Oof this is not fun. None of the options spark joy 🤣 A does cause me physical pain.

I'm in agreement with Josh, C is nice for correctness, but A seems good for now. It'd be a bit of an undertaking to correct it after, but if we are doing C later on then the additional work doesn't seem huge.

**Comment by DanielVF** [comment]
Another option...

D: We can live migrate accounts to the different resolution as transfers take place. We can use the high bit on the per account "nonRebasingCreditsPerToken" value to mark if the migration has taken place. This storage slot is already read in both _creditsPerToken, which is exactly where we would need to know if it's an low res or high res number for the user, and in _isNonRebasingAccount, which is where we would do the migrations. This means that there's basicly zero ongoing gas cost to having this in, just the first time migration cost which is only an extra 20-30K gas.

https://github.com/OriginProtocol/origin-dollar/blob/master/contracts/contracts/token/OUSD.sol#L354-L364

**Comment by DanielVF** [comment]
The v2 AAVE aTokens are an interesting reference for a very battle tested rebasing token with a 1e27 internal interest rate resolution. 

- https://github.com/aave/protocol-v2/blob/master/contracts/protocol/tokenization/AToken.sol
- https://github.com/aave/aave-protocol/blob/master/contracts/libraries/WadRayMath.sol

I've not yet checked if they the way they are doing things fix the issue, but it is a good example of a sightly different approach to multiplication and division.

**Comment by DanielVF** [comment]
## Approach

After writing some code to try out the live migration of values as they are used approach, I now lean towards an upgrade contract. I don't like having any ongoing complexity put into the contract that must stay there for all time.

We need to upgrade the values for:

- rebasingCredits (one time)
- rebasingCreditsPerToken (one time)
- _creditBalances (for each account)
- nonRebasingCreditsPerToken (for each account that does not rebase)

## Correctness

While we could do these via a contract that trusts offline calculations for each of these values, I'd like to keep as much of the correctness guarantees run on-chain as possible.

  1. The math for each adjustment  (simple for the upgrade contract to handle)
  2. Each adjustment should not be run more than once (could be handled by calls out to a contract that records that an address is being upgraded, and only permits one call per account.)
  3. Each adjustment should have been run before leaving the upgrade contract (feels impossible to do on-chain, given that the final control of the upgrades is outside the contracts. It's certainly easy enough to verify off-chain though.)

## Backwards compatibility 

Given that this upgrade would be massively increasing the creditsPerToken value, a change would throw off those depending on this to calculate yield/apr. We've got three options here:

1. Keep the OUSD contract exactly as is. Values will take big change. Notify those using OUSD programmatically about the change (kucoin, new integration parters), they can pause and update their own code.
2. Make the old methods backwards compatible by returning the real numbers to match the old style. Add new methods that return the true new values.
3. Use only the new value, but change the names on all methods that return them. This will then break anything using them.

I'm against adding ongoing complexity to the contract, so I'd lean towards either 1 or 3.

**Comment by tomlinton** [comment]
Any thoughts on how we'd achieve the per account changes? Been a while out of Solidity land. I guess it'd be a matter of having a migration function that accepts an array of addresses and we feed it all the accounts.

For the backward compatability, 1. seems like it might be the best option. Is the only function that matters the `function creditsBalanceOf(address _account)`? We could just leave that in place, and expose a new widgetsBalanceOf or whatever, ask any integrators to migrate and then remove it in a future upgrade.

**Comment by DanielVF** [comment]
@tomlinton I was thinking of something along these lines:

```
function upgradeGlobals() external {
        require(isUpgraded[address(0)] == 0);
        isUpgraded[address(0)] = 1;
        rebasingCredits *= RESOLUTION_INCREASE;
        rebasingCreditsPerToken *= RESOLUTION_INCREASE;
    }

    function upgradeAccounts(address[] calldata accounts) external {
        for (uint256 i = 0; i < accounts.length; i++) {
            address account = accounts[i];
            require(isUpgraded[account] == 0);
            isUpgraded[account] = 1;

            _creditBalances[account] *= RESOLUTION_INCREASE;
            uint256 nrc = nonRebasingCreditsPerToken[account];
            if(nrc > 0){
                nonRebasingCreditsPerToken[account] = nrc * RESOLUTION_INCREASE;
            }
        }
    }
```

**Comment by DanielVF** [comment]
@tomlinton On the backwards compatibility, not only that method changes, but also all our public variables with the name "credits" in them. We'd have to change the names of the variables, then provide accessors that divide the actual values to make them smaller to match the old values.

**Comment by tomlinton** [comment]
True true. Are there any integrators that we are aware of that would need to update aside from Kucoin?

**Comment by DanielVF** [comment]
@micahalcorn We've made it so new, contract accounts come in at high resolution, but we haven't changed anything about the rest of accounts yet.

**Comment by micahalcorn** [comment]
I think this is done now.
