### ISSUE TITLE
Curve Transaction Routing

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#627]
Once https://github.com/OriginProtocol/origin-dollar/issues/576 is done, we'll want to add support for [our OUSD MetaPool](https://etherscan.io/address/0x87650d7bbfc3a9f10587d7778206671719d9910d#code) since that's where we'll be focusing most of our liquidity efforts. Much like we're doing with Uniswap, we should automatically route transactions to this Curve pool when it would offer the most financially beneficial outcome for the user.

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/721
