### ISSUE TITLE
Coinbase Wallet Connection Option

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#634]
Coinbase Wallet is naturally supported in our DApp because it works with the same injected connector as MetaMask. In my experience, both of them connect automatically when "Connect" is clicked. This is different from the desktop version of MetaMask, which waits for the user to choose the MetaMask button from the listed options before connecting. As a result, there likely isn't a scenario where a user would actually click a "Coinbase Wallet" button within the mobile app. However, we should add a button basically advertising the fact that Coinbase Wallet is supported.

- [ ] Add a button to the [LoginWidget](https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/components/LoginWidget.js) using [the icon that I recently committed](https://github.com/OriginProtocol/origin-dollar/commit/d7b5f984250393284874f873cd0dabbb06a0540f) with the text "Coinbase Wallet".
- [ ] Arrange the buttons as follows: MetaMask, Ledger, Coinbase Wallet, WalletConnect, MEW wallet.
- [ ] Wire the button up to the same injected connector as MetaMask.

**Comment by micahalcorn** [comment]
Now that Coinbase Wallet has a browser extension, we can treat it just like we do MetaMask. I've updated the preceding comment accordingly.

One issue, however, is that both MetaMask and Coinbase Wallet prompts will appear if both are installed and a user clicks "MetaMask" **or** "Coinnbase Wallet". If there's a way to treat them differently, that would be a bonus. I don't think it's a big deal though because users who have both installed would likely see the same behavior on most other DApps.

**Comment by joshfraser** [comment]
It might be worth figuring out how we can support Brave wallet while we're at it.

**Comment by micahalcorn** [comment]
> It might be worth figuring out how we can support Brave wallet while we're at it.

Brave's built-in wallet works for me out of the box. It's the same concern that we have with Coinbase right now. You just click the MetaMask button and the same connector works. We might be able to identify that it's Brave's MetaMask fork rather than the browser extension and show a different button in that case. But it may get messy because Brave also has a config option for choosing whether to user their wallet or MetaMask when they're both enabled.

**Comment by calvintoes** [comment]
https://github.com/OriginProtocol/origin-dollar/pull/838

**Comment by franckc** [comment]
For the record, draft PR #838 could be useful starting point to look for the whoever works on this issue...

**Comment by sparrowDom** [comment]
Done via: https://github.com/OriginProtocol/origin-dollar/pull/909 thanks to @pedrotmr
