### ISSUE TITLE
Inaccurate Mix Breakdown

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#650]
37.34+55.9+29.53=122.77 (not 122.16 nor 121.55) 😕

<img width="628" alt="Screen Shot 2021-08-21 at 9 07 07 AM" src="https://user-images.githubusercontent.com/273937/130327987-be0b0e83-6b37-4f5d-9451-40bfdf7faa61.png">

**Comment by micahalcorn** [comment]
Based on [a recent test transaction](https://etherscan.io/tx/0xbed7a1df35248511b6b9a37a429b7adc6403c3d2c2c2bfeb540f34c79ac6b96c), I'm fairly certain that it's the sum that is incorrect and the per-stablecoin amounts are accurate.

**Comment by sparrowDom** [comment]
Fixed via: https://github.com/OriginProtocol/origin-dollar/pull/680
