### ISSUE TITLE
Pending Transaction Sorting

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#651]
In this example, I submitted the DAI transaction first, followed by the USDC transaction, and then the USDT approval last. They should be sorted in the reverse order of what is shown here (USDT on top, DAI on bottom).

<img width="280" alt="Screen Shot 2021-08-21 at 9 18 03 AM" src="https://user-images.githubusercontent.com/273937/130328275-569fff1c-d8b7-4a6a-83b0-61b5003c6744.png">

**Comment by jkaihsu** [comment]
This doesn't seem like an issue as it's sorting as expected. Discussed over discord with @sparrowDom, the side transactions are going way, so this seems to irrelevant.

**Comment by micahalcorn** [comment]
> This doesn't seem like an issue as it's sorting as expected. Discussed over discord with @sparrowDom, the side transactions are going way, so this seems to irrelevant.

Thanks, we haven't officially decided to remove these, but it has been discussed a few times. I'll reopen this if I'm able to reproduce it in the future.
