### ISSUE TITLE
Max Including Dust

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#652]
If I use the "Max" link, I expect all of that particular currency to be used. It's okay to truncate the input for display purposes, but the remainder should be included in the transaction so that I'm not left with some stablecoin dust.

**Comment by Michael1104Smith** [comment]
Where is "Max" link?

**Comment by micahalcorn** [comment]
<img width="169" alt="Screen Shot 2021-09-28 at 7 31 27 AM" src="https://user-images.githubusercontent.com/273937/135107999-d020df5d-373f-4a86-af3b-5f5a210e1bc9.png">

If I click "Max" and submit this transaction, it will swap 151.552942 DAI but my balance is currently 151.552942421692815265 DAI. I don't want to be left with 0.000000421692815265 DAI after the swap.

**Comment by Michael1104Smith** [comment]
I have done it and sent "commit" request.

**Comment by franckc** [comment]
@Michael1104Smith It does not look like you are actively working on this issue so un-assigning it....

**Comment by rolandpo** [comment]
done in #977
