### ISSUE TITLE
No Estimate Received on Unsupported Contracts

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#653]
When a contract is "Unsupported", its corresponding "Est. received" should be "-" instead of "0.00" to match the other two columns.

<img width="617" alt="Screen Shot 2021-08-21 at 9 35 43 AM" src="https://user-images.githubusercontent.com/273937/130328751-1e87315c-a0ac-4c26-8e23-b5bd7ec973c0.png">

**Comment by rolandpo** [comment]
done in #977
