### ISSUE TITLE
Number/Input Flipping UX

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#655]
There's one slight change I was recommending, but it's very minor. Currently, the bottom known value moves to the top when flipping (it follows the corresponding currency). But it also remains intact in the bottom field prior to the new calculation. I was expecting the top value to follow the flip and be moved into the bottom field. Again, it's not a big deal because the value will quickly be replaced but it caused me to get confused for a second.

**Edit**
Slightly different behavior observed and noted in https://github.com/OriginProtocol/origin-dollar/pull/958#issuecomment-1081462927 🤔

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/958
