### ISSUE TITLE
Configurable Gas Price

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#657]
<img width="425" alt="Screen Shot 2021-08-21 at 12 51 49 PM" src="https://user-images.githubusercontent.com/273937/130333375-e6265776-862a-4eac-be68-b9928b7bf3bb.png">

<img width="679" alt="Screen Shot 2021-08-21 at 12 50 54 PM" src="https://user-images.githubusercontent.com/273937/130333379-108f3337-7eff-4d0c-91e6-213f8385cf4d.png">

**Comment by sparrowDom** [comment]
PR for this issue: https://github.com/OriginProtocol/origin-dollar/pull/758
