### ISSUE TITLE
Contract Selection Override

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#659]
Make it possible for a user to choose which contract her transaction is routed through. She may already have an allowance granted for the Uniswap contract or she may trust it more than our contracts. In the event that the default selection is only slightly "better" than another option, it's reasonable to expect the user to want to switch to her preference and still submit the transaction through our DApp.

We currently support this for testing purposes by running the following command in the JS console:
```js
localStorage.setItem('override_best_tx_route', 'true')
```
We should probably take some time to confirm how we want the UX to work in this case before we enable it by default.

**Comment by sparrowDom** [comment]
Done
