### ISSUE TITLE
Approval/Swap Contract Mismatch

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#660]
We don't currently allow users to [override the default contract selection](https://github.com/OriginProtocol/origin-dollar/issues/659). However, I noticed when testing that there's an issue where the selection is not remembered between granting an allowance and submitting the transaction.

**Steps to reproduce**
- Have not granted DAI allowance to Uniswap
- Queue up a transaction involving a small DAI swap to OUSD
- See OUSD Swap as the default contract selection
- Click Uniswap to override the contract selection
- Click Swap
- Be prompted to grant approval to the contract
- Click Approve
- Submit the Uniswap allowance transaction
- See the approval confirmed for the Uniswap contract
- Click Swap
- See the transaction go through the OUSD Swap contract

**Comment by micahalcorn** [comment]
I think this happens because the DApp reruns the calculation periodically. So it updates the selection while I'm waiting for the allowance to get approved. Basically, when refreshing the calculation, it should respect my selection (whether an allowance is in progress or not).

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/739
