### ISSUE TITLE
Two Decimals on Blur

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#661]
I would vote for updating this input field to "123.00" when the field is blurred. We allow up to six decimal places on the input field and we should _not_ round that down to two places. But I do think it's nice for each value to at least be that precise since we're dealing in USD terms.

<img width="611" alt="Screen Shot 2021-08-21 at 3 58 35 PM" src="https://user-images.githubusercontent.com/273937/130336829-eb64b3c2-2294-4d52-a58c-07251c54b41d.png">

**PR for issue:** https://github.com/OriginProtocol/origin-dollar/pull/737

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/737
