### ISSUE TITLE
Q: Fixed daily schedule for rebases?

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#670]
While allowing people to buy OUSD on exchanges is good, there's an even bigger expansion of possible user base for OUSD when users can earn yield while on the centralized exchange. In order for this to happen, the exchange must support a rebasing token.

Rebasing support isn't a trivial thing to add for an exchange that's not already designed for it. Current exchanges are fairly  ugly in the way they handle rebasing for AMPL, in that they shutdown trading for an interval around the rebase time each day, and then adjust accounts balances afterwords before unpausing trading.

Kucoin, who lists OUSD, ended up skipping the rebasing support, and using a separate staking system to get yield.

## Pros

If we switched to a scheduled once a day rebase for OUSD, we would:

1. Make OUSD work in exchanges' current code bases for rebasing tokens, considerably increasing the number of exchanges likely to support OUSD yield.
2. Give users a predictable and regular time when they know their account balances will go up.
3. Reduce gas costs on user operations, since rebases no longer happen on the transacting user's gas.

All of these could be quite useful in increasing adoption.

## Cons

We'll need to make the contract code change to rebasing add the time based restriction. Contract code requires work.

We'll need to handle the actual calling of the rebasing. Chainlink Keeper, Andre's Keeper, or roll our own and use Flashbots. We'd also probably combine this with selling rewards tokens, that the automated process sells tokens, then rebases.

One concern with a predictable rebasing time is that yield thieves could purchase OUSD right before the rebase, then sell the large amount right after. The redeem fee on OUSD already prevents doing this using large mint's / redeems as well as the largish Uniswap v2 fee. We'll need to scenario out what happens with the cheeper fee on Uniswap V3. We'll also want to investigate how the AMPL ecosystem and AAVE atoken markets handle this.

3. We need insure that gaming that will result from a predictable rebase time will be limited

## Implementation questions:

Ten minute window for rebases? We're wanting to balance being easy to get the transaction through, with shortening the trading stop window.

Fund with the OUSD trustee contract?

What runs this? Chainlink Keeper, Andre's Keeper, or roll our own and use Flashbots.

**Comment by joshfraser** [comment]
@coleman415 On the business front, it would be good for us to check in with some of the exchanges that have integrated AMPL to double-check that they actually prefer daily rebasing. Most of AMPL's trading volume comes from DEX's and we're already listed on KuCoin and VirgoX, but it would be worth asking the other exchanges that have integrated AMPL (FTX, Gate, Bitfinex, Flybit, and MEXC) whether having a fixed scheduled would make it easier for us to get listed.

**Comment by joshfraser** [comment]
In an ideal world, the code would allow the rebase function to be called exactly once after midnight UTC and the exchanges would watch for that event to be fired as the signal that it's safe to update balances and restart trading. That way trading would stop for a few blocks instead of 10 mins.

I've been very impressed with the team at Chainlink and would love for us to deepen that relationship. It would be great to get closer to Andre as well. It really comes down to which one is a better fit from a technical perspective, and how we're going to pay the keepers. I don't see any advantage to us rolling it ourselves.

**Comment by KurogeWashu** [comment]
I would think a reward system with a base amount and variable amount would be good to incentivize more active participants at triggering the rebases. This would help in the case that users want to redeem OUSD, but a rebase hasn't occurred, then a rebase would occur before the transfer occurs. 
https://docs.makerdao.com/smart-contract-modules/dog-and-clipper-detailed-documentation#liquidation-incentive-mechanism
https://forum.makerdao.com/t/liquidations-2-0-technical-summary/4632

Some Cons:
Having exchanges earn yield on OUSD can incentivize exchanges to list OUSD, but requiring them to pause trading and award the yields to users may be an extra technical barrier of entry on their end.

Although yield thieves may not be profitable on-chain, it could be off-chain on CEX's - and this could impact peg stability. A simulation playground to test profitability of buying/selling large amounts before a rebase may be useful for clearer understanding.

**Comment by KurogeWashu** [comment]
To add onto the point of exchanges ultimately deciding on who owns the OUSD yield, this would further strengthen the argument of "not your keys, not your coins." Then this could encourage more users to withdraw and convert to on-chain active users.

**Comment by DanielVF** [comment]
We have moved to a minimum once a daily rebase via Chainlink Keepers, plus other possible rebases throughout the day.

I'm calling this a good enough answer to close this issue.
