### ISSUE TITLE
Network Switching Prompt

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#687]
As discovered by @franckc, DApps can initiate network switching. We may want to encourage a user to switch from Rinkeby to Mainnet, for example. However, unlike C.R.E.A.M.'s DApp, we should _not_ open a MetaMask prompt without first asking the user within the DApp interface. There should always be a direct connection between a user click and a MetaMask prompt.

<img width="353" alt="Screen_Shot_2021-08-25_at_9 56 25_AM" src="https://user-images.githubusercontent.com/273937/130837696-10c14501-6ef7-4bbb-9c7b-f8b9326e2635.png">

**Comment by KurogeWashu** [comment]
Decided a clickable button where it says "incorrect network" is most intuitive and least intrusive than adding directly into AccountListener.js

If there are other networks in addition to mainnet, like testnets, then I'd suggest individual buttons below "incorrect network" for each.

Also, being mindful of the red/green color-blind, a red dot is not informative enough that the network is incorrect.

**Comment by KurogeWashu** [comment]
Found another issue, currently the recent transactions section displays "Failed granting permission to move your OUSD" when an user attempts to create a transaction while on a wrong network. Should use this `import { isCorrectNetwork } from 'utils/web3'` before a tx is created, then popup the Network Switching Prompt. Will move the network prompt call into a helper function in util/web3.

**Comment by sparrowDom** [comment]
> Found another issue, currently the recent transactions section displays "Failed granting permission to move your OUSD" when an user attempts to create a transaction while on a wrong network. Should use this `import { isCorrectNetwork } from 'utils/web3'` before a tx is created, then popup the Network Switching Prompt. Will move the network prompt call into a helper function in util/web3.

That's a great idea. We don't focus heavily on other networks since it is deployed only to production. But still a nice to have.
