### ISSUE TITLE
Wrong Default Transaction Route

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#725]
As noted by @joshfraser in the staging environment, large numbers seem to cause the "worst" contract routing option to be chosen by default. In this example (from the production environment), the est received is significantly higher with Origin Vault than for Uniswap V3. While the gas estimate is also higher, it's not different enough to cause Uniswap to be the better option. When reproducing this, I confirmed that the `override_best_tx_route` was _not_ causing a prior override to keep Uniswap as the preferred option.

<img width="656" alt="Screen Shot 2021-08-31 at 5 30 08 PM" src="https://user-images.githubusercontent.com/273937/131593144-86683379-fa13-44a8-8a44-9c0ff1a4f433.png">

**Comment by joshfraser** [comment]
Also worth noting that the effective price is completely wrong as well.

**Comment by sparrowDom** [comment]
fixed via: https://github.com/OriginProtocol/origin-dollar/pull/727
