### ISSUE TITLE
Estimation liquidity check

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#728]
When selecting higher amounts than Uniswap or Curve available liquidity we should display an `Insufficient liquidity` error message instead of stopping the estimated price at available liquidity

<img width="643" alt="Screenshot 2021-09-01 at 21 04 38" src="https://user-images.githubusercontent.com/579910/131729227-e60661a7-b386-4327-9d46-af000521d280.png">

**Comment by rolandpo** [comment]
done in #1070
