### ISSUE TITLE
Clarity Around ERC-20 Approval Step

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#732]
We often hear from users who are confused by not receiving OUSD after submitting the approval transaction. Many people are either not familiar with the allowance concept or they're submitting the form quickly without noticing that the approval and swap are two different steps. I think we can help with this by doing something more like Uniswap and SushiSwap where there is a clear "1-2" sequence shown before the form is submitted at all.

**Uniswap: two buttons, "Swap" disabled until allowance is granted**

<img width="521" alt="Screen Shot 2021-09-06 at 7 38 45 AM" src="https://user-images.githubusercontent.com/273937/132234006-5b9bf83c-01f8-42e4-9dec-7f5f8eb5a485.png">

**SushiSwap: one "Approve" button, two-step sequence indicated below**

<img width="698" alt="Screen Shot 2021-09-06 at 7 39 05 AM" src="https://user-images.githubusercontent.com/273937/132234089-bdea3df7-2f25-4068-8c4b-4b336d122ec3.png">

**OUSD: single "Swap" button (same as when allowance already exists), conditional modal with approval sequence"**

<img width="574" alt="Screen Shot 2021-09-06 at 7 39 22 AM" src="https://user-images.githubusercontent.com/273937/132234296-90424ae1-d593-4c93-926b-747e76516119.png">
<img width="572" alt="Screen Shot 2021-09-06 at 7 39 36 AM" src="https://user-images.githubusercontent.com/273937/132234384-d0e98504-665b-4425-bc39-f48a90e39544.png">
<img width="576" alt="Screen Shot 2021-09-06 at 7 48 30 AM" src="https://user-images.githubusercontent.com/273937/132234564-8c97b1a7-8c4a-4d9f-8a09-70f3a06bb80d.png">

**Comment by sparrowDom** [comment]
Nice UX improvement. If I had to vote, I would go for the Uniswap variant (a bit more user friendly for my eyes)

**Comment by micahalcorn** [comment]
We might also want to incorporate the cost of allowance approval into the swap. For smaller amounts, it probably makes sense for some users to have their transactions routed through Uniswap instead of OUSD Swap even if the slippage or gas cost on the actual swap transaction is higher. We could also indicate on the table which contracts involve two transactions with some small icon.

**Comment by joshfraser** [comment]
I like this idea. We could put a little tooltip on the icon explaining why they sometimes need to do 2 transactions.

**Comment by sparrowDom** [comment]
+ 1. More transparency always seems like a good idea.

**Comment by micahalcorn** [comment]
Here's some guidance from @auregimon following the Uniswap style:

<img width="609" alt="Screen_Shot_2021-09-13_at_9 31 51_AM" src="https://user-images.githubusercontent.com/273937/134695367-bf7782fb-f19f-4bf0-9ba4-e9a864d98a6b.png">
<img width="603" alt="Screen_Shot_2021-09-13_at_9 31 56_AM" src="https://user-images.githubusercontent.com/273937/134695379-266826af-7fa2-4438-b3c1-22edbdddd9be.png">
<img width="599" alt="Screen_Shot_2021-09-13_at_9 32 01_AM" src="https://user-images.githubusercontent.com/273937/134695396-c357abe7-8440-4c10-8c2c-00e3944b6d89.png">

However, it's worth noting that this is a bit redundant with the info feed on the right side where we have a card for each on-chain transaction, including approvals:

<img width="286" alt="Screen Shot 2021-09-24 at 7 54 46 AM" src="https://user-images.githubusercontent.com/273937/134695887-756f94f0-243d-4b6a-9452-021799061feb.png">

It might be time to consider removing that thing altogether. I would get more value out of a proper [transaction history](https://github.com/OriginProtocol/origin-dollar/issues/62), although that would probably belong on a different screen accessible by some navigation.

For now, we can just make the changes to the approval experience as described above since our existing modal already has a little redundant spinner.

**Comment by soft2dev** [comment]
Would you share a tooltip message example as well, if you have any idea?

**Comment by micahalcorn** [comment]
> Would you share a tooltip message example as well, if you have any idea?

For the one on that button:

> You must give the {name} smart contract permission to move your {token}. This only needs to be done once for each token.

The name and token should be dynamic based on which contract the transaction is being routed through and which input currency requires approval. So an example would be "Uniswap" and "DAI".

**Comment by soft2dev** [comment]
@micahalcorn when the currently selected swap path & coin don't have enough allowance, Allow button should be hidden or disabled?

**Comment by sparrowDom** [comment]
Hey sorry for not outlining the states in more verbose manner. Here is the expected behaviour and will let @micahalcorn correct me if needed:

- Empty input state (no swap coin amount or swap amount is 0 and no swap path selected) -> show only disabled Swap button
- Loading state: beast swap route is being determined -> show only disabled Swap button
- Swap routes calculated and best route selected (either by user or automatic) 
  - allowance for the coin to be used by the swap and selected swap route not sufficient: -> show disabled Swap button and show approve button containing the Approve CTA for the mentioned combination of coin and swap route
  - allowance for the coin sufficient -> show only enabled Swap button 

When user clicks on the allowance button: 
- text on allowance button changes to: "Waiting for you to confirm..." as long as user doesn't confirm the transaction (button is still enabled but click doesn't do anything)
- when user confirms transaction text changes to "Processing transaction..." - as in the image above (button is still enabled but click doesn't do anything)
- when that transaction is mined the button does to disabled state and text says "Transaction complete" - as in the image above
- When swap routes recalculate again (user inputs new value) the behaviour of the approve button resets to initial states in this comment

**Comment by micahalcorn** [comment]
Thanks @sparrowDom 👍 Here are a couple of comments:

> allowance for the coin sufficient -> show only enabled Swap button

This wouldn't strictly be the case since we wouldn't want the button to disappear immediately after an approval transaction is submitted and confirmed.

> When user clicks on the allowance button:

I don't love the idea of a button being enabled but it not doing anything when clicked. But we also don't want it to be as ghosted as those disabled grey buttons. I suppose it's fine to keep the same blue styling but just switch the cursor to `default` or something to indicate that it isn't clickable.

**Comment by micahalcorn** [comment]
@sparrowDom @soft2dev I also wouldn't mind simplifying this and leaving the button text alone while we still have the info feed on the right redundantly showing the in-progress transactions (as I mentioned above). It's not the worst thing to be able to see what the top button is for after submitting the approval transaction. With the text changing, you lose that context.

**Comment by soft2dev** [comment]
@sparrowDom Is there anything to be updated in the scenario?

**Comment by micahalcorn** [comment]
> @sparrowDom Is there anything to be updated in the scenario?

Were you still working on this project? I didn't quite understand your question for @sparrowDom and didn't know what else you needed to clarify.

**Comment by sparrowDom** [comment]
Great job @rolandpo done via: https://github.com/OriginProtocol/origin-dollar/pull/958
