### ISSUE TITLE
Determine how exit fees on strategies should be handled

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#75]
Our initial strategy may be a yVault with a 0.5% exit fee that is charged under some (not all) scenarios. This could result in users seeing a decrease in their OUSD balance which is not ideal. Some ideas:

- We keep a reserve buffer to handle withdrawals so we most likely never have to withdraw from the yVault. e.g. 10% assets held liquid, 90% in yVault.
- We have a combination of strategies, that allow us to liquidate without fees. E.g. 20% Compound, 80% yVault. All withdrawals come out of the Compound strategy.
- Detect if the yVault will charge an exit fee and only allow the withdrawal if it won't (yuck).

**Comment by franckc** [comment]
Do we still need to keep this open or can we close this and just use #312 to discuss this area of the product?

**Comment by DanielVF** [comment]
Let's discuss this when we are implementing a specific strategy that needs this.
