### ISSUE TITLE
APY Discrepancy

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#752]
It looks like the analytics pages are consistently showing an APY four basis points lower than the DApp is. Perhaps there's some rounding difference in a calculation somewhere.

https://www.loom.com/share/aa812453de8c4f64a4effeca5bf7a4fa

**Comment by Michael1104Smith** [comment]
I tried to fix this issue but first of all, I should install this project into my local.
I can see some issues from it.
Can you install this project into your local?

**Comment by Michael1104Smith** [comment]
I have fixed that issue.
old codes:        const apy = aprToApy(parseFloat(json.apr), 7)
new codes:      const apy = aprToApy(parseFloat(json.apr), 30)
and working

**Comment by micahalcorn** [comment]
This now seems to be 12 basis points off, which appears more significant when one number is in the 20s and the other is in the 19s.

**Comment by franckc** [comment]
@Michael1104Smith It does not look like you are actively working on this issue so un-assigning it....

**Comment by micahalcorn** [comment]
Currently two basis points off when the APY is single digits ✌️
