### ISSUE TITLE
Onchain analytics

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#769]
We need a system that is able to process the onchain analytics data that is already present in [ousd-analytics](https://github.com/OriginProtocol/ousd-analytics) to extract KPIs we are interested in. Event listener is already ingesting most (if not all) of the required events, we need a supplementing algorithm that will: 
- be able to classify a transfer event as a swap / mint / redeem event
- be able to calculate OUSD balance in any point of time for a wallet

There should be a weekly / monthly cron job that will send KPI reports to all interested parties. 

KPIs to produce: 
- [x] Unique ethereum accounts holding OUSD + trend change
- [x] New Unique ethereum accounts holding OUSD + trend change
- [x] Unique ethereum accounts that were in possession of OUSD during the time interval + trend change
- [x] Unique ethereum accounts increasing their OUSD holding - because of new capital and not rebases + trend change
- [x] Unique ethereum accounts decreasing their OUSD holding - because of new capital and not rebases + trend change
- [ ] total token swaps value onchain
- [ ] total token swaps value on the dapp

P0 KPIs: 
- [x] Percentage of OUSD in Curve not earning yield
- [ ] Number of new OUSD holders not participating in Curve incentives
- [ ] Boost level

Additional remarks: 
- [ ] earnings through time would be useful for each account
- [x] what routers/contracts are being used to swap OUSD
- [x] dashboard and email would be useful

**Comment by micahalcorn** [comment]
Closing this for now 👏
