### ISSUE TITLE
Rescue COMP from old Compound strategy

### ISSUE THREAD

**Issue by tomlinton** [OriginProtocol/origin-dollar#776]
0xD5433168Ed0B1F7714819646606DB509D9d8EC1f is owed some COMP from Compound but at the time of writing these are unclaimable due to a Compound bug. This strategy will be removed but we should go back later and try and rescue these funds (if they are of an amount that makes it worthwhile).

**Comment by joshfraser** [comment]
https://api.compound.finance/api/v2/governance/comp/account?address=0xD5433168Ed0B1F7714819646606DB509D9d8EC1f

Looks like we have 8.84 COMP ($2,748.70 at today's value) waiting for us.

**Comment by DanielVF** [comment]
```
import requests
import json

total = 0.0
j = requests.get("https://api.compound.finance/api/v2/governance/comp/account?address=0xD5433168Ed0B1F7714819646606DB509D9d8EC1f").json()
for market in j['markets']:
  comp = float(market['comp_allocated'])-float(market['comp_distributed'])
  total+=comp
  print(comp)
print("----")
print(total)
```

**Comment by DanielVF** [comment]
Ahh. The comp transfer cancelation is because we are collecting on all markets, which includes the bugged markets. We can probably collect by just asking for our comp on the markets we are using.

**Comment by DanielVF** [comment]
Nope, still zeros out the transfer.
