### ISSUE TITLE
Account transaction indicator 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#81]
The least important part of this issue https://github.com/oplabs/origin-dollar/issues/26 transferred to a separate issue: 

**Wallet connected, correct network, transaction in progress:**

- Green spinner
- Truncated address as button text
- Short description of what's happening in dropdown (Converting to OUSD, Approving your DAI, etc)

**Comment by rolandpo** [comment]
Outdated
