### ISSUE TITLE
Transaction History Pagination

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#822]
Limit the initial display to the most recent 50 transactions. For the pagination behavior, we should probably go with whatever is easiest and quickest to implement (maybe an off-the-shelf library). My preference would be to have an explicit button rather than infinite scroll so that the footer remains accessible. I would also vote for just appending the next 50 rows rather than navigating from page 1 to 2, for example. It might also be nice to allow the user to specify how many rows to display (10, 50, 100, 500, etc) so that she can paginate faster if she's willing to wait for the data to load.

**Comment by sparrowDom** [comment]
hey sorry have sort of implemented a basic pagination before reading this ticket. Currently there are classic buttons at the bottom of the page - opposed to infinite scroll loading.

With infinite items loading, I am worried that it might slow down the browser if user would want to load the whole history - to the 60th page for example.

**Comment by micahalcorn** [comment]
Yeah, I think what you've done is great for now. My only complaint with the traditional pages is that I can't see the 10th transaction alongside the 11th transaction. But pages have benefits too, like the ability to jump to the oldest transaction with one click. Would it make sense to increase the number per page from 10 to say 50 or 100? When there are a bunch of rebases per day, I might not be able to see anything interesting until I get to the 3rd or 4th page.

**Comment by sparrowDom** [comment]
good point, let me increase it to 50. Closing this ticket for now... feel free to reopen if there are more things you would want to revisit
