### ISSUE TITLE
Some data not reset when wallet is disconnected

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#823]
Disconnecting your wallet in MetaMask resets your balance, but not your pending yield or lifetime earnings

<img width="1006" alt="Screen Shot 2021-11-15 at 11 27 41 PM" src="https://user-images.githubusercontent.com/982234/141918531-b53aeaa5-12f0-44a2-b477-1605ba22d609.png">

**Comment by micahalcorn** [comment]
I had the opposite experience today: my balance remained but the other two numbers were removed.

**Comment by talentdev0807** [comment]
This is working well on my side just have some delay
I think this comes from calling the apis asynchronously at the same time

**Comment by franckc** [comment]
@talentdev0807 Unassigned the issue since it does not look like you are working on it?
