### ISSUE TITLE
Gnosis Safe Icon broken on connect modal

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#824]
<img width="377" alt="Screen Shot 2021-11-15 at 11 35 07 PM" src="https://user-images.githubusercontent.com/982234/141921628-38d8a5b5-44f0-4fa7-80da-940bcf75a956.png">

**Comment by eulerbeat** [comment]
May I know where this dialog is from? I am facing a different one when connecting a wallet.

**Comment by rolandpo** [comment]
Outdated
