### ISSUE TITLE
Transaction History Timestamps

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#833]
Today, I found myself wanting to know when a particular yield event occurred. I can click through to Etherscan, but it would also be nice to be able to see the times and not just the dates on the historical events. This is particularly relevant when there are multiple rebases within a given day. And even though I can get the details from Etherscan, I have to convert UTC to my local timezone.

**Comment by velopace** [comment]
Fixed the issue: https://github.com/OriginProtocol/origin-dollar/pull/859
