### ISSUE TITLE
Aave Supply Alerts

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#841]
@mikeshultz is going to disable the supply alerts that we currently have for Aave v1 in our Discord **#ousd-bot** channel. We will want to add the alerts back once we're monitoring Aave v2.

**Comment by mikeshultz** [comment]
Specifically, we'll want to add v2 snapshotting, review any other events we might find of interest, and reenable the supply/borrow notifications.

Ref: https://github.com/OriginProtocol/ousd-analytics/pull/172

**Comment by franckc** [comment]
@sparrowDom Is this alert included in the new prometheus based monitoring/alerting system?

**Comment by sparrowDom** [comment]
Yes the amount that is available to borrow via Aave is now done with Grafana&Prometheus. No need for a separate system implementing this
