### ISSUE TITLE
Minor Improvements to Disconnected DApp State

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#851]
I couple of small things, one probably not controversial, and the other opinionated:

1) The numbers above Pending yield should match what's above Balance and Lifetime earnings when there's no account connected ("--.--" vs "0.00").

2) At least a couple of us would prefer that "History" always be present in the nav rather than being conditioned based on the account connection state. As a frequent visitor to the DApp who found myself logged out of MetaMask with the browser tab still open, it was odd for me to be missing a nav item that I regularly click.

Regarding 2, someone had previously mentioned that we would need to figure out the zero state for that page. I would think we could start with some simple text like we have for the loading state, and then eventually improve both to be more presentable.

<img width="298" alt="Screen Shot 2021-12-03 at 10 45 03 PM" src="https://user-images.githubusercontent.com/273937/144700995-e2b8c978-a79e-4da9-b4ad-37b7ef91059f.png">

Maybe "No OUSD transactions" 🤔

**Comment by velopace** [comment]
Fixed the issue: https://github.com/OriginProtocol/origin-dollar/pull/852

**Comment by micahalcorn** [comment]
> Fixed the issue: #852

Thanks for this. 👍
