### ISSUE TITLE
Multiple Reward Token Harvesting

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#857]
Make it possible for strategies to sell more than one type of reward token. This will be used initially for our Convex strategy, which earns CRV and CVX but is currently limited to harvesting CRV only.

**Comment by franckc** [comment]
@sparrowDom This is implemented, right? 
https://github.com/OriginProtocol/origin-dollar/blob/0d30731f7167da0f410db469baaaf74897408cf6/contracts/contracts/harvest/Harvester.sol#L343

Closing - pleas re-open if I'm missing something...

**Comment by sparrowDom** [comment]
yup, thanks!
