### ISSUE TITLE
Allowance-Aware Cost Estimates

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#864]
As discussed in https://github.com/OriginProtocol/origin-dollar/issues/732#issuecomment-917434051, we should update the transaction routing calculator to include the cost of allowances.

**Scenario**
As an avid Curve user, I have already granted allowances for their contracts to move my DAI, USDC, and USDT and I have not done the same for Uniswap. If I come to the DApp for the first time and want to swap DAI for OUSD, it might make more sense for me to use Curve instead of Uniswap even if the price is slightly better on Uniswap. When calculating which one is more economically advantageous, the DApp should consider the gas cost of the extra allowance.

We should probably also add a visual indicator to the table of contract options when they involve different numbers of transactions. If they would all require two transactions, then we may not want to show anything special. But if Curve already has an allowance and all the others require it, then we might want to flag it in a positive way or flag the others in a negative way.

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/930
