### ISSUE TITLE
Automated DApp Deployments

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#874]
As suggested by @sparrowDom ⚙️ In the scope of this ticket we want to achieve: 
- (semi) automatic deployment of the dapp to IPFS
- automatic deployment of the dapp by pushing to a `stable` branch
- show this prompt in Brave browser:
<img width="793" alt="Screen_Shot_2022-02-18_at_11 05 33_AM" src="https://user-images.githubusercontent.com/579910/154738904-9446e059-9256-4f80-966c-b2841d64532b.png">

**Comment by sparrowDom** [comment]
Done via https://github.com/OriginProtocol/origin-dollar/pull/922, https://github.com/OriginProtocol/origin-dollar/pull/921, https://github.com/OriginProtocol/origin-dollar/pull/910
