### ISSUE TITLE
Decentralized Harvest Triggers

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#875]
Provide an incentive for anyone to trigger the yield realization and receive a reward in return. We'll need to decide how much of an interface we want to create for this and where to put it. This will also involve moving the harvest logic out of the vault.

**Comment by franckc** [comment]
@sparrowDom Can we close this?

**Comment by sparrowDom** [comment]
This has been done for harvest but not yet for rebase. Opening it for now

**Comment by micahalcorn** [comment]
I filed https://github.com/OriginProtocol/origin-dollar/issues/1229 and will close this one since the main project was completed.
