### ISSUE TITLE
OUSD wrapper contract

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-dollar#876]
We have had several requests for an OUSD wrapper contract. This would provide a non-rebasing version of OUSD that keeps a fixed quantity without rebasing, and yet can be unwrapped to get an ever increasing amount of OUSD.

1. Tax benefits and simplifications. It is possible that in some jurisdictions, each rebase creates a separate taxable event. Also, by wrapping, in certain jurisdictions, yield is taxed at long term rates, rather than the much higher short term rates.

2. This allows off the shelf cross chain bridges to work with OUSD. While this bridged wOUSD would not have the 1-1 stablecoin property that OUSD has, it would still allow cross chain users to use OUSD as an investment vehicle, and to get it for cheap rates.

3. This provides an easy way to build yield bearing OUSD into other projects as a money lego.

In my view, there is little downside to a wrapped version of OUSD. The complexity is small. This empowers users a bit with more options and places to use OUSD. There's a potential supply increase from doing this. And if we can bridge to alt chains, even if it's wrapped, then that's quite a win.

**Comment by DanielVF** [comment]
Wrapped-AMPL:

- https://github.com/ampleforth/ampleforth-contracts/blob/master/contracts/WAMPL.sol

**Comment by DanielVF** [comment]
Contract that can wrap ERC20's without an intermediate approval step.
* https://github.com/alcueca/ERC20Wrapper/blob/main/contracts/ERC20Wrapper.sol

**Comment by DanielVF** [comment]
OHM wrapper. Bit too complicated:

- https://etherscan.io/address/0x0ab87046fBb341D058F17CBC4c1133F25a20a52f#code

**Comment by joshfraser** [comment]
I'm not necessarily opposed, but the biggest potential downside I see is splintering our liquidity. Our top preference is for exchanges to just list OUSD. It's also a ton of work to get a new token integrated everywhere (wallets, exchanges, etc).

**Comment by sparrowDom** [comment]
If I get this correctly this proposal wraps the 1 OUSD to 1 wOUSD. And redeems it 1 for 1 as well? Opting out of rebasing profits while the token is wrapped. 

Or was the idea that the wrapping contracts opts in for rebases, wraps the token, and once the user unwraps it effectively catches up on all of the rebases that have happened in the meantime while the token was wrapped.

**Comment by joshfraser** [comment]
@sparrowDom the latter, I believe. Interesting to look at wAMPL which is trading at $14.48 vs. AMPL at $0.74 right now.

https://www.coingecko.com/en/coins/ampleforth
https://www.coingecko.com/en/coins/wrapped-ampleforth

**Comment by DanielVF** [comment]
The idea is that you should end up with the same amount of OUSD  in your wallet if you just hold OUSD or if you:

- Wrap OUSD to wOUSD
- Rebases happen
- Unwrap wOUSD

If we had made a wOUSD at the start of OUSD, 1 wOUSD should unwrap to 1.22 OUSD.

**Comment by sparrowDom** [comment]
Cool that makes sense.

Don't completely have the details down, but I imagine one way this could work on another chain besides having an ERC20 wOUSD that would be part of the cross chain bridge, there would possibly be another ERC20 OUSD contract (on that other chain) that would be sort of an interface to the wOUSD contract. Users would be doing ERC20 OUSD operations and under the hood that would be moving the wOUSD tokens.

**Comment by DanielVF** [comment]
The new standard for tokenized vaults might be handy to use:

https://eips.ethereum.org/EIPS/eip-4626

In fact, a reference implementation might just work off the shelf.

https://github.com/Rari-Capital/solmate/pull/88

**Comment by franckc** [comment]
Would it be worth validating that ERC4626.sol would work for OUSD by writing a few unit tests for it? Might be a good task for an external contributor?
CC @DanielVF @sparrowDom @micahalcorn @joshfraser for input

**Comment by DanielVF** [comment]
Yes, we absolutely need to validate it.
