### ISSUE TITLE
Separate harvesting into a separate contract

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#877]
Main thing to accomplish is to separate the harvesting logic into a separate contract from the VaultAdmin contract.  There are security benefits to this, since this will greatly decrease the frequency at which we upgrade the Vault contract. Other things that need to be achieved in this issue: 
- make harvestAndSwap publicly callable function that anyone can call. Caller gets 1% of the rebase value. This should provide economic incentive for users to make harvestAndSwap calls
- the 1% revenue share threshold should be configurable by the governor and configurable per strategy
- slippage checks when swapping should also be configurable
- to prevent collisions and gas wastage, we should check early if 2 rebases are called too closely together and stop execution of the second one. 
- add re-entrancy modifier to all public functions
- the new harvester contract needs to be upgradeable

**Comment by franckc** [comment]
Closing since the harvester was implemented and deployed to mainnet. Please re-open if there is anything left to be implemented...
