### ISSUE TITLE
Support Uniswap V3 for reward token swapping

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#880]
Once https://github.com/OriginProtocol/origin-dollar/issues/877  is done we want to add a possibility to swap the reward tokens by using UniswapV3. Because of concentrated liquidity and sometimes larger liquidity pools it should in some cases result in lower slippage. See [liquidity research here](https://vote.originprotocol.com/#/proposal/0x5f2d4819c99660e8b0c5308aa1fbe0fcd37c07bdbf38f86274a5073f6ce7fd6a).

**Comment by franckc** [comment]
@sparrowDom Seems like this could be a "good first issue" for an experience solidity/defi engineer? Marking it as such, let me know if you have any thoughts...

**Comment by sparrowDom** [comment]
Yup agreed thanks

**Comment by micahalcorn** [comment]
@ssfanist is this something you're actively working on? If not, we should remove the assignment so that someone else can pick it up.

**Comment by DanielVF** [comment]
PR on this up here:

https://github.com/OriginProtocol/origin-dollar/pull/927

I don't think we need further work on this right now.
