### ISSUE TITLE
Support delegation for Snapshot voting

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#889]
The goal is to add support for [delegation](https://docs.snapshot.org/guides/delegation) to our [snapshot](https://snapshot.org/#/origingov.eth).

We wrote a [custom plugin](https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/ogn/index.ts) for snapshot that looks at an average OGN and Staked OGN balance in the last 30 days.

It's important to note that a plugin must not make more than 5 external requests to fetch data. See the [plugin checklist](https://github.com/snapshot-labs/snapshot.js/issues/212). Our current plugin already makes 4 requests. So the implementation should be careful as to not making more than 1 additional request to fetch the delegation data.

A suggestion for the changes to the plugin would be for each address to:
  - check if the wallet delegated their vote by calling the delegation contract
  - if the vote was delegated, add the OGN/Staked balances to the delegate rather than the holder.

**Comment by sparrowDom** [comment]
Have tested with the latest token split vote using the account I have delegated OGN to and it included the delegated OGN.
