### ISSUE TITLE
1% Harvester reward split: Do we rebase?

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#890]
The main question is do we rebase when calling harvestAndSwap or not? (pertains to this PR: https://github.com/OriginProtocol/origin-dollar/pull/869)

We have started this discussion on Discord and most of the participants were for the option of leaving rebase out of the new Harvesting contract `harvestAndSwap` function that will be publicly callable.

Things to consider: 
- calling rebase is fairly expensive ~450k gas, and people/bots will call harvest and swap less frequently if it also rebases
- without calling rebase the balance of users doesn't actually go up. It stays in the "pending yield" area
- if we don't call `rebase` when harvesting we still need active keepers to periodically call it.
- `mint` & `redeem` over 1k trigger rebase, but swapping coin on Uniswap, Curve etc. wont trigger it

**My take on it:**
Constantly calling rebase is too expensive, then again if we don't automatically trigger it we haven't really made our system more decentralised - we still rely on Keepers to rebase. To try to get the best of both worlds: have a Harvester configurable USDT threshold that gets triggered once enough USDT gets swapped and sent to the Vault. Quick test estimation shows (storing a uint256) this would cost an extra of ~22k per `harvestAndSwap`. When that threshold is reached it would obviously cost an extra 450k gas and we can configure how often that happens. 

Downside of this approach is that it doesn't scale well with TVL moving up/down.

**Comment by tomlinton** [comment]
I like keeping them separate and figuring out how we incentivise the call of each. I've always found threshold based things a little bit awkward and hard to reason about (I've put several in over time I think 🤣).

Having said that, I haven't figured out a good way to incentivise rebase calls beyond using a Keeper.

**Comment by joshfraser** [comment]
My vote is to leave it out for now, but for us to keep an open mind towards adding it back later if needed.

**Comment by micahalcorn** [comment]
I assumed we would introduce a similar incentive for calling rebase but that was a little hand-wavy. I would vote for separating the two concerns since the harvesters aren't necessarily going to be OUSD holders. But I also agree that we should be open to reintroducing the rebase in the future. It could potentially be an option for the caller to get a greater incentive or we might decide to force it onto everyone.

**Comment by DanielVF** [comment]
I currently favor disconnecting rebasing from harvesting. It roughly doubles our cost for selling reward tokens. Reducing slippage would be on top of that. I don't think there's much user value to more than daily rebases. If our rebases were cheap, I'd go for rebases with harvest. But they aren't cheap.

Currently we are rebasing once a day. If we disconnect the harvesting from the rebasing, we'll still be rebasing once a day. So we won't be getting any worse than we currently are.

Just to make the two arguments for the other side though:

1. Rebase on harvest instantly incentives rebasing. The schedule may be erratic and unpredictable, some days may not have a rebase, but rebases will happen.
2. As OUSD TLV grows, the dollar size yield rebased will increase each day. Having rebases happening multiple times a day means that individual rebases are smaller, which could prevent someone from finding a way to profit from them. (Counter argument is that as TLV grows, the amount of OUSD required to get a certain percentage of the rebase also grows.)

**Comment by sparrowDom** [comment]
Ok leaving it out for now until we can get to a solution that is more favourable. Thanks everyone for chipping in so quickly.
