### ISSUE TITLE
Best route calculation upgrade 

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#892]
When doing a best swap calculation for the user we don't yet take into account which contracts have already been approved and which not. The extra approval call could alter the order of most favourable swaps.

**Comment by micahalcorn** [comment]
Sounds like https://github.com/OriginProtocol/origin-dollar/issues/864 😛

**Comment by sparrowDom** [comment]
haha yes, I need to use search before making new tickets :)

closing as duplicate of: https://github.com/OriginProtocol/origin-dollar/issues/864
