### ISSUE TITLE
Harvester gas optimisation

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#901]
There are a few ways we could gas optimise the Harvester: 
 - [ ] As pointed out in [this comment](https://github.com/OriginProtocol/origin-dollar/pull/900#pullrequestreview-880896475) we could perform only 1 ERC20 transfer when no one is to claim the 1% (configurable) harvesting reward
 - [ ] Calling harvest on Convex strategy results in selling of CVX and CRV and thus does 2x USDT transfers as is necessary. Find an elegant way to optimise this.

**Comment by franckc** [comment]
@sparrowDom This could be a "good first issue" for an experienced solidity/defi engineer? Marking it as such, please lmk any comments...

**Comment by sparrowDom** [comment]
Yup a nice one 👍

**Comment by ssfanist** [comment]
@sparrowDom I just roughly checked this issue.
So first optimization discussed [here](https://github.com/OriginProtocol/origin-dollar/pull/900#pullrequestreview-880896475) is super easy - just to check address consistency and merge/unmerge the transfer.
But about the second optimization mentioned above, I'd like to hear more details.

**Comment by sparrowDom** [comment]
Regarding the second optimisation -> the rewards strategy can have multiple reward coins - like Convex strategy has CRV & CVX. When calling harvest and selling reward tokens `_swap` function is called twice - once for each of the reward tokens. Which means that any USDT transfers within `swap` function will happen twice. This could be optimised in a way where swap function would only do the swapping of the reward tokens while the ERC20 transfers of USDT would happen once all the reward tokens have been swapped. 

The challenge here will probably be finding an elegant solution to this problem.

**Comment by DanielVF** [comment]
My apologies for not spotting this issue earlier and commenting it on it. 

I do not think we need to gas optimize the case of not transferring twice when sending all proceeds to the vault. This way of calling may only happen only a few times a year - only when we completely pull out of a strategy. The extra 20K gas saved or so for us in those times will be negligible. I think the trade off in increased code code complexity is not worth it - I'd much rather have the code be clear and short.

**Comment by sparrowDom** [comment]
@DanielVF doesn't it happen each time we are harvesting Convex? Granted we have no funds in there right now

**Comment by sparrowDom** [comment]
Closing for now.
