### ISSUE TITLE
Redeem gas estimate failing

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#906]
When redeeming a mix of coins (using the Origin Vault) a large redeem is failing at the ether block: 14212248

PR: https://github.com/OriginProtocol/origin-dollar/pull/924/files

**Comment by DanielVF** [comment]
Was this because there was not enough funds in the default strategies?

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/924
