### ISSUE TITLE
Exit Fee on Redeem

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#92]
Add the framework for an exit fee that would be paid when OUSD is redeemed for stablecoins. This fee can help offset the risk of stablecoin price fluctuations and can be set via governance. Once a governance token is established, the fee could also accrue to holders of that token.

**Comment by micahalcorn** [comment]
The reality of this exit fee has recently sunk in for me. It's particularly problematic at our low APY, but it will remain an issue for good actors even as our APY increases.

Suppose our APY is consistently 13% (roughly equal to yyCRV right now). With an exit fee of 0.5%, the break-even point for a minter is two weeks (not including gas costs). This serves as a de-facto lockup. It's not a great experience to mint OUSD and then realize that you're unable to profitably convert back to other stablecoins unless you wait a while or use an exchange/AMM.

This should be a contributing factor as we reconsider our oracle approach. It's also a good reason to ensure that there is ample liquidity and price stability on the exchanges/AMMs.

We might also want to consider communicating the existence of the exit fee upfront prior to minting. I don't want to deter people from minting, but I also don't want them to be surprised when they go to collect their earnings after a few weeks only to find out that they're underwater.

**Comment by tomlinton** [comment]
2 weeks doesn't seem that unreasonable to me. We want to discourage redeeming and encourage usage or hodling. I agree that it should be clear when minting though.
