### ISSUE TITLE
Suspiciously Identical Gas Estimates

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#931]
**Steps to reproduce**
- Connect an account that has _not_ approved Curve or Origin Vault to move USDC
- Enter 4,000 as the USDC input with OUSD as the output (1,000 does not cause the issue)
- See the same gas estimate for Curve and Origin Vault

<img width="587" alt="Screen Shot 2022-03-04 at 8 03 09 AM" src="https://user-images.githubusercontent.com/273937/156815218-d16bbad4-1382-49ab-a0a3-68b36613bb46.png">

**Comment by sparrowDom** [comment]
This looks weird, but upon investigation there is nothing wrong. If approves have not been called and we need to estimate the gasLimit of transactions according to previously executed transactions. And for vault mint above rebase threshold and curve swap we have them both set to 520k gas limit. Will change the Vault's gas limit to 510k just that it won't look like a mistake.

**Comment by micahalcorn** [comment]
> This looks weird, but upon investigation there is nothing wrong. If approves have not been called and we need to estimate the gasLimit of transactions according to previously executed transactions. And for vault mint above rebase threshold and curve swap we have them both set to 520k gas limit. Will change the Vault's gas limit to 510k just that it won't look like a mistake.

Shouldn't a vault mint above the rebase threshold be much more expensive than a Curve swap?

**Comment by sparrowDom** [comment]
Yeah after checking some example Curve gasLimit swaps: 
- https://etherscan.io/tx/0x3ff7178d8be668649928d86863c78cd249224211efe67f23623017812e7918bb
- https://etherscan.io/tx/0xbf033ffbaf01b808953ca1904d3b0110b50337d60d89c96cd06f3f9a6972d3ca
- https://etherscan.io/tx/0xbce1a2f1e76d4b4f900b3952f34f5f53f8be4a65ccff348661d19b9a3827aa04
- https://etherscan.io/tx/0x12e7c05af3098eaeba9c0bab1e983aeb4d94b0d755899e5ac1cfaa7d02572d3e
- https://etherscan.io/tx/0x9cef860164868e870b28dba761f3e462f7a50c4721921ae7bce5b3d8d248639b

The gasLimits set on the transaction are between ~390k - 600k but the actual gas used is rarely above 320k. Will set the Curve gas estimation to be 350k. Also good to keep in mind we bump that `gasLimit` by 10% anyway (our constant Curve gas limit buffer)
