### ISSUE TITLE
Only require 2 signers for execution of a governance proposal

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#938]
Currently the Governor contract requires 5 signers for both [queueing](https://github.com/OriginProtocol/origin-dollar/blob/c97ab610630a72c4550adf6855857ca25374162c/contracts/contracts/governance/Governor.sol#L119) and [executing](https://github.com/OriginProtocol/origin-dollar/blob/c97ab610630a72c4550adf6855857ca25374162c/contracts/contracts/timelock/Timelock.sol#L176) a proposal.

Reducing the number of signers from 5 to 2 for the execution step (using the strategist role perhaps) would help reducing the overhead involved in getting these proposals thru. And since we would still require 5 signers for enqueueing, we would not compromise on the security of the protocol.

**Comment by franckc** [comment]
We discussed in the community call. Let's gather more data before we prioritize this work
  - The current governor may not get used as much or OUSD once we switch to the new governance model. Though let's double check on that as well as the timeline
  - We'll still use the current governor for OGN
  - The NFT platform may have a need for a governor/timelock contract for the new upcoming products being planned. Need to check with that team what their plans are.

**Comment by franckc** [comment]
It does not look like we'll be have a heavy usage of the governor for the NFT staking project.
=> So this change is low priority for the NFT platform at the moment. Will re-evaluate as we add more contracts to the NFT platform.

**Comment by DanielVF** [comment]
With the new governance contracts, we only need one user to execute after things have come out of timelock. Should be good here.
