### ISSUE TITLE
Allow for more granular price tolerance in the DApp

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-dollar#956]
We currently only allow the user to choose between 1%, 0.5% or 0.25% for their price tolerance. As I understand it, this is telling the AMM to cancel the transaction altogether if they can't guarantee at least X amount. Our current implementation is fine for small amounts but leaves plenty of opportunity for large (7 and 8-figure) traders to get front-run by bots. We should allow custom values & add an explanation bubble about what this is & how it works.

**Comment by franckc** [comment]
@rolandpo Can you take a look? ty :)
