### ISSUE TITLE
Explore using react-query instead of basic fetch

### ISSUE THREAD

**Issue by sparrowDom** [OriginProtocol/origin-dollar#960]
We are doing fetches when a new account connects to the dapp. Failed fetches are not retried and data from a lot of those is not persisted between active account changes (producing more unnecessary network traffic and slower dapp performance). Migrate those fetches to react-query [as in this PR](https://github.com/OriginProtocol/origin-dollar/pull/954) 

There are other places where we use `fetch`. See if any could also benefit from `react-query`. Areas to replace with react-query: 
- [x] [fetching allowances](https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/components/AccountListener.js#L310)
- [x] [fetching apy](https://github.com/OriginProtocol/origin-dollar/blob/master/dapp/src/utils/contracts.js#L382)

**Comment by evgenyboxer** [comment]
I'll take this on.

I'll do it in stages - starting with the Balances.

**Comment by sparrowDom** [comment]
@evgenyboxer did you plan on doing the same thing for allowance calls as well perhaps?

**Comment by evgenyboxer** [comment]
Yep - that would be next.

**Comment by sparrowDom** [comment]
@rolandpo in case you will be looking for issues to work on this one would be great. @evgenyboxer already did it for balances, what is left is allowances and apy (see issue decription)

**Comment by sparrowDom** [comment]
Thanks @rolandpo for great work. This is now done via: https://github.com/OriginProtocol/origin-dollar/pull/971
