### ISSUE TITLE
Consider prompting the user when contract override is abandoned

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#961]
**Steps to reproduce**
- Enter an amount of stablecoins to swap for OUSD
- See Flipper chosen as the default option (for example)
- Override the default selection by clicking on Curve
- Change the input amount slightly
- Contract selection is changed back to default

I _think_ this is the desired behavior because the risk would be greater if we maintained the override and then the new amount resulted in a much worse outcome than it would with the (new) default selection. Also, the contract section changes to a loading state anytime an input is changed. The problem though is that it is often out of view below the fold and the user may not realize that it has happened. We might want to prompt the user with an alert similar to the warning that we display then the default selection is initially overridden. We could also wait until the user attempts to submit the transaction and then require confirmation if (1) the default selection was overridden, (2) the input was changed after the initial warning was displayed, _and_ (3) the current selection is different from the last override.

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue if you dont miind?

**Comment by sparrowDom** [comment]
Posting a suggestion to the problem here: 
<img width="688" alt="Screenshot 2022-06-06 at 10 38 15" src="https://user-images.githubusercontent.com/579910/172126896-56bb2f44-cd4e-42ac-9a50-ef140fcdff7f.png">

IMHO this is a relatively elegant solution that is above the fold and is not hard to switch from a blocking to a non blocking one.
