### ISSUE TITLE
Remove MetaMask custom token prompt

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#962]
I don't think we need this prompt anymore since OUSD has been added as a supported token. However, we may need to reuse this for OGV or veOGV if we're unable to get those integrated quickly. For some reason, I didn't see this until after swapping my OUSD back to DAI after having swapped DAI for OUSD in the same session.

<img width="511" alt="Screen Shot 2022-03-28 at 10 35 10 PM" src="https://user-images.githubusercontent.com/273937/160540705-5920e2fe-c951-464f-8b2b-748018e39e5b.png">

**Comment by ritikBhandari** [comment]
So for right now we dont need this prompt but in future we might need this right?

**Comment by micahalcorn** [comment]
> So for right now we dont need this prompt but in future we might need this right?

Correct, we should not be showing this prompt for OUSD. I'm seeing it after swapping DAI for OUSD despite the OUSD being shown in my MetaMask.

<img width="993" alt="Screen Shot 2022-04-18 at 8 08 06 AM" src="https://user-images.githubusercontent.com/273937/163828895-31fa54ad-ecd0-442e-895e-0365521736df.png">

**Comment by sparrowDom** [comment]
done via: https://github.com/OriginProtocol/origin-dollar/pull/979
