### ISSUE TITLE
Maintain allowance button styling when transaction is rejected

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#964]
**Reproduction steps**:
- See an allowance button for a contract that has not yet been approved
- Note that the button is lighter on hover
- Click to generate the MetaMask prompt for the approval
- Reject the transaction
- Note that the button slightly loses some opacity (and shouldn't)

https://www.loom.com/share/3459fc778b30499388f5c67a1edac3cc

**Comment by rolandpo** [comment]
included in #958

**Comment by rolandpo** [comment]
included in #958
