### ISSUE TITLE
Wrap/unwrap OUSD interface

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#981]
Conclusions from **[wOUSD meets ousd.com](https://docs.google.com/document/d/1Fvos-sCp4_yrZHbLgDyZ9Z0OA2qRsSsOAMpKVDkudAI/edit#)**:
- Let’s start by creating a separate wrap/unwrap form that lives inside of the same DApp.
- The new form should be accessible from [ousd.com/swap](https://ousd.com/swap) via a nav link (Wrap OUSD).
- The wrap form should be accompanied by a similar info feed on the right rail like the swap form is.
- A card should be pinned to the top explaining in a few lines why the user might want to wrap OUSD. This card should behave similarly to the current “Get optional smart contract insurance” card except it should be displayed alongside the wrap form rather than the swap form.
- Wrap and unwrap transactions should appear in the feed alongside the wrap form just like swap transactions appear alongside the swap form. Approval transactions should be treated the same.
- When wrapping, an allowance will be required for the contract to move the user’s OUSD. We should have the same Approve+Wrap button pair that we have for Approve+Swap with the same behavior.
- Numbers above and in the wrap form should be denominated in OUSD, not USD. Let’s not worry about any USD/OUSD exchange rates beyond what we already do in the swap route comparisons.
- The wrap and unwrap transactions are described in [docs.ousd.com/core-concepts/wrapped-ousd](https://docs.ousd.com/core-concepts/wrapped-ousd) and the contract address is listed in [docs.ousd.com/smart-contracts/registry](https://docs.ousd.com/smart-contracts/registry).
- Put all this behind a feature gate that is controlled by a localstorage variable. We don't want to activate any wOUSD frontend for the average user until after the Solidified audit is completed.

Mockups (not public ☹):
- [Wrap](https://zpl.io/O0MK1A8)
- [Unwrap](https://zpl.io/JEn91WJ)
- [History (OUSD)](https://zpl.io/KGwyA1R)
- [History (wOUSD)](https://zpl.io/09lqJwE)
- [Swap w/CTA](https://zpl.io/noPL0Zx)

**Comment by sparrowDom** [comment]
@micahalcorn sorry for being late to the party. From the engineering standpoint it should be the same effort (if not maybe slightly easier) to integrate the wOusd in the current dapp. Mostly because almost no UI elements need to be built, just some logic added to handle `wOusd` in a special manner similarly to how we handle the redeem `mix` specially. 

If there is not a strong UX reason to separating it I would rather integrate it.

**Comment by rolandpo** [comment]
done in #988
