### ISSUE TITLE
New OGN staking CTA

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#983]
Once we're ready to disable OGN staking in its current form and we [stop linking to the Earn OGN page](https://github.com/OriginProtocol/origin-dollar/issues/982), we will still want to update the content above the fold for a couple of reasons. There are a variety of links around the web pointing people to this page. We could do a permanent redirect, but it's probably simpler to advertise the new staking program from here rather than reimplement the unstake/claim functionality on the new staking page. As long as there are users who need to claim their in-progress stakes, then we will need to maintain this existing page.

<img width="983" alt="Screen Shot 2022-04-19 at 7 33 10 PM" src="https://user-images.githubusercontent.com/273937/164135611-d244fd75-c6d5-4249-a1bd-bd10eee53d64.png">

**Comment by micahalcorn** [comment]
Here's a mockup for a new banner that we should use to replace this one: https://zpl.io/1y6xeQm

**Comment by rolandpo** [comment]
done in #1034
