### ISSUE TITLE
Small screen overflow

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-dollar#999]
Now that we have four nav links, they are wrapping on small screens. Additionally, the connect button is getting cut off due to the addition of the IPFS button. Since we have the language select in the footer, I think we can probably remove it from the nav if that helps. Let's also repair the vertical alignment of the APY.

![IMG_3475](https://user-images.githubusercontent.com/273937/168963224-05359c23-381a-418c-9e04-f00fcb6467c0.PNG)

**Comment by micahalcorn** [comment]
While we're at it, we should fix the footer as well. The links should be wrapped and left-aligned while the "Built by" and the language select should be wrapped and right-aligned.

![IMG_3476](https://user-images.githubusercontent.com/273937/168964486-be949c80-4a07-4bf7-82e2-1d1a74eab6ed.PNG)

**Comment by WilHolt** [comment]
Hello, could I help with this issue? I think it is a good first issue @micahalcorn 😉

**Comment by micahalcorn** [comment]
> Hello, could I help with this issue? I think it is a good first issue @micahalcorn 😉

I think that @rolandpo is already working on this one but let us know if you see something else you would like to pick up, thanks!
